### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Table 'ds1.t_order_order_items' doesn't exist 

### ISSUE THREAD

**Issue by LX1993728** [apache/incubator-shardingsphere#1689]
## Bug Report
# this ‘s my sharding config
```
sharding.jdbc.datasource.names=ds0,ds1,ds2
sharding.jdbc.datasource.ds0.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds0.url=jdbc:mysql://localhost:3306/ds0?serverTimezone=GMT%2B8`
sharding.jdbc.datasource.ds0.username=root
sharding.jdbc.datasource.ds0.password=root

sharding.jdbc.datasource.ds1.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds1.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds1.url=jdbc:mysql://localhost:3306/ds1?serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds1.username=root
sharding.jdbc.datasource.ds1.password=root

sharding.jdbc.datasource.ds2.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.ds2.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds2.url=jdbc:mysql://localhost:3306/ds2?serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds2.username=root
sharding.jdbc.datasource.ds2.password=root

sharding.jdbc.config.sharding.default-data-source-name=ds2
sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression=ds$->{user_id % 3}
sharding.jdbc.config.sharding.default-key-generator-class-name=liuxun.jpa.shard.config.SnowFlakeGenerator

sharding.jdbc.config.sharding.tables.t_order.actual-data-nodes=ds$->{0..2}.t_order$->{0..1}
sharding.jdbc.config.sharding.tables.t_order.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.t_order.table-strategy.inline.algorithm-expression=t_order$->{order_id % 2}
sharding.jdbc.config.sharding.tables.t_order.key-generator-column-name=order_id
sharding.jdbc.config.sharding.tables.t_order_item.actual-data-nodes=ds$->{0..2}.t_order_item$->{0..1}
sharding.jdbc.config.sharding.tables.t_order_item.table-strategy.inline.sharding-column=order_id
sharding.jdbc.config.sharding.tables.t_order_item.table-strategy.inline.algorithm-expression=t_order_item$->{order_id % 2}
sharding.jdbc.config.sharding.tables.t_order_item.key-generator-column-name=order_item_id
sharding.jdbc.config.sharding.binding-tables=t_order,t_order_item

sharding.jdbc.config.sharding.tables.t_user.actual-data-nodes=ds$->{0..2}.t_user$->{0..1}
sharding.jdbc.config.sharding.tables.t_user.table-strategy.inline.sharding-column=user_id
sharding.jdbc.config.sharding.tables.t_user.table-strategy.inline.algorithm-expression=t_user$->{user_id % 2}
sharding.jdbc.config.sharding.tables.t_user.key-generator-column-name=user_id

sharding.jdbc.config.sharding.tables.t_product.actual-data-nodes=ds$->{0..2}.t_product$->{0..1}
sharding.jdbc.config.sharding.tables.t_product.database-strategy.inline.sharding-column=product_id
sharding.jdbc.config.sharding.tables.t_product.database-strategy.inline.algorithm-expression=ds$->{product_id % 2}
sharding.jdbc.config.sharding.tables.t_product.table-strategy.inline.sharding-column=product_id
sharding.jdbc.config.sharding.tables.t_product.table-strategy.inline.algorithm-expression=t_product$->{product_id % 2}
sharding.jdbc.config.sharding.tables.t_product.key-generator-column-name=product_id

sharding.jdbc.config.sharding.props.sql.show=true

```
I have configured three database, each with two tables in each database including t_order , t_order_item, t_user and t_product. The default data source is ds0 but I have an error when querying orders based on the amount range.

```
java.sql.SQLSyntaxErrorException: Table 'ds1.t_order_order_items' doesn't exist at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.13.jar:8.0.13] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.13.jar:8.0.13] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.13.jar:8.0.13] 
```

How to solve it? This table is automatically generated by shading, and in the default data source ds2, .t_order_order_items

**Comment by terrymanu** [comment]
Hi, can you fill necessary information below?

**Comment by terrymanu** [comment]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by LX1993728** [comment]
I am using the 3.0.0 version of sharding-sphere.
And I am using a project integrated with springboot+jpa+sharding-jdbc.
Shading-rule is shown in the issue above.
My expected behavior is to be able to query all order data. My Order entity class is as follows:
```
@Entity
@Table(name = "t_order")
public class Orders implements Serializable {
    public Orders() {
    }
    @Id
    @Column(name = "order_id")
//    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "UserIdentityGenerator")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long orderId;

    @ManyToOne(targetEntity =User.class)
    @JoinColumn(name = "user_id")
    private User user;

    @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.EAGER)
    private List<OrderItem> orderItems = new ArrayList<>();

    @Column
    private Double total; // 总金额
   // setter and getter method
    ......
```
The relevant code of my query order is as follows:
```
@GetMapping("/range")
    public Object getOrdersByTotalRange(){
        List<Orders> list = em.createQuery("SELECT o FROM Orders o WHERE o.total BETWEEN 400.00 AND 2000.00", Orders.class).getResultList();
        logger.info("++++++++ {}++++++++",list.size());
        return list;
    }

    @GetMapping("/count")
    public Object getCountOfOrder(){
        TypedQuery<Orders> query = em.createQuery("SELECT o FROM Orders o ", Orders.class);

        List<Orders> resultList=query.getResultList();
        return resultList.size();
    }
```
The above two methods will report the above mentioned exceptions. 
The association table t_order_order_items will only be generated in the default data source. For example, if my default data source is ds0, only the ds0.t_order_order_items relational table will be generated, but when I query the orders logical table, it will be routed to ds1.t_order_order_items. How should I solve this problem?

**Comment by LX1993728** [comment]
The address of my Example codes is: [https://github.com/LX1993728/sharding-jdbc-example.git](url)
 After started application need init data :  [http://localhost/init/data](url)

**Comment by KomachiSion** [comment]
Hi @LX1993728, I try to recurrent this problem by your example codes, but failed.
Table **t_order_order_items** is created in ds2 correctly, and no exception be thrown.
The page of http://localhost/init/data show `success` in browser.

Would you mind try again and provide more information?

**Comment by LX1993728** [comment]
> Hi @LX1993728, I try to recurrent this problem by your example codes, but failed.
> Table **t_order_order_items** is created in ds2 correctly, and no exception be thrown.
> The page of http://localhost/init/data show `success` in browser.
> 
> Would you mind try again and provide more information?
Sorry, there is no problem with initializing the data. But when I query, I will throw the exception mentioned above. Such as when querying order data
[http://localhost/order/range](url)
[http://localhost/order/count](url)

**Comment by KomachiSion** [comment]
BTW, I found that Hibernate will create foreign key for **t_order** --> **t_user** and **t_order_item** --> **t_product**. ShardingSphere does not support foreign keys for sharding tables currently.
I suggest you change **t_product** to boardcast table too, and bind **t_order** and **t_user**.

**Comment by KomachiSion** [comment]
Can you update your example code?

**Comment by LX1993728** [comment]
Yes, after I update. Rerun and throw an exception when creating data. I debugged it and found that it should be wrong when inserting the broadcast table` t_order_order_items data`. It is said that it is expected to insert one but actually inserts multiple pieces. It is reasonable to insert data into the broadcast table. It should be inserted correctly. An exception should be thrown.
```
Hibernate: update t_order set total=?, user_id=? where order_id=?
Hibernate: insert into t_order_order_items (orders_order_id, order_items) values (?, ?)
2018-12-28 12:31:17.822 ERROR 44380 --- [p-nio-80-exec-1] o.h.i.ExceptionMapperStandardImpl        : HHH000346: Error during managed flush [org.hibernate.jdbc.BatchedTooManyRowsAffectedException: Batch update returned unexpected row count from update [0]; actual row count: 3; expected: 1]
2018-12-28 12:31:17.823  INFO 44380 --- [p-nio-80-exec-1] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2018-12-28 12:31:17.841 ERROR 44380 --- [p-nio-80-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Batch update returned unexpected row count from update [0]; actual row count: 3; expected: 1; nested exception is org.hibernate.jdbc.BatchedTooManyRowsAffectedException: Batch update returned unexpected row count from update [0]; actual row count: 3; expected: 1] with root cause

org.hibernate.jdbc.BatchedTooManyRowsAffectedException: Batch update returned unexpected row count from update [0]; actual row count: 3; expected: 1
	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:77) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.persister.collection.AbstractCollectionPersister.recreate(AbstractCollectionPersister.java:1340) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:50) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1454) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:511) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3283) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2479) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:178) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:39) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:271) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:98) ~[hibernate-core-5.3.7.Final.jar:5.3.7.Final]
```

**Comment by LX1993728** [comment]
I submitted the revised code and troubled me to help me solve it.

**Comment by LX1993728** [comment]
I submitted the modified code.
Ask for help and look.
Grateful.

**Comment by KomachiSion** [comment]
OK, I have recurrent this problem, it may be a row count bug in broadcast table.
We will confirm and feedback as soon as possible.

**Comment by terrymanu** [comment]
duplicate with #1696
