### ISSUE TITLE
H2Lexer 为什么不识别"`"

### ISSUE THREAD

**Issue by yinfang678** [apache/incubator-shardingsphere#1796]
H2Lexer 
@Override
protected boolean isIdentifierBegin(final char ch) {
        return CharType.isAlphabet(ch) || '\"' == ch || '_' == ch || '$' == ch;
}

i use hibernate + mysql
some params like behind
---------------------------------
@Column(name = "`name`")
private String name;
---------------------------------
then errors happen when excuting unit test with h2

like
--------------------------------
io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'ERROR', actual token is 'DOT', literals is '.'.

	at io.shardingsphere.core.parsing.lexer.Lexer.nextToken(Lexer.java:69)
	at io.shardingsphere.core.parsing.lexer.LexerEngine.nextToken(LexerEngine.java:61)
	at io.shardingsphere.core.parsing.parser.clause.SelectListClauseParser.parseCommonOrStarSelectItem(SelectListClauseParser.java:127)
	at io.shardingsphere.core.parsing.parser.clause.SelectListClauseParser.parseSelectItem(SelectListClauseParser.java:86)
	at io.shardingsphere.core.parsing.parser.clause.SelectListClauseParser.parse(SelectListClauseParser.java:68)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
