### ISSUE TITLE
order by not support double value

### ISSUE THREAD

**Issue by trojanliu** [apache/incubator-shardingsphere#2008]
shardingsphere 3.1

order by not support double value

like:
order by st_distance(point(113.319534 , 23.12337) , point(longitude , latitude) ) asc

errormessage:
Caused by: java.lang.NumberFormatException: For input string: "113.319534"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.7.0_79]
	at java.lang.Integer.parseInt(Integer.java:492) ~[?:1.7.0_79]
	at java.math.BigInteger.<init>(BigInteger.java:338) ~[?:1.7.0_79]
	at io.shardingsphere.core.util.NumberUtil.getExactlyNumber(NumberUtil.java:72) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.parsing.antlr.extractor.impl.dql.OrderByItemExtractor.extract(OrderByItemExtractor.java:49) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.parsing.antlr.extractor.impl.dql.OrderByExtractor.extract(OrderByExtractor.java:43) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.parsing.antlr.extractor.SQLSegmentsExtractorEngine.extract(SQLSegmentsExtractorEngine.java:44) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.parsing.antlr.AntlrParsingEngine.parse(AntlrParsingEngine.java:60) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:59) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:82) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:62) ~[sharding-core-3.1.0.jar:?]
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:214) ~[sharding-jdbc-core-3.1.0.jar:?]
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:106) ~[sharding-jdbc-core-3.1.0

**Comment by terrymanu** [comment]
Order by cannot support function calucate
