### ISSUE TITLE
sharding_proxy : lack of config file for config_sharding_masterslave.yaml

### ISSUE THREAD

**Issue by msnetc** [apache/incubator-shardingsphere#2109]
it is difficult for me to write config file for config_sharding_masterslave.yaml ,
since it lack of demo file for sharding and master_slave feature template file.

 can sharding_proxy suppply template file of config_sharding_masterslave.yaml ?

**Comment by terrymanu** [comment]
Document may help you: https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/

**Comment by msnetc** [comment]
> Document may help you: https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/
the config file  in your can not work in sharding-proxy 3.0.0. can u supply one config template ?

**Comment by msnetc** [comment]
> Document may help you: https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/

the config file in your can not work in sharding-proxy 3.0.0.  can u supply one config template ?
ERROR:
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'broadcastTables' on class: io.shardingsphere.core.yaml.sharding.YamlShardingRuleConfiguration
at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
... 13 mor

**Comment by terrymanu** [comment]
for 3.x should be: https://shardingsphere.apache.org/document/legacy/3.x/document/en/manual/sharding-proxy/configuration/

**Comment by terrymanu** [comment]
Can you close issue if your question is resolved?

**Comment by msnetc** [comment]
thanks @terrymanu
