### ISSUE TITLE
supported hibernate insert values ( )

### ISSUE THREAD

**Issue by LinXinHun** [apache/incubator-shardingsphere#2130]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
Yes,the hight version sharding-sphere  cannot support hibernate
id generate greater than 1.4.2 like 3.1.0,will throw exception when insertparse sql like (insert table_name values ( )) values contains blank.
### Describe the feature you would like.
I'll change ParsingSQLRouter's construtor or InsertValuesClauseParser's parseValues  for support this problem.

**Comment by terrymanu** [comment]
I am not get your point. Can you provide a demo?

**Comment by LinXinHun** [comment]
> I am not get your point. Can you provide a demo?

like hibernate automatic generation sql [insert into some_table values ( )], 
 '( )' contains blank will throw exception:
io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'END', literals is ''

but the 1.4.2 version can support it .

**Comment by LinXinHun** [comment]
`insert into _id_generate values ( )`

**Comment by LinXinHun** [comment]
`insert into id_generate values ( )`

**Comment by terrymanu** [comment]
Could you provide full SQL, and exception info?

**Comment by LinXinHun** [comment]
My full SQL : `insert into coupon_code_id_generate values ( )`
And Exception info :
io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'END', literals is ''.
	at io.shardingsphere.core.parsing.lexer.LexerEngine.accept(LexerEngine.java:122)
	at io.shardingsphere.core.parsing.parser.clause.InsertValuesClauseParser.parseValues(InsertValuesClauseParser.java:123)
	at io.shardingsphere.core.parsing.parser.clause.InsertValuesClauseParser.parse(InsertValuesClauseParser.java:79)
	at io.shardingsphere.core.parsing.parser.sql.dml.insert.AbstractInsertParser.parse(AbstractInsertParser.java:71)
	at io.shardingsphere.core.parsing.parser.sql.dml.insert.AbstractInsertParser.parse(AbstractInsertParser.java:41)
	at io.shardingsphere.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:60)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:91)
	at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:229)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:124)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2919)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3490)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:626)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:280)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:261)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:306)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:782)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:767)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by codefairy08** [comment]
@LinXinHun It is not valid sql, please see [INSERT Syntax](https://dev.mysql.com/doc/refman/8.0/en/insert.html),
![image](https://user-images.githubusercontent.com/39583929/55306692-a1009980-5487-11e9-9d13-fa0bfa85f0b0.png)
![image](https://user-images.githubusercontent.com/39583929/55306722-b970b400-5487-11e9-85fe-25eb8ac3fc9e.png)
According to the syntax, there is at least one value in parentheses.

**Comment by LinXinHun** [comment]
No，I can execute it for mysql successful。please try it：
`insert into coupon_code_id_generate values ( )`

**Comment by terrymanu** [comment]
@LinXinHun Can you show your table create DDL?

**Comment by codefairy08** [comment]
@LinXinHun  i use this sql in MySQL 5.7 and  MySQL8.0, both of them raised this error. please show you create table statement
![image](https://user-images.githubusercontent.com/39583929/55694378-8332b780-59e6-11e9-92a2-526ecffb7b55.png)
