### ISSUE TITLE
java.io.NotSerializableException: java.io.StringReader

### ISSUE THREAD

**Issue by xfyang1989** [apache/incubator-shardingsphere#2181]
When I insert data into a field of text type in the database, I report the following error. It seems that sharding has rewritten this field. How to solve this problem?

java.io.NotSerializableException: java.io.StringReader
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3824)
at io.shardingsphere.shardingjdbc.jdbc.adapter.invocation.JdbcMethodInvocation.invoke(JdbcMethodInvocation.java:47)
	at io.shardingsphere.shardingjdbc.jdbc.adapter.AbstractShardingPreparedStatementAdapter.replaySetParameter(AbstractShardingPreparedStatementAdapter.java:264)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.setParametersForStatements(ShardingPreparedStatement.java:194)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.initPreparedStatementExecutor(ShardingPreparedStatement.java:189)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:136)

**Comment by tuohai666** [comment]
Duplicate with https://github.com/apache/incubator-shardingsphere/issues/1567.
Will be fixed together.

**Comment by tuohai666** [comment]
Fixed via https://github.com/apache/incubator-shardingsphere/pull/2388.
