### ISSUE TITLE
Tip Must have sharding column with subquery error

### ISSUE THREAD

**Issue by liunancun** [apache/incubator-shardingsphere#2192]
sharding version:
`<dependency>
	<groupId>io.shardingsphere</groupId>
	<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
	<version>3.1.0</version>
</dependency>`

database:
ds1
  ├── user
  └── t_one
ds2
  ├── user
  └── t_two

application.properties config:
`sharding.jdbc.datasource.names=ds1,ds2
sharding.jdbc.config.sharding.default-data-source-name=ds1
sharding.jdbc.config.props.sql.show=true
sharding.jdbc.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds1.url=jdbc:mysql://192.168.31.102:3306/ds1
sharding.jdbc.datasource.ds1.username=root
sharding.jdbc.datasource.ds1.password=root
sharding.jdbc.datasource.ds2.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds2.url=jdbc:mysql://192.168.31.102:3306/ds2
sharding.jdbc.datasource.ds2.username=root
sharding.jdbc.datasource.ds2.password=root
sharding.jdbc.config.sharding.tables.t_two.actual-data-nodes=ds2.t_two`

Execute SQL:
`select * from t_two where id in (select id from user)`

Error message:
`java.lang.IllegalStateException: Must have sharding column with subquery.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.mergeShardingValueForSubQuery(ParsingSQLRouter.java:154)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:100)
	at io.shardingsphere.core.routing.StatementRoutingEngine.route(StatementRoutingEngine.java:55)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.sqlRoute(ShardingStatement.java:247)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.executeQuery(ShardingStatement.java:89)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:438)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:375)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:451)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:461)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:489)
	at com.bessky.jdbc.JdbcApplicationTests.test(JdbcApplicationTests.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)`

**Comment by terrymanu** [comment]
This is a excepted exception, please try to understand the error message

**Comment by liunancun** [comment]
我是按业务分库的，没有根据字段规则分库，那要怎么办呢？
I am sub-library according to the business, and there is no sub-library according to the field rules. What should I do?

**Comment by liunancun** [comment]
@terrymanu

**Comment by liunancun** [comment]
@terrymanu 
我是按业务分库的，没有根据字段规则分库，那要怎么办呢？
I am sub-library according to the business, and there is no sub-library according to the field rules. What should I do?

**Comment by wgy8283335** [comment]
@liunancun ，try hint.

**Comment by liunancun** [comment]
@wgy8283335 
具体要怎么做，可以给个参考吗？
How can I do it, can I give a reference?

**Comment by wgy8283335** [comment]
Reference to the link: https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/hint-example.

**Comment by liunancun** [comment]
@wgy8283335 This is an example of version 4.0. Is there a similar version of 3.0?

**Comment by wgy8283335** [comment]
@liunancun. Choose '3.1.0' branch in github
