### ISSUE TITLE
sharding-proxy:java.sql.SQLException: Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by Bingjian-Zhu** [apache/incubator-shardingsphere#2304]
follow this :
1.docker pull shardingsphere/sharding-proxy:3.0.0
2.docker run -d -v /my_work_dir/conf:/opt/sharding-proxy/conf --env PORT=3308 -p13308:3308 shardingsphere/sharding-proxy:3.0.0

make this mistake:
java.sql.SQLException: Unknown system variable 'query_cache_size'

MySQL VERSION is 8.0.15.

I do not use the sharding-jdbc.

**Comment by terrymanu** [comment]
Can you provide more details for exception info and how to reproduce it?

**Comment by Bingjian-Zhu** [comment]
**my server.yaml is :**
authentication:
  username: user
  password: password
props:
#  max.connections.size.per.query: 1
  acceptor.size: 4 
  executor.size: 2 
  proxy.transaction.enabled: false 
  proxy.opentracing.enabled: false 
  sql.show: true 
**config-master_slave.yaml is:**
schemaName: master_slave_db

dataSources:
 master_ds:
   url: jdbc:mysql://192.168.2.3:3306/test_db?serverTimezone=UTC&useSSL=false
   username: root
   password: root
   maximumPoolSize: 20
 slave_ds_0:
   url: jdbc:mysql://192.168.2.190:3306/test_db?serverTimezone=UTC&useSSL=false
   username: root
   password: root
   maximumPoolSize: 20

masterSlaveRule:
 name: ms_test_db
 masterDataSourceName: master_test_db
 slaveDataSourceNames:
   - slave_test_db

**and the detail mistake is:**
00:43:11,347 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
00:43:11,348 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
00:43:11,348 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/shardi
ng-proxy/conf/logback.xml]
00:43:11,349 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on t
he classpath.
00:43:11,349 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/s
harding-proxy/lib/sharding-proxy-3.0.0.jar!/logback.xml]
00:43:11,349 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/opt/shard
ing-proxy/conf/logback.xml]
00:43:11,491 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
00:43:11,500 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.l
ogback.core.ConsoleAppender]
00:43:11,518 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [console]
00:43:11,529 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.
classic.encoder.PatternLayoutEncoder] for [encoder] property
00:43:11,651 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.shardingsphere] to
 INFO
00:43:11,651 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.shardingspher
e] to false
00:43:11,651 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger
[io.shardingsphere]
00:43:11,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.shardingsphere.cor
e.executor.threadlocal.ExecutorExceptionHandler] to OFF
00:43:11,652 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
00:43:11,652 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger
[ROOT]
00:43:11,652 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
00:43:11,653 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@384561a6 - Registering current configuration as sa
fe fallback point

[INFO ] 00:43:11.691 [main] c.a.icatch.provider.imp.AssemblerImp - Loaded jar:file:/opt/sharding-proxy/lib/transactions-
4.0.4.jar!/transactions-defaults.properties
[INFO ] 00:43:11.695 [main] c.a.icatch.provider.imp.AssemblerImp - Loaded jar:file:/opt/sharding-proxy/lib/sharding-tran
saction-3.0.0.jar!/jta.properties
[WARN ] 00:43:11.709 [main] c.a.icatch.provider.imp.AssemblerImp - Thanks for using Atomikos! Evaluate http://www.atomik
os.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professio
nal support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
[INFO ] 00:43:11.724 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.allow_subtransactions = tr
ue
[INFO ] 00:43:11.724 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.recovery_delay = 1000000
[INFO ] 00:43:11.724 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.automatic_resource_registr
ation = true
[INFO ] 00:43:11.724 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_max_retries = 5
[INFO ] 00:43:11.724 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.client_demarcation = false
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.threaded_2pc = false
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.serial_jta_transactions =
false
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.log_base_dir = ./
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.rmi_export_class = none
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.max_actives = 10000
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.checkpoint_interval = 500
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.enable_logging = false
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.log_base_name = tmlog
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.max_timeout = 300000
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.trust_client_tm = false
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.tm_unique_name = 172.17.0.
2.tm
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: java.naming.factory.initial = com.sun.jndi.rmi
.registry.RegistryContextFactory
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.forget_orphaned_log_entrie
s_delay = 86400000
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_retry_interval = 1000
0
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: java.naming.provider.url = rmi://localhost:109
9
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.force_shutdown_on_vm_exit
= false
[INFO ] 00:43:11.725 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_jta_timeout = 1000
000
[INFO ] 00:43:11.726 [main] c.a.icatch.provider.imp.AssemblerImp - Using default (local) logging and recovery...
[INFO ] 00:43:11.970 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[ERROR] 00:43:13.544 [main] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Unknown system variable 'query_cache_size'
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
        at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3766)
        at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3229)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2238)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCRawBackendDataSourceFactory.build(JDBCRawBackendD
ataSourceFactory.java:59)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.getNormalDataSourceMap(JDBCBack
endDataSource.java:65)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.createDataSourceMap(JDBCBackend
DataSource.java:58)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.<init>(JDBCBackendDataSource.ja
va:52)
        at io.shardingsphere.shardingproxy.runtime.ShardingSchema.<init>(ShardingSchema.java:68)
        at io.shardingsphere.shardingproxy.runtime.GlobalRegistry.init(GlobalRegistry.java:128)
        at io.shardingsphere.shardingproxy.runtime.GlobalRegistry.init(GlobalRegistry.java:112)
        at io.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:84)
        at io.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:65)
Exception in thread "main" io.shardingsphere.core.exception.ShardingException: Can not build data source, name is `maste
r_ds`.
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.getNormalDataSourceMap(JDBCBack
endDataSource.java:69)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.createDataSourceMap(JDBCBackend
DataSource.java:58)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.<init>(JDBCBackendDataSource.ja
va:52)
        at io.shardingsphere.shardingproxy.runtime.ShardingSchema.<init>(ShardingSchema.java:68)
        at io.shardingsphere.shardingproxy.runtime.GlobalRegistry.init(GlobalRegistry.java:128)
        at io.shardingsphere.shardingproxy.runtime.GlobalRegistry.init(GlobalRegistry.java:112)
        at io.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:84)
        at io.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:65)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system vari
able 'query_cache_size'
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:528)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:520)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCRawBackendDataSourceFactory.build(JDBCRawBackendD
ataSourceFactory.java:59)
        at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.getNormalDataSourceMap(JDBCBack
endDataSource.java:65)
        ... 7 more
Caused by: java.sql.SQLException: Unknown system variable 'query_cache_size'
       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
        at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3766)
        at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3229)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2238)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:428)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:499)
        ... 11 more
~

**Comment by Bingjian-Zhu** [comment]
> Can you provide more details for exception info and how to reproduce it?

I've listed my .yaml and the all exception, thanks.

**Comment by cherrylzhao** [comment]
@Bingjian-Zhu I'm sorry for the late reply.
it seems that your config is wrong
```
masterSlaveRule:
 name: ms_test_db
 masterDataSourceName: master_test_db
 slaveDataSourceNames:
   - slave_test_db
```

it should be
```
masterSlaveRule:
 name: ms_test_db
 masterDataSourceName: master_ds
 slaveDataSourceNames:
   - slave_ds_0
```

**Comment by Bingjian-Zhu** [comment]
> @Bingjian-Zhu I'm sorry for the late reply.
> it seems that your config is wrong
> 
> ```
> masterSlaveRule:
>  name: ms_test_db
>  masterDataSourceName: master_test_db
>  slaveDataSourceNames:
>    - slave_test_db
> ```
> 
> it should be
> 
> ```
> masterSlaveRule:
>  name: ms_test_db
>  masterDataSourceName: master_ds
>  slaveDataSourceNames:
>    - slave_ds_0
> ```

I follow your config, but still get the same mistake.

**Comment by Bingjian-Zhu** [comment]
@cherrylzhao I follow your config, but still get the same mistake.

**Comment by cherrylzhao** [comment]
please test whether  you can connect to `192.168.2.3:3306` within your proxy docker environment.
we suppose that you can use docker-compose to startup a proxy and mysql docker independent, but they can communication with  each other.
you can see detail [here](https://github.com/apache/incubator-shardingsphere-example#using-docker-compose-to-config-startup-environment)

**Comment by Bingjian-Zhu** [comment]
> please test whether you can connect to `192.168.2.3:3306` within your proxy docker environment.
> we suppose that you can use docker-compose to startup a proxy and mysql docker independent, but they can communication with each other.
> you can see detail [here](https://github.com/apache/incubator-shardingsphere-example#using-docker-compose-to-config-startup-environment)

you are right! I change the `192.168.2.3:3306` and can run. thanks
