### ISSUE TITLE
Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by wzswzjwsj** [apache/incubator-shardingsphere#2307]
[2019-04-30 14:40:34.715 INFO ] [http-bio-8888-exec-141] {SQLLogger.java:71} log - Rule Type: sharding
[2019-04-30 14:40:34.716 INFO ] [http-bio-8888-exec-141] {SQLLogger.java:71} log - Logic SQL: SELECT DISTINCT org_trade_order_no FROM mpay_refund
    WHERE create_time BETWEEN ? AND ?
     
     
      AND refund_status IN
       (  
        ?
       , 
        ?
       ) 
     
     
      AND ledger_status IN
       (  
        ?
       , 
        ?
       , 
        ?
       ) 
     
    ORDER BY create_time ASC
    LIMIT ?
[2019-04-30 14:40:34.716 INFO ] [http-bio-8888-exec-141] {SQLLogger.java:71} log - SQLStatement: SelectStatement(super=DQLStatement(super=io.shardingsphere.core.parsing.parser.sql.dql.select.SelectStatement@441064f0), containStar=false, firstSelectItemStartPosition=16, selectListLastPosition=35, groupByLastPosition=0, items=[io.shardingsphere.core.parsing.parser.context.selectitem.DistinctSelectItem@49f90609], groupByItems=[], orderByItems=[OrderItem(owner=Optional.absent(), name=Optional.of(create_time), orderDirection=ASC, nullOrderDirection=ASC, index=-1, expression=null, alias=Optional.of(ORDER_BY_DERIVED_0))], limit=Limit(offset=null, rowCount=LimitValue(value=10, index=7, boundOpened=false)), subQueryStatement=null, subQueryStatements=[], subQueryConditions=[])
[2019-04-30 14:40:34.717 INFO ] [http-bio-8888-exec-141] {SQLLogger.java:71} log - Actual SQL: TR01 ::: SELECT DISTINCT org_trade_order_no , create_time AS ORDER_BY_DERIVED_0 FROM mpay_refund
    WHERE create_time BETWEEN ? AND ?
     
     
      AND refund_status IN
       (  
        ?
       , 
        ?
       ) 
     
     
      AND ledger_status IN
       (  
        ?
       , 
        ?
       , 
        ?
       ) 
     
    ORDER BY create_time ASC
    LIMIT ? ::: [[2019-04-30 14:00:44, 2019-04-30 14:24:02, INIT, PROCESSING, WAIT_ACCT, PROCESSING, SUCCESS, 10]]
[2019-04-30 14:40:34.718 INFO ] [http-bio-8888-exec-141] {SQLLogger.java:71} log - Actual SQL: TR02 ::: SELECT DISTINCT org_trade_order_no , create_time AS ORDER_BY_DERIVED_0 FROM mpay_refund
    WHERE create_time BETWEEN ? AND ?
     
     
      AND refund_status IN
       (  
        ?
       , 
        ?
       ) 
     
     
      AND ledger_status IN
       (  
        ?
       , 
        ?
       , 
        ?
       ) 
     
    ORDER BY create_time ASC
    LIMIT ? ::: [[2019-04-30 14:00:44, 2019-04-30 14:24:02, INIT, PROCESSING, WAIT_ACCT, PROCESSING, SUCCESS, 10]]
[2019-04-30 14:40:34.855 ERROR] [http-bio-8888-exec-141] {MpayRefundDaoImpl.java:286} queryTradeOrderNos - queryTradeOrderNos.Exception
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-1.3.1.jar:1.3.1]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.1.jar:1.3.1]
        at com.sun.proxy.$Proxy86.selectList(Unknown Source) ~[?:?]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-1.3.1.jar:1.3.1]
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.5.jar:3.4.5]
        at com.sun.proxy.$Proxy92.queryTradeOrderNos(Unknown Source) ~[?:?]
        at XXXXX.MpayRefundDaoImpl.queryTradeOrderNos(MpayRefundDaoImpl.java:284) [XXXXX-core-1.0.jar:?]
        at XXXXX.MicroPayTradeQuartzServiceImpl.queryRefundQuartz(MicroPayTradeQuartzServiceImpl.java:2365) [XXXXXX-core-1.0.jar:?]
        at MicroPayTradeQuartzFacadeImpl.queryRefundQuartz(MicroPayTradeQuartzFacadeImpl.java:717) [XXXXX-core-1.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at XXXXX.RemoteProxyHandler.invoke(RemoteProxyHandler.java:25) [XXXXX-rmi-1.9.jar:?]
        at com.sun.proxy.$Proxy134.queryRefundQuartz(Unknown Source) [?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.remoting.support.RemoteInvocationTraceInterceptor.invoke(RemoteInvocationTraceInterceptor.java:78) [spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at com.sun.proxy.$Proxy135.queryRefundQuartz(Unknown Source) [?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:302) [XXXXX-hessian-1.0.0.jar:?]
        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:217) [XXXXX-hessian-1.0.0.jar:?]
        at org.springframework.remoting.caucho.HessianExporter.doInvoke(HessianExporter.java:223) [spring-web-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.remoting.caucho.HessianExporter.invoke(HessianExporter.java:138) [spring-web-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.remoting.caucho.HessianServiceExporter.handleRequest(HessianServiceExporter.java:66) [spring-web-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.57]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.57]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.57]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.57]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.57]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.57]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.57]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.57]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.57]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.57]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.57]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote.jar:7.0.57]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.57]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar:3.4.5]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar:1.3.1]
        ... 63 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_151]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_151]
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:608) ~[guava-18.0.jar:?]
        at io.shardingsphere.core.merger.dql.DQLMergeEngine.<init>(DQLMergeEngine.java:65) ~[sharding-core-3.1.0.jar:?]
        at io.shardingsphere.core.merger.MergeEngineFactory.newInstance(MergeEngineFactory.java:57) ~[sharding-core-3.1.0.jar:?]
        at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.getResultSet(ShardingPreparedStatement.java:180) ~[sharding-jdbc-core-3.1.0.jar:?]
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:235) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:185) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136) ~[mybatis-3.4.5.jar:3.4.5]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) ~[mybatis-3.4.5.jar:3.4.5]
        at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:351) ~[pagehelper-4.0.1.jar:?]
        at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:329) ~[pagehelper-4.0.1.jar:?]
        at com.github.pagehelper.PageHelper.intercept(PageHelper.java:150) ~[pagehelper-4.0.1.jar:?]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.5.jar:3.4.5]
        at com.sun.proxy.$Proxy152.query(Unknown Source) ~[?:?]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.5.jar:3.4.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar:3.4.5]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar:1.3.1]
        ... 63 more
[2019-04-30 14:40:34.882 ERROR] [http-bio-8888-exec-141] {MicroPayTradeQuartzFacadeImpl.java:719} queryRefundQuartz - 【退款定时】FacadeImpl.queryRefundQuartz.TradeServiceException
XXXXX.TradeServiceException: 查询数据异常
        at XXXXX.MpayRefundDaoImpl.queryTradeOrderNos(MpayRefundDaoImpl.java:287) ~[XXXXX-1.0.jar:?]
        at XXXXX.MicroPayTradeQuartzServiceImpl.queryRefundQuartz(MicroPayTradeQuartzServiceImpl.java:2365) ~[XXXXX-1.0.jar:?]
        at XXXXX.MicroPayTradeQuartzFacadeImpl.queryRefundQuartz(MicroPayTradeQuartzFacadeImpl.java:717) [XXXXX-1.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at XXXXX.RemoteProxyHandler.invoke(RemoteProxyHandler.java:25) [XXXXX-rmi-1.9.jar:?]
        at com.sun.proxy.$Proxy134.queryRefundQuartz(Unknown Source) [?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.remoting.support.RemoteInvocationTraceInterceptor.invoke(RemoteInvocationTraceInterceptor.java:78) [spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at com.sun.proxy.$Proxy135.queryRefundQuartz(Unknown Source) [?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:302) [XXXXX-1.0.0.jar:?]
        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:217) [XXXXX-1.0.0.jar:?]
        at org.springframework.remoting.caucho.HessianExporter.doInvoke(HessianExporter.java:223) [spring-web-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.remoting.caucho.HessianExporter.invoke(HessianExporter.java:138) [spring-web-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.remoting.caucho.HessianServiceExporter.handleRequest(HessianServiceExporter.java:66) [spring-web-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.57]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.57]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.57]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.57]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.57]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.57]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.57]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.57]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.57]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.57]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.57]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.57]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote.jar:7.0.57]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.57]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2019-04-30 14:40:34.883 INFO ] [http-bio-8888-exec-141] {MicroPayTradeQuartzFacadeImpl.java:726} queryRefundQuartz - 【退款定时】结束,totalTime:1011

使用版本3.1.0  如果使用分库字段没有结果集是不报错的，不使用分库字段有结果集不报错，没有结果集报上面的错误

**Comment by KomachiSion** [comment]
duplicate #1718

**Comment by KomachiSion** [comment]
Hi @wzswzjwsj, this problem has solved in new version. please try to use 4.0.0-RC1.
