### ISSUE TITLE
3.0.0不支持distinct

### ISSUE THREAD

**Issue by abcwangjingjing** [apache/incubator-shardingsphere#2382]
我的sql ：select distinct id from 表名
maven引用：
`   <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>3.0.0</version>
        </dependency>`
报错如下：
`Exception in thread "main" io.shardingsphere.core.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'DISTINCT'.
 at io.shardingsphere.core.parsing.lexer.LexerEngine.unsupportedIfEqual(LexerEngine.java:188)
 at io.shardingsphere.core.parsing.parser.clause.DistinctClauseParser.parse(DistinctClauseParser.java:47)
 at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseDistinct(AbstractSelectParser.java:87)
 at io.shardingsphere.core.parsing.parser.dialect.mysql.sql.MySQLSelectParser.parseInternal(MySQLSelectParser.java:48)
 at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseInternal(AbstractSelectParser.java:80)
 at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parse(AbstractSelectParser.java:67)
 at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parse(AbstractSelectParser.java:51)
 at io.shardingsphere.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:60)
 at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:91)
 at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64)
 at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:229)
 at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:108)
 at QueryShardingTest.main(QueryShardingTest.java:33)`

**Comment by abcwangjingjing** [comment]
看文档上写着支持，但实际不支持。

**Comment by terrymanu** [comment]
For English only, other languages will not accept.
