### ISSUE TITLE
Execute the query statement，sharding-proxy An exception occurred in the background ,java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by haj8888888** [apache/incubator-shardingsphere#2396]
Which version of ShardingSphere did you use?
sharding-proxy-4.0.0-RC1

Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-proxy-4.0.0-RC1

Exception description：`java.lang.NullPointerException: null
	at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.item.FunctionSelectItemSegmentExtractor.extractFunctionSelectItemSegment(FunctionSelectItemSegmentExtractor.java:50)
	at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.item.FunctionSelectItemSegmentExtractor.extract(FunctionSelectItemSegmentExtractor.java:46)
	at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.item.SelectItemExtractor.extract(SelectItemExtractor.java:54)
	at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.SelectClauseExtractor.setSelectItemSegment(SelectClauseExtractor.java:61)
	at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.SelectClauseExtractor.extract(SelectClauseExtractor.java:48)
	at org.apache.shardingsphere.core.parse.antlr.extractor.SQLSegmentsExtractorEngine.extract(SQLSegmentsExtractorEngine.java:47)
	at org.apache.shardingsphere.core.parse.antlr.AntlrParsingEngine.parse(AntlrParsingEngine.java:71)
	at org.apache.shardingsphere.core.parse.SQLParsingEngine.parse(SQLParsingEngine.java:61)
	at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:78)
	at org.apache.shardingsphere.core.route.StatementRoutingEngine.route(StatementRoutingEngine.java:56)
	at org.apache.shardingsphere.core.SimpleQueryShardingEngine.route(SimpleQueryShardingEngine.java:60)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:64)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:86)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:57)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:79)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:71)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
Execute SQL：
`select * from t_order t join t_order_item ti on t.order_id = ti.order_id;`

**Comment by codefairy08** [comment]
@haj8888888  Use the default configuration, the result is normal regardless of whether there is data, there is no abnormal log in the background, how to reproduce this issue？

**empty resultset  log**
![image](https://user-images.githubusercontent.com/39583929/58152288-bd0e0380-7c9e-11e9-9f8a-b0ac431e6185.png)
![image](https://user-images.githubusercontent.com/39583929/58152823-1aef1b00-7ca0-11e9-85df-ad30050324f2.png)

**has one resultset  log**
![image](https://user-images.githubusercontent.com/39583929/58152363-f9416400-7c9e-11e9-9ddd-80ecbbdcde76.png)
![image](https://user-images.githubusercontent.com/39583929/58152374-01999f00-7c9f-11e9-820e-599c835289d1.png)

**Comment by terrymanu** [comment]
No response anymore, close now.
