### ISSUE TITLE
Type is required

### ISSUE THREAD

**Issue by huangdaxue** [apache/incubator-shardingsphere#2421]
Exception in thread "main" java.lang.IllegalArgumentException: Type is required.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.apache.shardingsphere.api.config.TypeBasedSPIConfiguration.<init>(TypeBasedSPIConfiguration.java:43)
	at org.apache.shardingsphere.api.config.sharding.KeyGeneratorConfiguration.<init>(KeyGeneratorConfiguration.java:44)
	at org.apache.shardingsphere.core.yaml.swapper.impl.KeyGeneratorConfigurationYamlSwapper.swap(KeyGeneratorConfigurationYamlSwapper.java:42)
	at org.apache.shardingsphere.core.yaml.swapper.impl.TableRuleConfigurationYamlSwapper.swap(TableRuleConfigurationYamlSwapper.java:66)
	at org.apache.shardingsphere.core.yaml.swapper.impl.ShardingRuleConfigurationYamlSwapper.swap(ShardingRuleConfigurationYamlSwapper.java:82)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.getRuleConfiguration(Bootstrap.java:165)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:92)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:71)

sharding_proxy version is 4.0.0-RC1-sharding-proxy  , errors occurs when config master-and-slave,sharding,the config as follows:

shardingRule:  
  masterSlaveRules:
    ms_ds0:
      masterDataSourceName: ds0
      slaveDataSourceNames:
        - ds0_slave0
      loadBalanceAlgorithmType: ROUND_ROBIN
    ms_ds1:
      masterDataSourceName: ds1
      slaveDataSourceNames:
        - ds1_slave0
      loadBalanceAlgorithmType: ROUND_ROBIN
#  defaultDataSourceName: ms_ds0
  tables:
    t_order: 
      actualDataNodes: ms_ds${0..1}.t_order${0..1}
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order${order_id % 2}
      keyGenerator:
#        type: SNOWFLAKE
        column: order_id
    t_order_item:
      actualDataNodes: ms_ds${0..1}.t_order_item${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_item${order_id % 2} 
      keyGenerator:
#        type: SNOWFLAKE
        column: order_id 
  bindingTables:
    - t_order,t_order_item
  broadcastTables:
    - t_config
  
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ms_ds${user_id % 2}
  defaultTableStrategy:
    none:
  defaultKeyGenerator:
    type: SNOWFLAKE

**Comment by terrymanu** [comment]
duplicate with #2397
