### ISSUE TITLE
rewrite index syntax error

### ISSUE THREAD

**Issue by trydofor** [apache/incubator-shardingsphere#2437]
### Which version of ShardingSphere did you use?
4.0.0-RC
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior

Logic SQL: 
```sql
ALTER TABLE `WG_ORDER`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT` (`CREATE_DT` ASC);
```
i want (1) or (2)

=(1)= remove ``` ` ```
``` sql
ADD INDEX IDX_CREATE_DT_WG_ORDER_1 (`CREATE_DT` ASC);
```
=(2)= without ds postfix as the orginal sql
``` sql
ADD INDEX `IDX_CREATE_DT` (`CREATE_DT` ASC);
```
### Actual behavior

``` sql
ADD INDEX `IDX_CREATE_DT`_WG_ORDER_1 (`CREATE_DT` ASC);
```
```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_WG_ORDER_0 (`CREATE_DT` ASC)' at line 3

	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
```

### Example codes for reproduce this issue (such as a github link).

``` kotlin
    @Test
    fun alterTable() {
        val statement = datasource.connection.prepareStatement("""
            ALTER TABLE `WG_ORDER`
            DROP COLUMN `COMMIT_ID`,
            ADD INDEX `IDX_CREATE_DT` (`CREATE_DT` ASC);
        """.trimIndent())

        val result = statement.executeUpdate()
```

``` 
2019-05-23 19:22:42.466  INFO 6868 --- [           main] ShardingSphere-SQL                       : Rule Type: sharding
2019-05-23 19:22:42.466  INFO 6868 --- [           main] ShardingSphere-SQL                       : Logic SQL: ALTER TABLE `WG_ORDER`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT` (`CREATE_DT` ASC);
2019-05-23 19:22:42.467  INFO 6868 --- [           main] ShardingSphere-SQL                       : SQLStatement: AbstractSQLStatement(type=DDL, tables=Tables(tables=[Table(name=WG_ORDER, alias=Optional.absent())]), routeConditions=Conditions(orCondition=OrCondition(andConditions=[])), encryptConditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(tableName=WG_ORDER, quoteCharacter=BACK_QUOTE, schemaNameLength=0), IndexToken(stopIndex=72, tableName=WG_ORDER)], parametersIndex=0, logicSQL=ALTER TABLE `WG_ORDER`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT` (`CREATE_DT` ASC);)
2019-05-23 19:22:42.468  INFO 6868 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: ALTER TABLE `WG_ORDER_0`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT`_WG_ORDER_0 (`CREATE_DT` ASC);
2019-05-23 19:22:42.468  INFO 6868 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds0 ::: ALTER TABLE `WG_ORDER_1`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT`_WG_ORDER_1 (`CREATE_DT` ASC);
2019-05-23 19:22:42.468  INFO 6868 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds1 ::: ALTER TABLE `WG_ORDER_0`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT`_WG_ORDER_0 (`CREATE_DT` ASC);
2019-05-23 19:22:42.469  INFO 6868 --- [           main] ShardingSphere-SQL                       : Actual SQL: ds1 ::: ALTER TABLE `WG_ORDER_1`
DROP COLUMN `COMMIT_ID`,
ADD INDEX `IDX_CREATE_DT`_WG_ORDER_1 (`CREATE_DT` ASC);
```

**Comment by terrymanu** [comment]
duplicate with #2312
