### ISSUE TITLE
mybatis insert text column error, but don't insert the column,it won't be error

### ISSUE THREAD

**Issue by wangenji2015** [apache/incubator-shardingsphere#2515]
```
Cause: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
; SQL []; Invalid argument value: java.io.NotSerializableException; nested exception is java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:108)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy20.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy22.insertSelective(Unknown Source)
	at com.sanxiang.order.dal.repository.OrderRepository.save(OrderRepository.java:20)
	at com.sanxiang.order.services.OrderCoreServiceImpl.createOrder(OrderCoreServiceImpl.java:78)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at brave.dubbo.rpc.TracingFilter.invoke(TracingFilter.java:76)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3825)
	at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3555)
	at com.mysql.jdbc.JDBC42PreparedStatement.setObject(JDBC42PreparedStatement.java:68)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:3401)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setObject(FilterAdapter.java:1320)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:3398)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setObject(FilterAdapter.java:1320)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:3398)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setObject(PreparedStatementProxyImpl.java:460)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setObject(DruidPooledPreparedStatement.java:481)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.invocation.JdbcMethodInvocation.invoke(JdbcMethodInvocation.java:47)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractShardingPreparedStatementAdapter.replaySetParameter(AbstractShardingPreparedStatementAdapter.java:265)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.setParametersForStatements(ShardingPreparedStatement.java:204)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.initPreparedStatementExecutor(ShardingPreparedStatement.java:199)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy30.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy28.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 37 more
Caused by: java.io.NotSerializableException: java.io.StringReader
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3814)
	... 79 more

	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```

**Comment by KomachiSion** [comment]
@wangenji2015, Please provide your full sharding configuration. 
If can provide your example code which can reproduce this problem to github will be better.

**Comment by wangenji2015** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns:p="http://www.springframework.org/schema/p"
	   xmlns:context="http://www.springframework.org/schema/context"
	   xmlns:tx="http://www.springframework.org/schema/tx"
	   xmlns:sharding="http://shardingsphere.apache.org/schema/shardingsphere/sharding"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans
                        http://www.springframework.org/schema/beans/spring-beans.xsd
                        http://shardingsphere.apache.org/schema/shardingsphere/sharding
                        http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding.xsd
                        http://www.springframework.org/schema/context
                        http://www.springframework.org/schema/context/spring-context.xsd
                        http://www.springframework.org/schema/tx
                        http://www.springframework.org/schema/tx/spring-tx.xsd">

	<context:property-placeholder location="classpath:application.properties" />

	<bean id="orderDataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close"
		  p:url="${datasource.user.url}"
		  p:username="${datasource.user.username}"
		  p:password="${datasource.user.password}"
		  p:initialSize="${datasource.user.initialSize}"
		  p:minIdle="${datasource.user.minIdle}"
		  p:maxActive="${datasource.user.maxActive}"
		  p:maxWait="${datasource.user.maxWait}"
		  p:timeBetweenEvictionRunsMillis="${datasource.user.timeBetweenEvictionRunsMillis}"
		  p:minEvictableIdleTimeMillis="${datasource.user.minEvictableIdleTimeMillis}"
		  p:validationQuery="${datasource.user.validationQuery}"
		  p:testWhileIdle="${datasource.user.testWhileIdle}"
		  p:testOnBorrow="${datasource.user.testOnBorrow}"
		  p:testOnReturn="${datasource.user.testOnReturn}"
		  p:poolPreparedStatements="${datasource.user.poolPreparedStatements}"
		  p:maxPoolPreparedStatementPerConnectionSize="${datasource.user.maxPoolPreparedStatementPerConnectionSize}"
		  p:filters="${datasource.user.filters}">
	</bean>

	<sharding:inline-strategy id="orderTableStrategy" sharding-column="order_id" algorithm-expression="me_order_$->{order_id % 2}" />

	<sharding:key-generator id="orderKeyGenerator" type="SNOWFLAKE" column="order_id" />

	<sharding:data-source id="shardingDataSource">
		<sharding:sharding-rule data-source-names="orderDataSource">
			<sharding:table-rules>
				<sharding:table-rule logic-table="me_order" actual-data-nodes="orderDataSource.me_order_$->{0..1}" table-strategy-ref="orderTableStrategy" key-generator-ref="orderKeyGenerator" />
			</sharding:table-rules>
			<sharding:binding-table-rules>
				<sharding:binding-table-rule logic-tables="me_order"/>
			</sharding:binding-table-rules>
		</sharding:sharding-rule>
		<sharding:props>
			<prop key="sql.show">true</prop>
		</sharding:props>
	</sharding:data-source>


	<bean id="orderSqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="dataSource" ref="shardingDataSource" />
		<property name="typeAliasesPackage"
				  value="com.sanxiang.dal.entity" />
		<property name="mapperLocations" value="classpath*:com/sanxiang/order/dal/persistence/mapping/*Mapper.xml" />
		<property name="configLocation" value="classpath:mybatis/setting.xml"/>
	</bean>

	<bean name="orderMapperScannerConfigurer" class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		<property name="basePackage"
				  value="com.sanxiang.order.dal.persistence" />
		<property name="sqlSessionFactoryBeanName" value="orderSqlSessionFactory"/>
	</bean>

	<context:component-scan base-package="com.sanxiang.order.services" />
	<context:component-scan base-package="com.sanxiang.order.dal"/>
	

</beans>

**Comment by wangenji2015** [comment]
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for me_order_0
-- ----------------------------
DROP TABLE IF EXISTS `me_order_0`;
CREATE TABLE `me_order_0` (
  `id` int(11) unsigned NOT NULL COMMENT '订单ID',
  `order_id` bigint(64) NOT NULL,
  `order_no` varchar(64) NOT NULL COMMENT '订单编码',
  `uid` int(11) unsigned NOT NULL COMMENT '用户ID',
  `address_id` int(11) unsigned DEFAULT NULL COMMENT '收货人地址ID',
  `product_count` int(11) NOT NULL DEFAULT '1' COMMENT 'SKU 数量',
  `product_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单总价',
  `logistics_freight` decimal(15,2) DEFAULT '0.00' COMMENT '运费金额',
  `logistics_no` varchar(32) DEFAULT '' COMMENT '物流编号',
  `logistics_company_code` varchar(24) DEFAULT '' COMMENT '物流公司编号',
  `logistics_company` varchar(255) DEFAULT NULL COMMENT '物流公司',
  `pay_channel` tinyint(4) DEFAULT '0' COMMENT '支付渠道:0-微信支付1-支付宝支付2-Apple Pay3-智慧币支付；4：物料钱包；5小程序支付',
  `pay_score` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '抵用积分',
  `trade_no` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方支付流水号',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `deliver_time` timestamp NULL DEFAULT NULL COMMENT '发货时间',
  `remark` varchar(256) NOT NULL DEFAULT '' COMMENT '备注',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0-未付款1-待发货2-待收货3-待评价4-退货申请5-退货申请驳回6-退货中7-已退货8-取消交易9-交易完成10-支付失败',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标记:0-正常1-删除',
  `pay_status` varchar(20) NOT NULL DEFAULT '' COMMENT '支付宝支付状态',
  `goods_type` varchar(32) NOT NULL COMMENT '商品类型:MATERIEL/GOODS/RECHARGE/MEMBER/GIFT/MEMBER_GIFT/APESK',
  `seller_message` varchar(255) DEFAULT NULL COMMENT '卖家留言',
  `is_remind` int(11) NOT NULL DEFAULT '2' COMMENT '是否提醒卖家；1已提醒；2未提醒',
  `remind_time` int(11) DEFAULT '0' COMMENT '提醒时间',
  `report_id` int(11) DEFAULT NULL COMMENT '报告ID',
  `recepit` text,
  PRIMARY KEY (`order_id`) USING BTREE,
  KEY `uid` (`uid`) USING BTREE,
  KEY `address_id` (`address_id`) USING BTREE,
  KEY `uid_2` (`uid`,`status`,`goods_type`) USING BTREE,
  KEY `uid_flag_type` (`uid`,`del_flag`,`goods_type`) USING BTREE,
  KEY `status_create_type` (`status`,`create_time`,`goods_type`) USING BTREE,
  KEY `status_pay_time` (`pay_time`,`status`,`goods_type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';

SET FOREIGN_KEY_CHECKS = 1;

**Comment by wangenji2015** [comment]
the column is recepit

**Comment by wangenji2015** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
BTW, What's your versions of shardingsphere and mybatis?

**Comment by wangenji2015** [comment]
mybatis 3.4.6
sharding 4.0.0-RC1

**Comment by wangenji2015** [comment]
> BTW, What's your versions of shardingsphere and mybatis?

mybatis 3.4.6
sharding 4.0.0-RC1

**Comment by KomachiSion** [comment]
> mybatis 3.4.6
> sharding 4.0.0-RC1

OK, I will try to reproduce your problem.

**Comment by wangenji2015** [comment]
> > mybatis 3.4.6
> > sharding 4.0.0-RC1
> 
> OK, I will try to reproduce your problem.

and mysql-connector-java 5.1.38 
mybatis-spring version 1.3.2
may be you'll use them

**Comment by KomachiSion** [comment]
duplicate with #1567. 
The bug will be fixed in next release.

For now you can use `<result column="recepit" property="recepit" jdbcType="VARCHAR"/>` to solve the problem temporarily.

**Comment by wangenji2015** [comment]
OK，ThanK you
