### ISSUE TITLE
the @Transient column Initiation insert Error on v4.0.0-RC1

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#2584]
I use 4.0.0.RC1
Sharing-JDBC

i use hibernate+sharding-JDBC 
Code like:
```


	@Transient
	@Override
	public Long getId() {
		return this.roleId;
	}

	@Override
	public void setId(Long id) {
		this.roleId = id;		
	}

	@Id
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;		
	}
```

it error when i insert data to db，the Actual SQL not same my Logic SQL.
The actual sql more column “id” witch i mark Transient.
Btw it auto create table is ok,table non-existent column “id”.
This logs is:

```

2019-06-19 14:48:10,198 INFO [ShardingSphere-SQL] Logic SQL: insert into t_role_info (activeTime, createTime, head, headBorderId, level, lockReason, lockTime, name, passagerId, pid, sex, status, type, userId, vipLevel, changeNameTime, changeNameTimes, langStr, roleId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2019-06-19 14:48:10,198 INFO [ShardingSphere-SQL] SQLStatement: InsertStatement(super=DMLStatement(super=AbstractSQLStatement(type=DML, tables=Tables(tables=[Table(name=t_role_info, alias=Optional.absent())]), routeConditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=roleId, tableName=t_role_info), operator=EQUAL, compareOperator=null, positionValueMap={}, positionIndexMap={0=18})])])), encryptConditions=Conditions(orCondition=OrCondition(andConditions=[])), sqlTokens=[TableToken(tableName=t_role_info, quoteCharacter=NONE, schemaNameLength=0), SQLToken(startIndex=24)], parametersIndex=19, logicSQL=insert into t_role_info (activeTime, createTime, head, headBorderId, level, lockReason, lockTime, name, passagerId, pid, sex, status, type, userId, vipLevel, changeNameTime, changeNameTimes, langStr, roleId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)), deleteStatement=false, updateTableAlias={}, updateColumnValues={}, whereStartIndex=0, whereStopIndex=0, whereParameterStartIndex=0, whereParameterEndIndex=0), columnNames=[activeTime, createTime, head, headBorderId, level, lockReason, lockTime, name, passagerId, pid, sex, status, type, userId, vipLevel, changeNameTime, changeNameTimes, langStr, roleId], values=[InsertValue(columnValues=[org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@49d86222, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@246f9503, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@5cbd1493, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@2c5c9433, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@269f2ae8, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@7e0064b5, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@4a2dfe6a, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@2180610, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@5d0fb4d1, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@20575609, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@5ac22c7, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@47c68ce4, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@674f11f1, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@7d32e40f, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@19ec5b74, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@6a3e4501, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@75e1012e, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@1f999101, org.apache.shardingsphere.core.parse.old.parser.expression.SQLPlaceholderExpression@64554e7d])])
2019-06-19 14:48:10,198 INFO [ShardingSphere-SQL] Actual SQL: r_game_sub1 ::: insert into t_role_info0  (activeTime, createTime, head, headBorderId, level, lockReason, lockTime, name, passagerId, pid, sex, status, type, userId, vipLevel, changeNameTime, changeNameTimes, langStr, roleId, id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ::: [2019-06-19 14:48:10.179, 2019-06-19 14:48:10.179, 0, 0, 1, , 0, player9101, wj03, 1000, 0, 1, 1, 6, 0, 0, 0, cn, 464170103659832205, 348115866262437889]
2019-06-19 14:48:10,216 WARN [o.h.util.JDBCExceptionReporter] SQL Error: 1054, SQLState: 42S22
2019-06-19 14:48:10,217 ERROR [o.h.util.JDBCExceptionReporter] Unknown column 'id' in 'field list'
2019-06-19 14:48:10,220 ERROR [o.h.e.d.AbstractFlushingEventListener] Could not synchronize database state with session
org.hibernate.exception.SQLGrammarException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:90)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
```

**Comment by terrymanu** [comment]
Can you provide all stack trace?

**Comment by wangjing112** [comment]
```

Caused by: java.sql.BatchUpdateException: Unknown column 'id' in 'field list'
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2056)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1467)
	at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:223)
	at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:223)
	at org.apache.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor$4.executeSQL(BatchPreparedStatementExecutor.java:168)
	at org.apache.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor$4.executeSQL(BatchPreparedStatementExecutor.java:164)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:69)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:126)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.serialExecute(ShardingExecuteEngine.java:91)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:56)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:128)
	at org.apache.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.executeBatch(BatchPreparedStatementExecutor.java:171)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeBatch(ShardingPreparedStatement.java:231)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
	... 18 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2818)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2157)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2460)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2008)
	... 35 common frames omitted
```

**Comment by wangjing112** [comment]
Logic SQL: insert into t_role_info (activeTime, createTime, head, headBorderId, level, lockReason, lockTime, name, passagerId, pid, sex, status, type, userId, vipLevel, changeNameTime, changeNameTimes, langStr, roleId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

**Comment by wangjing112** [comment]
i found the problem that i yams config this:
```

  defaultKeyGenerator:
    type: SNOWFLAKE
    column: id
```
then ShardingInsertOptimizeEngine::optimize generatedKey add the “id”.

```

    
    @Override
    public OptimizeResult optimize() {
        InsertOptimizeResult insertOptimizeResult = new InsertOptimizeResult(insertStatement.getColumnNames());
        List<AndCondition> andConditions = insertStatement.getShardingConditions().getOrConditions();
        //*****this generatedKey add the defaultKeyGenerator cfg column “id” but not in table column!****
        Optional<GeneratedKey> generatedKey = GeneratedKey.getGenerateKey(shardingRule, parameters, insertStatement);
        boolean isGeneratedValue = generatedKey.isPresent() && generatedKey.get().isGenerated();
        Iterator<Comparable<?>> generatedValues = isGeneratedValue ? generatedKey.get().getGeneratedValues().iterator() : null;
        if (generatedKey.isPresent()) {
            appendGeneratedKeyColumn(generatedKey.get(), insertOptimizeResult);
        }
        appendAssistedQueryColumns(insertOptimizeResult);
        int derivedColumnsCount = getDerivedColumnsCount(isGeneratedValue);
        int parametersCount = 0;
        for (int i = 0; i < andConditions.size(); i++) {
            InsertValue insertValue = insertStatement.getValues().get(i);
            InsertOptimizeResultUnit unit = insertOptimizeResult.addUnit(
                    insertValue.getValues(derivedColumnsCount), insertValue.getParameters(parameters, parametersCount, derivedColumnsCount), insertValue.getParametersCount());
            if (isGeneratedValue) {
                unit.addInsertValue(generatedValues.next(), parameters);
            }
            if (shardingRule.getEncryptRule().getEncryptorEngine().isHasShardingQueryAssistedEncryptor(insertStatement.getTables().getSingleTableName())) {
                fillAssistedQueryUnit(insertOptimizeResult.getColumnNames(), unit);
            }
            parametersCount += insertValue.getParametersCount();
        }
        List<RouteCondition> routeConditions = new ArrayList<>();
        return generatedKey.isPresent()
                ? createOptimizeResult(insertOptimizeResult, routeConditions, generatedKey.get()) : new OptimizeResult(new RouteConditions(routeConditions), insertOptimizeResult);
    }
```

**Comment by wangjing112** [comment]
suggest need check generatedKey mast in table’s column.

**Comment by KomachiSion** [comment]
Hi @wangjing112, If your table does not include `id` column, you shouldn't configure keyGenerate for it.

Your configuration told ShardingSphere you want generate key for column `id`, and ShardingSphere done in your acutalSQL. So it's not problem of ShardingSphere.

**Comment by wangjing112** [comment]
Yes you are right, maybe it’s not problem of ShardingSphere,but batter way is  throw clear exception to tell user what happened.so i suggest check and throw exception.

**Comment by KomachiSion** [comment]
> Yes you are right, maybe it’s not problem of ShardingSphere,but batter way is throw clear exception to tell user what happened.so i suggest check and throw exception.

Thanks, We will discuss and consider this suggest. 
We welcome you can subscribe dev mail list and launch a discussion about this issue.
If you are willing to implement and contribute to this function is best.
