### ISSUE TITLE
NOW() cause Optional.get() cannot be called on an absent value

### ISSUE THREAD

**Issue by fwb7014** [apache/incubator-shardingsphere#2591]
**Version**: 4.0.0-RC1-SNAPSHOT
**Logic Sql**:
update t_bind_card_order         set                                 order_state = ?,                                                     pay_channel_id = ?,                                 pay_template_id = ?,                                                                                             remark = ?,                             updated_at = NOW()          where id = ? and global_no = ?

When delete updated_at = NOW() execute success;
**Error Info**:
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
	... 38 common frames omitted
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:42)
	at org.apache.shardingsphere.core.parse.antlr.filler.sharding.statement.impl.dml.UpdateSetWhereFiller.fill(UpdateSetWhereFiller.java:49)
	at org.apache.shardingsphere.core.parse.antlr.filler.sharding.statement.impl.dml.UpdateSetWhereFiller.fill(UpdateSetWhereFiller.java:39)
	at org.apache.shardingsphere.core.parse.antlr.filler.SQLStatementFillerEngine.fill(SQLStatementFillerEngine.java:82)
	at org.apache.shardingsphere.core.parse.antlr.AntlrParsingEngine.parse(AntlrParsingEngine.java:71)
	at org.apache.shardingsphere.core.parse.SQLParsingEngine.parse(SQLParsingEngine.java:62)
	at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:76)
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64)
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:60)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:64)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:224)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:170)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:45)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:115)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:170)
	... 43 common frames omitted

**Comment by tuohai666** [comment]
1. Please set sql.show: true, and put on the logs with SQLs.
2. Please provide your sharding configuration.
3. Please double check your version. I wonder why you using **4.0.0-RC1-SNAPSHOT**? If you do use **4.0.0-RC1-SNAPSHOT**, please update to **4.0.0-RC2-SNAPSHOT** and have a try.

**Comment by tuohai666** [comment]
Duplicate with https://github.com/apache/incubator-shardingsphere/issues/2278.
