### ISSUE TITLE
rewrites SQL statements with forced Index that do not configure shard rules

### ISSUE THREAD

**Issue by wlstone119** [apache/incubator-shardingsphere#2599]
shardingSphere rewrites SQL statements with forced Index that do not configure sharding rules, and the index name is rewritten to: indexName_tableName

the version is  : 4.0.0-RC1

select count(*)   from bw_borrower_flow FORCE INDEX(k_distribute_time)     WHERE is_delete= 0                            and distribute_time >= ?                            and distribute_time <= ?                                  AND status = ?                AND task_type=?                AND uid_cus=?                            AND company_id = ?          AND abandon_reason_id in    (     ?    ,     ?    )          AND view_law_times < ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Key 'k_distribute_time_bw_borrower_flow' doesn't exist in table 'bw_borrower_flow'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Key 'k_distribute_time_bw_borrower_flow' doesn't exist in table 'bw_borrower_flow'
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91) ~[spring-jdbc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82) ~[spring-jdbc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at com.sun.proxy.$Proxy88.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy93.getSeaFlowCount(Unknown Source) ~[?:?]
	at com.weidai.crm.data.biz.dalService.flow.impl.BorrowerFlowServiceImpl.getSeaFlowCount(BorrowerFlowServiceImpl.java:728) ~[crm-data-service-1.0.0.jar:1.0.0]
	at com.weidai.crm.data.biz.dalService.flow.impl.BorrowerFlowServiceImpl$$FastClassBySpringCGLIB$$a94821ce.invoke(<generated>) ~[crm-data-service-1.0.0.jar:1.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.weidai.crm.data.biz.dalService.flow.impl.BorrowerFlowServiceImpl$$EnhancerBySpringCGLIB$$312e3f99.getSeaFlowCount(<generated>) ~[crm-data-service-1.0.0.jar:1.0.0]
	at com.weidai.crm.data.facade.flow.BorrowerFlowFacadeImpl.getSeaFlowPageList(BorrowerFlowFacadeImpl.java:945) ~[crm-data-service-1.0.0.jar:1.0.0]
	at com.alibaba.dubbo.common.bytecode.Wrapper10.invokeMethod(Wrapper10.java) ~[dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) ~[dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) ~[dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) ~[dubbo-2.5.5.jar:2.5.5]
	at com.weidai.crm.data.filter.FilterHandler.handle(FilterHandler.java:36) [classes/:?]
	at com.weidai.crm.data.filter.ProviderFilter.invoke(ProviderFilter.java:26) [classes/:?]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.weidai.middleware.rpcext.IterationProviderFilter.invoke(IterationProviderFilter.java:29) [middleware-weidai-rpcext.jar:?]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.weidai.cat.plugin.dubbo.CatDubboFilter.invoke(CatDubboFilter.java:88) [wcat-client-1.0.7.jar:?]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.weidai.middleware.log.filter.DubboLogTraceFilter.invoke(DubboLogTraceFilter.java:23) [middleware-log-1.1.2.jar:?]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:61) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:102) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:98) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:81) [dubbo-2.5.5.jar:2.5.5]
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:47) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

**Comment by terrymanu** [comment]
Key 'k_distribute_time_bw_borrower_flow' doesn't exist in table 'bw_borrower_flow'

Just check your database's index

**Comment by wlstone119** [comment]
our index is k_distribute_time, the real reason is SS rewrite the index name to 'k_distribute_time_bw_borrower_flow' ， but table bw_borrower_flow no shardingRule。

![图片](https://user-images.githubusercontent.com/16698223/60148817-22f12c00-9805-11e9-8e28-3290656f874d.png)

**Comment by wlstone119** [comment]
our index is k_distribute_time, the real reason is SS rewrite the index name to 'k_distribute_time_bw_borrower_flow' ， but table bw_borrower_flow no shardingRule。

![图片](https://user-images.githubusercontent.com/16698223/60148857-44eaae80-9805-11e9-91ea-f1f220f7cac2.png)

**Comment by wlstone119** [comment]
our index is k_distribute_time, the real reason is SS rewrite the index name to 'k_distribute_time_bw_borrower_flow' ， but table bw_borrower_flow no shardingRule。
