### ISSUE TITLE
sharding-proxy是否可以同sharding-jdbc公用同一个zk上的配置？

### ISSUE THREAD

**Issue by core1942** [apache/incubator-shardingsphere#2671]
sharding-proxy是否可以同sharding-jdbc公用同一个zk上的配置？
如果可以的话是否只需要配置sharding-proxy的server.yaml中的orchestration配置，其他配置文件直接置空就行了？但目前我这样做会抛NullPointerException。

`Exception in thread "main" java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:64)
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427)
        at org.apache.shardingsphere.core.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:87)
        at org.apache.shardingsphere.orchestration.internal.registry.config.service.ConfigurationService.loadAuthentication(ConfigurationService.java:214)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:102)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:75)`

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
