### ISSUE TITLE
error with SQL use MyBaits PageHelper

### ISSUE THREAD

**Issue by xiaolong7713** [apache/incubator-shardingsphere#2721]
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalStateException: Must have sharding column with subquery.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 34 common frames omitted
Caused by: java.lang.IllegalStateException: Must have sharding column with subquery.

but another SQL is normal, like this:

2019-07-17 23:56:00.825 |-DEBUG [taskExecutor-3]  ==>  Preparing: SELECT count(0) FROM ob_task_pre_order t, ob_task_config c WHERE t.hotel_code = c.hotel_code AND c.payid_enable = 1 AND t.payment_status = 'Y' AND date_sub(t.last_retain_time, INTERVAL 30 MINUTE) < SYSDATE() AND t.task_status IN (0, 2) AND t.order_status = 1 AND t.task_result IN (1, 2) AND t.last_retain_time LIKE ? AND t.out_cnt = 1 AND t.rcp_type = 'RcpType01' 

this is wrong:
==>Preparing: select count(0) from (SELECT t.* FROM ob_task_rec_order t, ob_task_config c WHERE t.hotel_code = c.hotel_code AND c.check_out_confirm_enable = 1 AND date_sub(t.last_check_out_time,INTERVAL c.check_out_confirm_time MINUTE) < SYSDATE() AND t.last_check_out_time > SYSDATE() AND t.task_status = 0 AND t.order_status = 5 AND t.task_result = 0 AND t.last_check_out_time like ? AND t.out_cnt = 0 AND t.rcp_type = 'RcpType01' order by t.create_time,t.task_id) tmp_count 

Just different than 'tmp_count '

sharding-jdcb version:4.0.0-RC1
mybatis:version: 3.5.0

**Comment by terrymanu** [comment]
The exception said: Must have sharding column with subquery

**Comment by adonis2014** [comment]
@xiaolong7713 Have you solved it? I have the same problem
