### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by gameboyLV** [apache/incubator-shardingsphere#2811]
### Which version of ShardingSphere did you use?

4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-Proxy

### Actual behavior

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/mysql/cj/jdbc/Driver : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.recognizer.impl.MySQLRecognizer.getDriverClassName(MySQLRecognizer.java:40)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.recognizer.JDBCDriverURLRecognizerEngine.load(JDBCDriverURLRecognizerEngine.java:48)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.recognizer.JDBCDriverURLRecognizerEngine.<clinit>(JDBCDriverURLRecognizerEngine.java:42)
        at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:92)
        at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:79)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:92)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:71)

### Reason analyze (If you can)

Sharding-Proxy currently not compatible with mysql-connector-java-8.0.17.tar.gz

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

copy mysql-connector-java-8.0.17.tar.gz to lib folder
start sharding-proxy

**Comment by terrymanu** [comment]
Please search `Unsupported major.minor version 52.0` to find solution.

**Comment by gameboyLV** [comment]
https://hub.docker.com/r/shardingsphere/sharding-proxy
 solution is not suitable for the official docker image

**Comment by gameboyLV** [comment]
`docker pull shardingsphere/sharding-proxy

docker run -d --name mysql-cluster -v /opt/sharding-proxy/conf:/opt/sharding-proxy/conf -e PORT=3308 -p 3308:3308 shardingsphere/sharding-proxy:latest

docker cp /opt/sharding-proxy/lib/mysql-connector-java-8.0.17.jar mysql-cluster:/opt/sharding-proxy/lib/mysql-connector-java-8.0.17.jar

docker cp /opt/sharding-proxy/lib/jdk-8u221-linux-x64.tar.gz mysql-cluster:/usr/lib/jvm/jdk-8u221-linux-x64.tar.gz

docker exec -it mysql-cluster bash

cd /usr/lib/jvm/ && tar -zxvf jdk-8u221-linux-x64.tar.gz

update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.8.0_221/bin/java 300

update-alternatives --config java

exit

docker restart mysql-cluster
`
