### ISSUE TITLE
openjdk11 not work

### ISSUE THREAD

**Issue by liujiesmart** [apache/incubator-shardingsphere#2841]
openjdk11 :
`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.shardingsphere.core.parse.rule.registry.ParseRuleRegistry
        at org.apache.shardingsphere.core.parse.entry.MasterSlaveSQLParseEntry.getSQLParseEngine(MasterSlaveSQLParseEntry.java:41)
        at org.apache.shardingsphere.core.parse.entry.SQLParseEntry.parse(SQLParseEntry.java:48)
        at org.apache.shardingsphere.core.route.router.masterslave.MasterSlaveRouter.route(MasterSlaveRouter.java:56)
`
jdk8 is normal

version 4.0.0-RC2

**Comment by terrymanu** [comment]
Can you provide all stack trace of exception?

**Comment by terrymanu** [comment]
Will close soon if no response any more.
