### ISSUE TITLE
Access Sharing-Proxy 4.0.0RC2 with navicat return null point exception for lack of scheam

### ISSUE THREAD

**Issue by liujuntao** [apache/incubator-shardingsphere#2860]
I used the offical example of proxy, when i use navicat to access the proxy, it thrown the exception below, so the test cannot continue. since i don't very familer with the code ,so i just trace to that, datasource name of BackenConnection is null lead to this issue。
Below is the excepiton， and the configure also be attached.
And the proxy is comminucate with QUERY_COM ,and the query sql is "SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA"

ava.lang.NullPointerException: null
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:189)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:172)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:141)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
 at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
 at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
 at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:78)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:91)
 at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:77)
 at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
 at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:72)
 at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
 at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

[config-files.zip](https://github.com/apache/incubator-shardingsphere/files/3495706/config-files.zip)

**Comment by liujuntao** [comment]
when i add the "defaultDataSourceName: ds_0" to "config-sharding.yaml" , i use navicat can see the database information ,but i got the error below .

[INFO ] 18:16:58.989 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mysql' ORDER BY TABLE_SCHEMA, TABLE_NAME
[ERROR] 18:16:59.415 [ShardingSphere-Command-0] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.core.parse.exception.SQLParsingException: Cannot support multiple schemas in one SQL
	at org.apache.shardingsphere.core.parse.filler.impl.TableFiller.fill(TableFiller.java:42)
	at org.apache.shardingsphere.core.parse.filler.impl.TableFiller.fill(TableFiller.java:35)
	at org.apache.shardingsphere.core.parse.filler.SQLStatementFillerEngine.fill(SQLStatementFillerEngine.java:65)
	at org.apache.shardingsphere.core.parse.SQLParseEngine.parse(SQLParseEngine.java:64)
	at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:66)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:64)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:85)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tuohai666** [comment]
> I used the offical example of proxy, when i use navicat to access the proxy, it thrown the exception below, so the test cannot continue. since i don't very familer with the code ,so i just trace to that, datasource name of BackenConnection is null lead to this issue。
> Below is the excepiton， and the configure also be attached.
> And the proxy is comminucate with QUERY_COM ,and the query sql is "SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA"
> 
> ava.lang.NullPointerException: null
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:189)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:172)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:141)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
> at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
> at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
> at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:78)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:91)
> at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:77)
> at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
> at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:72)
> at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
> at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 
> [config-files.zip](https://github.com/apache/incubator-shardingsphere/files/3495706/config-files.zip)

Duplicate with #2617

**Comment by tuohai666** [comment]
> when i add the "defaultDataSourceName: ds_0" to "config-sharding.yaml" , i use navicat can see the database information ,but i got the error below .
> 
> [INFO ] 18:16:58.989 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mysql' ORDER BY TABLE_SCHEMA, TABLE_NAME
> [ERROR] 18:16:59.415 [ShardingSphere-Command-0] o.a.s.s.f.c.CommandExecutorTask - Exception occur:
> org.apache.shardingsphere.core.parse.exception.SQLParsingException: Cannot support multiple schemas in one SQL
> at org.apache.shardingsphere.core.parse.filler.impl.TableFiller.fill(TableFiller.java:42)
> at org.apache.shardingsphere.core.parse.filler.impl.TableFiller.fill(TableFiller.java:35)
> at org.apache.shardingsphere.core.parse.filler.SQLStatementFillerEngine.fill(SQLStatementFillerEngine.java:65)
> at org.apache.shardingsphere.core.parse.SQLParseEngine.parse(SQLParseEngine.java:64)
> at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:66)
> at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.(MySQLComQueryPacketExecutor.java:64)
> at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
> at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
> at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:85)
> at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)

I can't reproduce this error. Please try 4.0.0-RC2-SNAPSHOT in dev branch.

**Comment by liujuntao** [comment]
re-Command-13] ShardingSphere-SQL - SQLStatement: SelectStatement(super=DMLStatement(super=AbstractSQLStatement(sqlSegments=[TableSegment(startIndex=63, stopIndex=88, name=COLUMNS, quoteCharacter=NONE, owner=Optional.of(org.apache.shardingsphere.core.parse.sql.segment.common.SchemaSegment@a80183), alias=Optional.absent()), ColumnSegment(startIndex=7, stopIndex=18, name=TABLE_SCHEMA, quoteCharacter=NONE, owner=Optional.absent()), ColumnSegment(startIndex=21, stopIndex=30, name=TABLE_NAME, quoteCharacter=NONE, owner=Optional.absent()), ColumnSegment(startIndex=33, stopIndex=43, name=COLUMN_NAME, quoteCharacter=NONE, owner=Optional.absent()), ColumnSegment(startIndex=46, stopIndex=56, name=COLUMN_TYPE, quoteCharacter=NONE, owner=Optional.absent()), ColumnSegment(startIndex=96, stopIndex=107, name=TABLE_SCHEMA, quoteCharacter=NONE, owner=Optional.absent()), ColumnSegment(startIndex=126, stopIndex=137, name=TABLE_SCHEMA, quoteCharacter=NONE, owner=Optional.absent()), ColumnSegment(startIndex=140, stopIndex=149, name=TABLE_NAME, quoteCharacter=NONE, owner=Optional.absent()), org.apache.shardingsphere.core.parse.sql.segment.dml.item.SelectItemsSegment@771c829, org.apache.shardingsphere.core.parse.sql.segment.dml.predicate.WhereSegment@30ceb677, org.apache.shardingsphere.core.parse.sql.segment.dml.order.OrderBySegment@3b14a8a6], tables=Tables(tables=[Table(name=COLUMNS, alias=Optional.absent())]), logicSQL=SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'db1' ORDER BY TABLE_SCHEMA, TABLE_NAME, parametersCount=0)), selectItems=org.apache.shardingsphere.core.parse.sql.segment.dml.item.SelectItemsSegment@771c829, where=Optional.of(org.apache.shardingsphere.core.parse.sql.segment.dml.predicate.WhereSegment@30ceb677), groupBy=Optional.absent(), orderBy=Optional.of(org.apache.shardingsphere.core.parse.sql.segment.dml.order.OrderBySegment@3b14a8a6))
[INFO ] 16:09:53.360 [ShardingSphere-Command-13] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'db1' ORDER BY TABLE_SCHEMA, TABLE_NAME
[ERROR] 16:09:53.411 [ShardingSphere-Command-14] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.core.parse.exception.SQLParsingException: Cannot support multiple schemas in one SQL
	at org.apache.shardingsphere.core.parse.filler.impl.TableFiller.fill(TableFiller.java:42)
	at org.apache.shardingsphere.core.parse.filler.impl.TableFiller.fill(TableFiller.java:35)
	at org.apache.shardingsphere.core.parse.filler.SQLStatementFillerEngine.fill(SQLStatementFillerEngine.java:65)
	at org.apache.shardingsphere.core.parse.SQLParseEngine.parse(SQLParseEngine.java:64)
	at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:66)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:64)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:85)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tuohai666** [comment]
Can you try 4.0.0-RC2-SNAPSHOT in dev branch?

**Comment by liujuntao** [comment]
give me sometime , i'm busying with other work, i'll try it with RC2 later.

**Comment by terrymanu** [comment]
Closed for no response anymore.

**Comment by StHsiang** [comment]
When I connectted to a sharding proxy 4.0.0-RC2 server with navicat 10.1.7,I can get the schema the one I configured in the configuration file config-sharding.yml and open the schema successfully. Howerer, when I connected the sharding proxy with navicat 12.1.7, I cannot get the schema and when I tried to open anyone of  presented schemas, I got the error "1049 - Unknown database 'xxxx'".
