### ISSUE TITLE
shardingsphere-incubating-4.0.0-RC1-sharding-proxy Demo Not Run

### ISSUE THREAD

**Issue by xriqyu** [apache/incubator-shardingsphere#2867]
schemaName: sharding_db

dataSources:
 ds_0:
   url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
 ds_1:
   url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50

The exception detail is no writeable property 'cacheServerConfiguration' in class 'com.mysql.cj.jdbc.MysqlXADataSource'.
Exception in thread "main" com.atomikos.beans.PropertyException: no writeable property 'cacheServerConfiguration' in class 'com.mysql.cj.jdbc.MysqlXADataSource'
	at com.atomikos.beans.PropertyUtils.getSetter(PropertyUtils.java:334)
	at com.atomikos.beans.PropertyUtils.setDirectProperty(PropertyUtils.java:185)
	at com.atomikos.beans.PropertyUtils.setProperty(PropertyUtils.java:94)
	at com.atomikos.beans.PropertyUtils.setProperties(PropertyUtils.java:171)
	at org.apache.shardingsphere.transaction.xa.jta.datasource.XADataSourceFactory.build(XADataSourceFactory.java:79)
	at org.apache.shardingsphere.transaction.xa.jta.datasource.SingleXADataSource.<init>(SingleXADataSource.java:58)
	at org.apache.shardingsphere.transaction.xa.XAShardingTransactionManager.init(XAShardingTransactionManager.java:65)
	at org.apache.shardingsphere.transaction.ShardingTransactionManagerEngine.init(ShardingTransactionManagerEngine.java:69)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createDataSourceMap(JDBCBackendDataSource.java:74)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.<init>(JDBCBackendDataSource.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchema.<init>(LogicSchema.java:61)
	at org.apache.shardingsphere.shardingproxy.backend.schema.ShardingSchema.<init>(ShardingSchema.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.createLogicSchema(LogicSchemas.java:113)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.initSchemas(LogicSchemas.java:103)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:79)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:92)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:71)

**Comment by terrymanu** [comment]
Can you explain why close this issue without any reason to update?

**Comment by xriqyu** [comment]
change mysql-connector-java  to version: 5.1.48.fix it
