### ISSUE TITLE
Unsupported SQL of `FLUSH TABLES`- 4.0.0RC2

### ISSUE THREAD

**Issue by liujuntao** [apache/incubator-shardingsphere#2870]
Unsupported SQL of `FLUSH TABLES`

[INFO ] 13:46:43.206 [ShardingSphere-Command-11] ShardingSphere-SQL - SQLStatement: SetStatement(super=DALStatement(super=AbstractSQLStatement(sqlSegments=[], tables=Tables(tables=[]), logicSQL=SET NAMES utf8mb4, parametersCount=0)))
[INFO ] 13:46:43.206 [ShardingSphere-Command-11] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET NAMES utf8mb4
[INFO ] 13:46:44.304 [ShardingSphere-Command-12] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 13:46:44.304 [ShardingSphere-Command-12] ShardingSphere-SQL - Logic SQL: SET NAMES utf8mb4
[INFO ] 13:46:44.304 [ShardingSphere-Command-12] ShardingSphere-SQL - SQLStatement: SetStatement(super=DALStatement(super=AbstractSQLStatement(sqlSegments=[], tables=Tables(tables=[]), logicSQL=SET NAMES utf8mb4, parametersCount=0)))
[INFO ] 13:46:44.304 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET NAMES utf8mb4
line 1:0 mismatched input 'FLUSH' expecting {SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE, GRANT, REVOKE, SET, WITH, DESC, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, CALL, USE, DESCRIBE, SHOW, REPLACE, START, RENAME}
[ERROR] 13:46:44.372 [ShardingSphere-Command-12] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.core.parse.exception.SQLParsingException: Unsupported SQL of `FLUSH TABLES`
	at org.apache.shardingsphere.core.parse.parser.SQLParserEngine.parse(SQLParserEngine.java:57)
	at org.apache.shardingsphere.core.parse.SQLParseEngine.parse(SQLParseEngine.java:61)
	at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:66)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:64)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:85)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by terrymanu** [comment]
No plan to do
