### ISSUE TITLE
proxy 4.0.0-RC1 update error

### ISSUE THREAD

**Issue by xriqyu** [apache/incubator-shardingsphere#2898]
更新的字段值为null ，就异常了
等否直接提供一个proxy 4.0.0-RC2 的下载地址，真的不是太好构建。

ERROR] 19:02:08.738 [ShardingSphere-Command-15] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:756)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4411)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getObject(HikariProxyResultSet.java)
	at org.apache.shardingsphere.core.execute.sql.execute.result.StreamQueryResult.getValue(StreamQueryResult.java:73)
	at org.apache.shardingsphere.core.merge.dql.common.StreamMergedResult.getValue(StreamMergedResult.java:49)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.getQueryData(JDBCDatabaseCommunicationEngine.java:158)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.getQueryData(QueryBackendHandler.java:64)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.getQueryData(MySQLComQueryPacketExecutor.java:114)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.getQueryData(MySQLComQueryPacketExecutor.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.writeQueryData(MySQLCommandExecuteEngine.java:83)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:94)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
