### ISSUE TITLE
both local and official image of Sharding-Proxy run with errors

### ISSUE THREAD

**Issue by Moriadry** [apache/incubator-shardingsphere#2909]
## Bug Report

**For English only**, other languages will not accept.

According to https://shardingsphere.apache.org/document/current/cn/manual/sharding-proxy/docker/ , but It failed if I run `mvn clean package docker:build`. The result is as below:

```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.14:build (default-cli) on project sharding-proxy: Exception caught: Must specify baseImage if dockerDirectory is null -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

if I use official docker image `shardingsphere/sharding-proxy` directly, It turns out another error message:

```
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.initSchemas(LogicSchemas.java:103)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:79)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:92)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:71)
Caused by: org.apache.shardingsphere.core.exception.ShardingException: Cannot load JDBC driver class `com.mysql.jdbc.Driver`, make sure it in Sharding-Proxy's classpath.
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.validateDriverClassName(JDBCRawBackendDataSourceFactory.java:82)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.build(JDBCRawBackendDataSourceFactory.java:54)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createDataSourceMap(JDBCBackendDataSource.java:66)
	... 9 more
```

Could you help me solve this, by update the document, or give me a correct way to run proxy by docker.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2 and 4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Actual behavior
run failed

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
follow the steps of document for docker.

### Example codes for reproduce this issue (such as a github link).
NONE.

**Comment by terrymanu** [comment]
Please add mysql driver by yourself
