### ISSUE TITLE
Can the sharding-proxy config a user with read-only privilege ?

### ISSUE THREAD

**Issue by Myshiner** [apache/incubator-shardingsphere#2913]
Version: sharding-proxy 4.0.0-RC1
Can i config a read-only user in the authentication center ? just like following.
authentication:
users:
root:
password: root
reader: /* read only user */
password: reader
authorizedSchemas: sharding_db

**Comment by Myshiner** [comment]
My configure are following:
-----------------------------
orchestration:
  name: orchestration_ds
  overwrite: true
  registry:
    type: zookeeper
    serverLists: 10.60.0.183:2181
    namespace: orchestration

authentication:
  users:
    root:
      password: root
    reader:
      password: 1A2s~dQwe
      authorizedSchemas: neworiental_v3,neworiental_trail
---------------------------------------------
And when i start the process, i get errors as below.
Exception in thread "main" Cannot create property=authentication for JavaBean=org.apache.shardingsphere.shardingproxy.config.yaml.YamlProxyServerConfiguration@d1cfd52
 in 'reader', line 7, column 1:
    orchestration:
    ^
Cannot create property=users for JavaBean=org.apache.shardingsphere.core.yaml.config.common.YamlAuthentication@4c8c4559
 in 'reader', line 16, column 3:
      users:
      ^
Unable to find property 'users' on class: org.apache.shardingsphere.core.yaml.config.common.YamlAuthentication
 in 'reader', line 17, column 5:
        root:
        ^

 in 'reader', line 16, column 3:
      users:
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
        at org.apache.shardingsphere.core.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:59)
        at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.loadServerConfiguration(ShardingConfigurationLoader.java:77)
        at org.apache.shardingsphere.shardingproxy.config.ShardingConfigurationLoader.load(ShardingConfigurationLoader.java:58)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:68)
Caused by: Cannot create property=users for JavaBean=org.apache.shardingsphere.core.yaml.config.common.YamlAuthentication@4c8c4559
 in 'reader', line 16, column 3:
      users:
      ^
Unable to find property 'users' on class: org.apache.shardingsphere.core.yaml.config.common.YamlAuthentication
 in 'reader', line 17, column 5:
        root:

**Comment by terrymanu** [comment]
No, hope some committer dev this feature

**Comment by Myshiner** [comment]
thx，but in v4.0.0-RC2, when i config multi-users it throw errors. Please refer to the errors from the previous comments above.

**Comment by terrymanu** [comment]
Why close this issue? Do you find solution?

**Comment by sunbufu** [comment]
Duplicate with https://github.com/apache/incubator-shardingsphere/issues/2925.
