### ISSUE TITLE
sharding-proxy could not support hint strategy

### ISSUE THREAD

**Issue by M-make** [apache/incubator-shardingsphere#2957]
### tool
Sharding-proxy

### error
```log
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:189)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:172)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:141)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:78)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:95)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:81)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

### config-sharding.yaml
```xml
schemaName: sharding_db

dataSources:
  ds0:
    url: jdbc:mysql://132.232.39.227:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 88888888
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds1:
    url: jdbc:mysql://132.232.39.227:3307/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 88888888
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  defaultDatabaseStrategy:
    hint:
      algorithmClassName: org.DbHintShardingAlgorithm
  defaultTableStrategy:
    hint:
      algorithmClassName: org.TableHintShardingAlgorithm
```

### DbHintShardingAlgorithm
```java
public class DbHintShardingAlgorithm implements HintShardingAlgorithm<Integer> {
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<Integer> shardingValue) {
        Collection<String> tables = new ArrayList<>();
        for (String availableTargetName : availableTargetNames) {
            tables.add(availableTargetName.split(".")[0]);
        }
        return tables;
    }
}
```

### TableHintShardingAlgorithm
```java
public class TableHintShardingAlgorithm implements HintShardingAlgorithm<Integer> {
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<Integer> shardingValue) {
        Collection<String> tables = new ArrayList<>();
        for (String availableTargetName : availableTargetNames) {
            tables.add(availableTargetName.split(".")[1]);
        }
        return tables;
    }
}
```

### client
```java
public class Test {
    public static void main(String[] args) {
        MysqlDataSource mysqlDataSource = new MysqlDataSource();
        mysqlDataSource.setUser("sharding");
        mysqlDataSource.setPassword("sharding");
        mysqlDataSource.setUrl("jdbc:mysql://localhost:3307/sharding_db?serverTimezone=UTC&useSSL=false");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(mysqlDataSource);
        jdbcTemplate.query("select * from ds0.test_table1",new ColumnMapRowMapper());

    }
}
```

**Comment by M-make** [comment]
the version is 4.0.0.R2

**Comment by cherrylzhao** [comment]
what is your `server.yaml` configuration?

**Comment by M-make** [comment]
```yaml
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 
      authorizedSchemas: sharding_db
```

**Comment by M-make** [comment]
> what is your `server.yaml` configuration?

```yml
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 
      authorizedSchemas: sharding_db
```

**Comment by cherrylzhao** [comment]
so props content is empty? like this
```
props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  query.with.cipher.column: true
  sql.show: false
```

**Comment by cherrylzhao** [comment]
I suggest you verify the feature using proxy command line at first

**Comment by M-make** [comment]
> I suggest you verify the feature using proxy command line at first

I added these configurations, but still NPE

```log
[ERROR] 09:32:13.915 [ShardingSphere-Command-3] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:189)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:172)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:141)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
```

**Comment by M-make** [comment]
this is my server.yaml

```yml
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 
      authorizedSchemas: sharding_db

props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  query.with.cipher.column: true
  sql.show: false
```

**Comment by M-make** [comment]
I observed the log, why is it always `XAResource`

#### stdout.log
```log
[INFO ] 09:20:44.657 [Atomikos:1] c.a.d.xa.XATransactionalResource - resource-2-ds1: refreshed XAResource
Listening for transport dt_socket at address: 5005
09:31:33,908 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:31:33,908 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:31:33,908 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/huqingfeng/Downloads/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin/conf/logback.xml]
09:31:33,909 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
09:31:33,909 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/huqingfeng/Downloads/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin/conf/logback.xml]
09:31:33,909 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/huqingfeng/Downloads/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin/lib/sharding-proxy-bootstrap-4.0.0-RC2.jar!/logback.xml]
09:31:33,909 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/huqingfeng/Downloads/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin/lib/sharding-proxy-distribution-4.0.0-RC2.jar!/logback.xml]
09:31:34,007 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:31:34,010 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:31:34,017 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [console]
09:31:34,023 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:31:34,088 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.shardingsphere] to INFO
09:31:34,088 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.shardingsphere] to false
09:31:34,088 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[org.apache.shardingsphere]
09:31:34,090 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
09:31:34,090 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[ROOT]
09:31:34,090 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:31:34,091 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6d763516 - Registering current configuration as safe fallback point

[INFO ] 09:31:34.113 [main] o.a.s.core.util.ConfigurationLogger - ShardingRuleConfiguration
defaultDatabaseStrategy:
  hint:
    algorithmClassName: org.DbHintShardingAlgorithm
defaultTableStrategy:
  hint:
    algorithmClassName: org.TableHintShardingAlgorithm

[INFO ] 09:31:34.166 [main] o.a.s.core.util.ConfigurationLogger - Authentication
users:
  sharding:
    authorizedSchemas: sharding_db
    password: sharding
  root:
    authorizedSchemas: ''
    password: root

[INFO ] 09:31:34.167 [main] o.a.s.core.util.ConfigurationLogger - Properties
proxy.frontend.flush.threshold: 128
executor.size: 16
proxy.transaction.type: LOCAL
max.connections.size.per.query: 1
sql.show: false
acceptor.size: 16
proxy.opentracing.enabled: false
query.with.cipher.column: true

[INFO ] 09:31:34.385 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[INFO ] 09:31:35.129 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[INFO ] 09:31:35.130 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
[INFO ] 09:31:35.510 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
[INFO ] 09:31:35.574 [main] c.a.icatch.provider.imp.AssemblerImp - Loaded jar:file:/Users/huqingfeng/Downloads/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin/lib/transactions-4.0.6.jar!/transactions-defaults.properties
[INFO ] 09:31:35.575 [main] c.a.icatch.provider.imp.AssemblerImp - Loaded jar:file:/Users/huqingfeng/Downloads/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin/lib/sharding-transaction-xa-atomikos-manager-4.0.0-RC2.jar!/jta.properties
[WARN ] 09:31:40.592 [main] c.a.icatch.provider.imp.AssemblerImp - Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
[INFO ] 09:31:40.605 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_max_wait_time_on_shutdown = 9223372036854775807
[INFO ] 09:31:40.605 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.allow_subtransactions = true
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.recovery_delay = 300000
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.automatic_resource_registration = false
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_max_retries = 5
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.client_demarcation = false
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.threaded_2pc = false
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.serial_jta_transactions = false
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.log_base_dir = ./logs
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.rmi_export_class = none
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.max_actives = 10000
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.checkpoint_interval = 50000
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.enable_logging = true
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.log_base_name = xa_tx
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.max_timeout = 300000
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.trust_client_tm = false
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: java.naming.factory.initial = com.sun.jndi.rmi.registry.RegistryContextFactory
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.tm_unique_name = 10.2.104.84.tm
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.forget_orphaned_log_entries_delay = 86400000
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_retry_interval = 10000
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: java.naming.provider.url = rmi://localhost:1099
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.force_shutdown_on_vm_exit = false
[INFO ] 09:31:40.606 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_jta_timeout = 300000
[INFO ] 09:31:40.608 [main] c.a.icatch.provider.imp.AssemblerImp - Using default (local) logging and recovery...
[INFO ] 09:31:40.914 [main] c.a.d.xa.XATransactionalResource - resource-1-ds0: refreshed XAResource
[INFO ] 09:31:41.231 [main] c.a.d.xa.XATransactionalResource - resource-2-ds1: refreshed XAResource
[INFO ] 09:31:46.575 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x6aece2bb] REGISTERED
[INFO ] 09:31:46.577 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x6aece2bb] BIND: 0.0.0.0/0.0.0.0:3307
[INFO ] 09:31:46.581 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x6aece2bb, L:/0.0.0.0:3307] ACTIVE
[INFO ] 09:32:12.002 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x6aece2bb, L:/0.0.0.0:3307] READ: [id: 0xdc28bc02, L:/127.0.0.1:3307 - R:/127.0.0.1:49763]
[INFO ] 09:32:12.006 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x6aece2bb, L:/0.0.0.0:3307] READ COMPLETE
```

**Comment by M-make** [comment]
In the 150 lines of code where the error occurred, I found that there is no LOCAL key in the `shardingTransactionManagerEngine`. it's this ok?

![image](https://user-images.githubusercontent.com/35563513/64085551-07a31f80-cd66-11e9-8131-610f688935db.png)

**Comment by cherrylzhao** [comment]
this is right, LOCAL will be not registered in ShardingTransacitonMananger. I doubt about why the type is XA, have you tested in raw sql command line without JDBC driver?

**Comment by cherrylzhao** [comment]
and the proxy is downloaded from our official site? [4.0.0-RC2](https://www.apache.org/dyn/closer.cgi?path=incubator/shardingsphere/4.0.0-RC2/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz)

**Comment by cherrylzhao** [comment]
``` java
// transactionType here is LOCAL?
private Connection createConnection(final TransactionType transactionType, final String dataSourceName, final DataSource dataSource) throws SQLException {
        ShardingTransactionManager shardingTransactionManager = shardingTransactionManagerEngine.getTransactionManager(transactionType);

// isInShardingTransaction(shardingTransactionMananger) return true or false? it should be false, then execute dataSource.getConnection()
// so the problem should be dataSource is NPE, and your table name in SQL should not start with schema, try to use a logic sql like this `select * from test_table`

        return isInShardingTransaction(shardingTransactionManager) ? shardingTransactionManager.getConnection(dataSourceName) : dataSource.getConnection();
    }
```

**Comment by cherrylzhao** [comment]
I have analyzed this problem, your SQL is wrong, it should be a logic SQL, please pay attention to it.

**Comment by M-make** [comment]
> I have analyzed this problem, your SQL is wrong, it should be a logic SQL, please pay attention to it.

change `select * from ds0.test_table1 ` into `select * from test_table1 ` ?

emmm...   it's still `NPE`

#### log
```log
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:189)
```

**Comment by M-make** [comment]
The sql statement never enters my custom `hint`

**Comment by M-make** [comment]
> and the proxy is downloaded from our official site? [4.0.0-RC2](https://www.apache.org/dyn/closer.cgi?path=incubator/shardingsphere/4.0.0-RC2/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz)

Yes , i'm downloaded from http://mirrors.tuna.tsinghua.edu.cn/apache/incubator/shardingsphere/4.0.0-RC2/apache-shardingsphere-incubating-4.0.0-RC2-sharding-proxy-bin.tar.gz

**Comment by cherrylzhao** [comment]
and hint strategy should have some problems in proxy, it should be only supported on XA transaction, see #2914

**Comment by cherrylzhao** [comment]
hint is based on thread local, but proxy could not ensure this except within a XA transaction type.

**Comment by cherrylzhao** [comment]
you can try to  config like this:
```
props:
  proxy.transaction.type: XA
```

**Comment by M-make** [comment]
> you can try to config like this:
> 
> ```
> props:
>   proxy.transaction.type: XA
> ```


The same error.

**Comment by cherrylzhao** [comment]
ShardingRule configuration also have problems, you have some misunderstand about hint it should be like this, please see our hint-example [here](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/other-feature-example/hint-example)

```
shardingRule:
  tables:
    test_table:
      actualDataNodes: ds${0..1}.test_table${0..1}
  defaultDatabaseStrategy:
    hint:
      algorithmClassName: org.DbHintShardingAlgorithm
  defaultTableStrategy:
    hint:
      algorithmClassName: org.TableHintShardingAlgorithm
```

**Comment by M-make** [comment]
I change my `config-sharding.yaml` and `server.yaml`, the query is ok, it didn't even go to my custom hint

#### config-sharding.yaml
```yml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://132.232.39.227:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 88888888
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://132.232.39.227:3307/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 88888888
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    test_table1:
      actualDataNodes: ds_${0..1}.test_table1
      tableStrategy:
        hint:
          algorithmClassName: org.TableHintShardingAlgorithm
      databaseStrategy:
        hint:
          algorithmClassName: org.DbHintShardingAlgorithm
  bindingTables:
    - test_table1
  defaultDatabaseStrategy:
    hint:
      algorithmClassName: org.DbHintShardingAlgorithm
  defaultTableStrategy:
    hint:
      algorithmClassName: org.TableHintShardingAlgorithm
```

#### server.yaml
```yml
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 
      authorizedSchemas: sharding_db

props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: XA
  proxy.opentracing.enabled: false
  query.with.cipher.column: true
  sql.show: false
```

#### DbHintShardingAlgorithm
```java
public class DbHintShardingAlgorithm implements HintShardingAlgorithm<Integer> {

    private static final Logger LOGGER = LoggerFactory.getLogger(DbHintShardingAlgorithm.class);

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<Integer> shardingValue) {
        if (1==1)throw new RuntimeException();
        LOGGER.info(" in "+availableTargetNames);
        Collection<String> tables = new ArrayList<>();
        for (String availableTargetName : availableTargetNames) {
            tables.add(availableTargetName.split(".")[0]);
        }
        LOGGER.info(" out "+tables);
        return tables;
    }
}
```

#### TableHintShardingAlgorithm
```java
public class TableHintShardingAlgorithm implements HintShardingAlgorithm<Integer> {

    private static final Logger LOGGER = LoggerFactory.getLogger(DbHintShardingAlgorithm.class);

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<Integer> shardingValue) {
        if (1==1)throw new RuntimeException();
        LOGGER.info(" in "+availableTargetNames);
        Collection<String> tables = new ArrayList<>();
        for (String availableTargetName : availableTargetNames) {
            tables.add(availableTargetName.split(".")[1]);
        }
        LOGGER.info(" out "+tables);
        return tables;
    }
}
```

#### Client
```java
public class Test {
    public static void main(String[] args) {
        MysqlDataSource mysqlDataSource = new MysqlDataSource();
        mysqlDataSource.setUser("sharding");
        mysqlDataSource.setPassword("sharding");
        mysqlDataSource.setUrl("jdbc:mysql://localhost:3307/sharding_db?serverTimezone=UTC&useSSL=false");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(mysqlDataSource);
        List<Map<String, Object>> query = jdbcTemplate.query("select * from test_table1", new ColumnMapRowMapper());
        System.out.println(query);

    }
}
```

#### result
```console
[{id=1, name=111}, {id=1, name=222}]
```

**Comment by cherrylzhao** [comment]
you can try to debug it, and see our example, how to use hint, HintMananger is necessary.

**Comment by cherrylzhao** [comment]
sorry, hint cannot be supported, because we have not api to set HintManager through proxy JDBC.

**Comment by M-make** [comment]
> sorry, hint cannot be supported, because we have not api to set HintManager through proxy JDBC.


Do you mean that `shardingproxy` does not support `hint`?

**Comment by cherrylzhao** [comment]
yes, If you are interested about it, you can make a enhancement using proxy [sctl](https://shardingsphere.apache.org/document/current/cn/manual/sharding-proxy/usage/#sctl-sharding-proxy-control-language)

**Comment by M-make** [comment]
> yes, If you are interested about it, you can make a enhancement using proxy [sctl](https://shardingsphere.apache.org/document/current/cn/manual/sharding-proxy/usage/#sctl-sharding-proxy-control-language)

Ok,thank you very much

**Comment by cherrylzhao** [comment]
created another hint enhance issue in #2979 2979
