### ISSUE TITLE
SQLParseResultCache what behavior if gc happen, may cause sql route wrong 

### ISSUE THREAD

**Issue by Ah39** [apache/incubator-shardingsphere#2965]
## Question
if the jvm gc , SQLParseResultCache may remove sql parse result, when many thread  execute the sql

**Comment by Ah39** [comment]
3.1.0version

Caused by: java.lang.NullPointerException: null
 
    at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139)
 
    at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
 
    at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
 
    at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
 
    at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
 
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
 
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
 
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
 
    at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
 
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
    at java.lang.reflect.Method.invoke(Method.java:498)
 
    at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
 
    at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:401)
 
    at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:374)
 
    at com.github.pagehelper.PageHelper.intercept(PageHelper.java:255)
 
    at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
 
    at com.sun.proxy.$Proxy142.query(Unknown Source)
 
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
 
    ... 19 common frames omitted

**Comment by terrymanu** [comment]
Can you try to 4.0.0-RC2

**Comment by terrymanu** [comment]
Closed for no response any more, if the issue still existed, please create a new issue
