### ISSUE TITLE
decrypt the plain data when "query.with.cipher.column" is false

### ISSUE THREAD

**Issue by SAMARITAN2046** [apache/incubator-shardingsphere#2973]
Sharding-encript
version:4.0.0-RC2-SNAPSHOT
my logical sql
SQL: select
          id, applyNum, status,
          applyName, idNo, phone
        from cf_application_info
        where applyNum = ?
the bug is:when my setting "query.with.cipher.column" is false,i query my origin data(plain data) ,it happens exception.it seems the code still using the aks to decrypt my data.
this is the exception:
Caused by:
	at com.jdd.aks.extend.AksShardingExtend.decrypt(AksShardingExtend.java:122)
	at org.apache.shardingsphere.core.execute.sql.execute.result.StreamQueryResult.decrypt(StreamQueryResult.java:162)
	at org.apache.shardingsphere.core.execute.sql.execute.result.StreamQueryResult.decrypt(StreamQueryResult.java:157)
	at org.apache.shardingsphere.core.execute.sql.execute.result.StreamQueryResult.getValue(StreamQueryResult.java:75)
	at org.apache.shardingsphere.core.merge.dql.common.StreamMergedResult.getValue(StreamMergedResult.java:56)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.EncryptResultSet.getString(EncryptResultSet.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ResultSetLogger.invoke(ResultSetLogger.java:68)
	at org.apache.ibatis.type.StringTypeHandler.getNullableResult(StringTypeHandler.java:37)
	at org.apache.ibatis.type.StringTypeHandler.getNullableResult(StringTypeHandler.java:26)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:66)
	... 43 more
i hope this can be fixed.thanks

**Comment by tristaZero** [comment]
Got it, i will fix this bug asap.
