### ISSUE TITLE
分页查询返回的是Long类型。但是代码做了Integer类型强制转化。

### ISSUE THREAD

**Issue by dhuaqiao** [apache/incubator-shardingsphere#3001]
org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination

private int getValue(PaginationValueSegment paginationValueSegment, List<Object> parameters) {
        return paginationValueSegment instanceof ParameterMarkerPaginationValueSegment ? **(Integer)**parameters.get(((ParameterMarkerPaginationValueSegment)paginationValueSegment).getParameterIndex()) : ((NumberLiteralPaginationValueSegment)paginationValueSegment).getValue();
    }

**Comment by dhuaqiao** [comment]
4.0.0-RC2版本
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination.getValue(Pagination.java:60)
	at org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination.<init>(Pagination.java:54)

**Comment by sunbufu** [comment]
Duplicate of https://github.com/apache/incubator-shardingsphere/issues/2926.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
