### ISSUE TITLE
run sql "select * from pp"....exception is "java.sql.SQLSyntaxErrorException: Table 'test.pp' doesn't exist"

### ISSUE THREAD

**Issue by beijing-penguin** [apache/incubator-shardingsphere#3035]
1、my databases have two simple table: pp_0 and pp_1.
2、i use the project newest version code is incubator-shardingsphere's dev or 4.0.0-RC2
3、shardingjdbc config is:
```java
		// 配置真实数据源
	    Map<String, DataSource> dataSourceMap = new HashMap<>();
	    // 配置第一个数据源
	    DruidDataSource dataSource1 = new DruidDataSource();
	    dataSource1.setUrl("jdbc:mysql://localhost:3306/test?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT");
	    dataSource1.setUsername("root");
	    dataSource1.setPassword("123456");
	    dataSourceMap.put("ds0", dataSource1);
	    
	    TableRuleConfiguration testTableRuleConfig = new TableRuleConfiguration("pp");
	    testTableRuleConfig.setTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("id", "pp_${id % 2}"));
	    ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
	    shardingRuleConfig.getTableRuleConfigs().add(testTableRuleConfig);
	    // 获取数据源对象
	    DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, new Properties());
try {
		    DbHelper db = new DbHelper(dataSource);
		    List<Map<String,Object>> list = db.selectList("select * from pp");
		    System.out.println(JSON.toJSONString(list));
	    }catch (Exception e) {
	    	e.printStackTrace();
		}
	    ConnectionManager.closeConnectionAll();
```
---------------------------------------------------------------------------------------------
4、
```java
java.sql.SQLSyntaxErrorException: Table 'test.pp' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.getQueryResult(PreparedStatementExecutor.java:116)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.access$2(PreparedStatementExecutor.java:114)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:108)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:1)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:68)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:57)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73)
	at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:56)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:133)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeQuery(PreparedStatementExecutor.java:111)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:116)
	at org.dc.jdbc.core.utils.JDBCUtils.setParamsReturnRS(JDBCUtils.java:55)
	at org.dc.jdbc.core.DbHelper.selectList(DbHelper.java:88)
	at org.dc.jdbc.core.DbHelper.selectList(DbHelper.java:98)
	at com.dc.shardingtest.App.main(App.java:44)
```
5、I hope that the result is “pp_0” and "pp_1" all data

**Comment by KomachiSion** [comment]
@beijing-penguin , Please add actualNodes to `testTableRuleConfig ` like 
```
testTableRuleConfig.setActualDataNodes("test.pp_${0..1}");
```

**Comment by beijing-penguin** [comment]
yes,Problem solved，ths....
