### ISSUE TITLE
execute query on tables without encryption rules throws NullPointerException

### ISSUE THREAD

**Issue by ixiaomlt** [apache/incubator-shardingsphere#3070]
#### version of sharesphere
4.0.0-RC2

#### version of database
Oracle 11.2.0.4.0

#### version of java
jdk_7u80

#### version of tomcat
7.0.93

#### config
~~~xml
<bean id="misDataSource" class="com.jolbox.bonecp.BoneCPDataSource" destroy-method="close">
	   <property name="driverClass" value="${oracle.jdbc.driverClassName}"/>
	   <property name="jdbcUrl" value="${oracle.jdbc.url}"/>
	   <property name="username" value="${oracle.jdbc.username}"/>
	   <property name="password" value="${oracle.jdbc.password}"/>
	   <property name="idleConnectionTestPeriodInSeconds" value="10"/>
	   <property name="idleMaxAgeInMinutes" value="60"/>
	   <property name="maxConnectionsPerPartition" value="50"/>
	   <property name="minConnectionsPerPartition" value="10"/>
	   <property name="partitionCount" value="4"/>
	   <property name="acquireIncrement" value="3"/>
	   <property name="statementsCacheSize" value="0"/>
	   <property name="deregisterDriverOnClose" value="true"/>
	   <property name="resetConnectionOnClose" value="true"/>
	   <property name="connectionTimeoutInMs" value="1"/>
	</bean>

     <bean:properties id="props">
        <prop key="aes.key.value">aes-gdna</prop>
    </bean:properties>

    <encrypt:data-source id="shardingDataSource"  data-source-name="misDataSource" >
        <encrypt:encrypt-rule>
            <encrypt:tables>
                <encrypt:table name="sys_user">
                    <encrypt:column logic-column="certificate_no"
                    	plain-column="certificate_no"
                    	cipher-column="certificate_no_cipher"
                    	encryptor-ref="encryptor_aes" />
                </encrypt:table>
            </encrypt:tables>
            <encrypt:encryptors>
                <encrypt:encryptor id="encryptor_aes" type="AES" props-ref="props"/>
                <encrypt:encryptor id="encryptor_md5" type="MD5" />
            </encrypt:encryptors>
        </encrypt:encrypt-rule>
        <encrypt:props>
            <prop key="sql.show">true</prop>
            <prop key="query.with.cipher.column">false</prop>
        </encrypt:props>
    </encrypt:data-source>

	<bean id="misSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean" >
        <property name="dataSource" ref="shardingDataSource"/>
        <property name="configLocation" value="classpath:MyBatis-Configuration.xml"></property>
    </bean>

    <bean id="sqlSession" class="org.mybatis.spring.SqlSessionTemplate" destroy-method="close" scope="prototype">
    	<constructor-arg index="0" ref="misSessionFactory"/>
    </bean>

	<bean id="baseDao" class="com.highershine.gdna2.dao.GdnaBaseDao">
		<property name="sqlSessionTemplate" ref="sqlSession"></property>
	</bean>

	<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="shardingDataSource"></property>
	</bean>
~~~

### start sharesphere log
~~~log
19-09-19 16:30:30:670 - {INFO} util.ConfigurationLogger Thread [localhost-startStop-1];  EncryptRuleConfiguration
encryptors:
  encryptor_aes:
    props:
      aes.key.value: aes-gdna
    type: AES
  encryptor_md5:
    type: MD5
tables:
  sys_user:
    columns:
      certificate_no:
        assistedQueryColumn: ''
        cipherColumn: certificate_no_cipher
        encryptor: encryptor_aes
        plainColumn: certificate_no

19-09-19 16:30:30:670 - {INFO} util.ConfigurationLogger Thread [localhost-startStop-1];  Properties
sql.show: 'true'
query.with.cipher.column: 'false'
~~~

#### error log
~~~log
### The error may involve system.SysConfigMapper.getSysConfig-Inline
### The error occurred while setting parameters
### SQL: select            ID, CONFIG_CATEGORY, CONFIG_KEY, CONFIG_NAME, CONFIG_VALUE, DEFAULT_VALUE, ACTIVE_FLAG,       ORD, REMARK, CREATE_USER, CREATE_DATETIME, UPDATE_USER, UPDATE_DATETIME          from SYS_CONFIG              WHERE 1=1              AND CONFIG_CATEGORY = ?             AND CONFIG_KEY = ?
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:107)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:354)
	... 41 more
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter$1.execute(AbstractStatementAdapter.java:59)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter$1.execute(AbstractStatementAdapter.java:55)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.execute(ForceExecuteTemplate.java:44)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter.close(AbstractStatementAdapter.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:77)
	at com.sun.proxy.$Proxy137.close(Unknown Source)
	at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:231)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:59)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:259)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:132)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:115)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104)
	... 48 more
~~~

The sys_config table does not set encryptRule and does not set any logicColumn on this table, but throws an exception. I want to know where my configuration file is incorrectly configured. Please help me find it out.

**Comment by sunbufu** [comment]
Can your show some sql ?

**Comment by ixiaomlt** [comment]
@sunbufu , You can find it in the error log.

**Comment by ixiaomlt** [comment]
@terrymanu When will the 4.0.0-RC3 version be released?

**Comment by sunbufu** [comment]
Can you create an example project and push to github?  I have executed a select sql with non-encrypt and non-sharding table, and got a right result.

**Comment by ixiaomlt** [comment]
@sunbufu example project is [here](https://github.com/ixiaomlt/shardingsphere-jdbc-demo.git)

**Comment by sunbufu** [comment]
I think you should add this dependency in your `pom.xml`.
```xml
<dependency>
	<groupId>org.apache.shardingsphere</groupId>
	<artifactId>sharding-jdbc-core</artifactId>
	<version>4.0.0-RC2</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/14866067/65386591-53972200-dd70-11e9-87a6-3d6c07af9886.png)

**Comment by ixiaomlt** [comment]
Are you using version 11.2.0.4 for Oracle?
