### ISSUE TITLE
Must have sharding column with subquery

### ISSUE THREAD

**Issue by hunter7727** [apache/incubator-shardingsphere#3102]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
Execute sql correctly
### Actual behavior
Execute sql statement error
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Environmental configuration：
```
dataSources:
  cyberplus-meta-define1:
    url: jdbc:mysql://localhost:3306/cyberplus-meta-define1?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50



shardingRule:
  tables:
    t_proposal_workflow:
          actualDataNodes: cyberplus-meta-define1.t_proposal_workflow
          databaseStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: cyberplus-meta-define1
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
  defaultDataSourceName: cyberplus-meta-define1
```
Error stack information：
```
Hibernate: SELECT COUNT(1) AS TOTAL FROM (select T_PROPOSAL_WORKFLOW.INPUT_DATE AS INPUTDATE,T_PROPOSAL_WORKFLOW.INTERMEDIARY_NAME AS INTERMEDIARYNAME,T_PROPOSAL_WORKFLOW.ORG_CODE AS ORGCODE,T_PROPOSAL_WORKFLOW.APPLY_NO AS APPLYNO,T_PROPOSAL_WORKFLOW.POLICY_NO AS POLICYNO,T_PROPOSAL_WORKFLOW.PRODUCT_CODE AS PRODUCTCODE,T_PROPOSAL_WORKFLOW.APPLICANT_CODE AS APPLICANTCODE,T_PROPOSAL_WORKFLOW.INSURED_CODE AS INSUREDCODE,T_PROPOSAL_WORKFLOW.START_DATE AS STARTDATE,T_PROPOSAL_WORKFLOW.END_DATE AS ENDDATE,T_PROPOSAL_WORKFLOW.TASK_FLAG AS TASKFLAG,T_PROPOSAL_WORKFLOW.CURRENT_HANDLER AS CURRENTHANDLER,T_PROPOSAL_WORKFLOW.EMERGENCY_LEVEL AS EMERGENCYLEVEL,T_PROPOSAL_WORKFLOW.HANDLER_CODE AS HANDLERCODE,T_PROPOSAL_WORKFLOW.BIZ_DEVELOPMENT_METHOD AS BIZDEVELOPMENTMETHOD,T_PROPOSAL_WORKFLOW.ENDR_TYPE AS ENDRTYPE,T_PROPOSAL_WORKFLOW.O_ID AS OID from T_PROPOSAL_WORKFLOW where T_PROPOSAL_WORKFLOW.APPLY_NO like ? and T_PROPOSAL_WORKFLOW.O_BUSINESS_TYPE=?) TOTAL
java.lang.IllegalStateException: Must have sharding column with subquery.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.checkSubqueryShardingValues(ParsingSQLRouter.java:111)
	at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:75)
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:66)
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:60)
	at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:86)
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:70)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:224)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:110)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2168)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1931)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1893)
	at org.hibernate.loader.Loader.doQuery(Loader.java:938)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
	at org.hibernate.loader.Loader.doList(Loader.java:2692)
	at org.hibernate.loader.Loader.doList(Loader.java:2675)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2507)
	at org.hibernate.loader.Loader.list(Loader.java:2502)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:335)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2200)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1016)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:152)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1463)
	at cn.com.cyberplus.meta.instance.dao.impl.SnDAOImpl.getSnCount(SnDAOImpl.java:496)
	at cn.com.cyberplus.meta.instance.dao.impl.SnDAOImpl$$FastClassBySpringCGLIB$$14a9680.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at cn.com.cyberplus.meta.instance.dao.impl.SnDAOImpl$$EnhancerBySpringCGLIB$$9bc42b42.getSnCount(<generated>)
	at cn.com.cyberplus.meta.instance.dm.impl.SnDMServiceImpl.getSnCount(SnDMServiceImpl.java:439)
	at cn.com.cyberplus.meta.instance.dm.impl.SnDMServiceImpl$$FastClassBySpringCGLIB$$7f9827cd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at cn.com.cyberplus.meta.instance.dm.impl.SnDMServiceImpl$$EnhancerBySpringCGLIB$$ecf79749.getSnCount(<generated>)
	at cn.com.cyberplus.meta.instance.search.service.impl.SnSearchServiceImpl.searchSn(SnSearchServiceImpl.java:83)
	at cn.com.cyberplus.meta.instance.search.controller.SnSearchController.searchSn(SnSearchController.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

### Example codes for reproduce this issue (such as a github link).
Executing sql is 
SELECT COUNT(1) AS TOTAL FROM (select T_PROPOSAL_WORKFLOW.INPUT_DATE AS INPUTDATE,T_PROPOSAL_WORKFLOW.INTERMEDIARY_NAME AS INTERMEDIARYNAME,T_PROPOSAL_WORKFLOW.ORG_CODE AS ORGCODE,T_PROPOSAL_WORKFLOW.APPLY_NO AS APPLYNO,T_PROPOSAL_WORKFLOW.POLICY_NO AS POLICYNO,T_PROPOSAL_WORKFLOW.PRODUCT_CODE AS PRODUCTCODE,T_PROPOSAL_WORKFLOW.APPLICANT_CODE AS APPLICANTCODE,T_PROPOSAL_WORKFLOW.INSURED_CODE AS INSUREDCODE,T_PROPOSAL_WORKFLOW.START_DATE AS STARTDATE,T_PROPOSAL_WORKFLOW.END_DATE AS ENDDATE,T_PROPOSAL_WORKFLOW.TASK_FLAG AS TASKFLAG,T_PROPOSAL_WORKFLOW.CURRENT_HANDLER AS CURRENTHANDLER,T_PROPOSAL_WORKFLOW.EMERGENCY_LEVEL AS EMERGENCYLEVEL,T_PROPOSAL_WORKFLOW.HANDLER_CODE AS HANDLERCODE,T_PROPOSAL_WORKFLOW.BIZ_DEVELOPMENT_METHOD AS BIZDEVELOPMENTMETHOD,T_PROPOSAL_WORKFLOW.ENDR_TYPE AS ENDRTYPE,T_PROPOSAL_WORKFLOW.O_ID AS OID from T_PROPOSAL_WORKFLOW where T_PROPOSAL_WORKFLOW.APPLY_NO like '%E2019092306124001%' and T_PROPOSAL_WORKFLOW.O_BUSINESS_TYPE=4) TOTAL

**Comment by terrymanu** [comment]
Can you change the title more meaningful for search friendly? Title may describe the problem summary.

**Comment by tanhuang2016** [comment]
I also have this problem, the official website says that this kind of SQL is supported
![图片](https://user-images.githubusercontent.com/38677722/65656426-68b2d000-e052-11e9-847c-45f940480c2b.png)

**Comment by terrymanu** [comment]
@hunter7727 Hi, can you change the title more meaningful for search friendly? Title may describe the problem summary.

**Comment by terrymanu** [comment]
Closed until change the title more meaningful.

**Comment by hunter7727** [comment]
Sorry,I can't change the title now. can you help me change to "when there is a sql subquery, the implementation error"?

**Comment by hunter7727** [comment]
The same problem occurs when there are associated queries and subqueries appear in the sql statement.Such as this sql statement:select * from (select id,key,value) as a,b,c where a.id = b.key_id and b.key_id = c.p_id;
