### ISSUE TITLE
Cannot find JDBC type '2003' in PostgreSQL column type

### ISSUE THREAD

**Issue by xilipilige** [apache/incubator-shardingsphere#3104]
sharding-proxy 4.0.0.RC
postgresql 10.4

when i use the sharding-proxy manage two node pg server
the console log show that 
![image](https://user-images.githubusercontent.com/18464734/65507128-caaef080-deff-11e9-927a-12bc281905f2.png)

![image](https://user-images.githubusercontent.com/18464734/65507208-fc27bc00-deff-11e9-85a4-f28121de78e3.png)

**Comment by dongzl** [comment]
Hi @xilipilige , can you show more detail information about this problem, for example table structure.

**Comment by xilipilige** [comment]
> Hi @xilipilige , can you show more detail information about this problem, for example table structure.

CREATE TABLE public.device (
	device_id bigint NOT NULL,
	device_name varchar NULL,
	tenant_id bigint NULL,
	CONSTRAINT device_pk PRIMARY KEY (device_id)
)
WITH (
	OIDS=FALSE
) ;

**Comment by dongzl** [comment]
Hi @xilipilige , I'm sorry I didn't reply to you in time.

Do you describe more details, the execute SQL and so on.

**Comment by terrymanu** [comment]
Will close soon if no update anymore.

**Comment by RaigorJiang** [comment]
The problem reproduced, I am looking for a cause.

**Comment by dongzl** [comment]
> The problem reproduced, I am looking for a cause.

Hi @RaigorJiang , can you describe the reproduced process?

**Comment by RaigorJiang** [comment]
Yes,  I prepared an environment like #3419 ,  then use Navicat (version 11.2.18)  or  DBeaver (version 6.0.0) to connect to Proxy(version 4.0.0-RC3),    and the Exception occur.

![image](https://user-images.githubusercontent.com/5668787/68921310-4ec07e80-07b3-11ea-998e-dfa98d29ff1e.png)

**Comment by RaigorJiang** [comment]
Error Log is :

`line 1:24 mismatched input 'session_user' expecting {'U', 'u', '!', '~', '+', '-', '(', '{', '?', INSERT, UPDATE, DELETE, ALTER, DROP, TRUNCATE, SCHEMA, REVOKE, ADD, SET, INDEX, KEY, FUNCTION, TRIGGER, PROCEDURE, CASE, CAST, IF, NOT, NULL, TRUE, FALSE, EXISTS, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, BOOLEAN, CHAR, INTERVAL, TIME, TIMESTAMP, LOCALTIME, LOCALTIMESTAMP, YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, MAX, MIN, SUM, COUNT, AVG, CURRENT, ENABLE, DISABLE, INSTANCE, PRESERVE, DEFINER, SQL, CASCADED, LOCAL, CLOSE, OPEN, NEXT, NAME, NAMES, INTEGER, REAL, DECIMAL, TYPE, ADMIN, BINARY, ESCAPE, EXCLUDE, PARTITION, ROW, UNKNOWN, ALWAYS, CASCADE, GENERATED, ISOLATION, LEVEL, OPTION, PRIVILEGES, READ, ROLE, ROWS, START, TRANSACTION, ACTION, CACHE, CHARACTERISTICS, CLUSTER, COMMENTS, CONSTRAINTS, CURRENT_TIMESTAMP, CYCLE, DATA, DATABASE, DEFAULTS, DEFERRED, DEPENDS, DOMAIN, EXCLUDING, EXECUTE, EXTENDED, EXTENSION, EXTERNAL, EXTRACT, FILTER, FIRST, FOLLOWING, FORCE, GLOBAL, IDENTITY, IMMEDIATE, INCLUDING, INCREMENT, INDEXES, INHERIT, INHERITS, INCLUDE, LANGUAGE, LARGE, LAST, LOGGED, MAIN, MATCH, MAXVALUE, MINVALUE, NOTHING, NULLS, OBJECT, OIDS, OVER, OWNED, OWNER, PARTIAL, PLAIN, PRECEDING, RANGE, RENAME, REPLICA, RESET, RESTART, RESTRICT, ROUTINE, RULE, SECURITY, SEQUENCE, SESSION, SHOW, SIMPLE, STATISTICS, STORAGE, TABLESPACE, TEMP, TEMPORARY, UNBOUNDED, UNLOGGED, USAGE, VALID, VALIDATE, WITHIN, WITHOUT, ZONE, OF, GROUPS, RECURSIVE, IDENTIFIER_, STRING_, NUMBER_, HEX_DIGIT_, BIT_NUM_}
[ERROR] 14:12:34.778 [pool-11-thread-1] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IllegalArgumentException: Cannot find JDBC type '2003' in PostgreSQL column type
	at org.apache.shardingsphere.shardingproxy.transport.postgresql.constant.PostgreSQLColumnType.valueOfJDBCType(PostgreSQLColumnType.java:187)
	at org.apache.shardingsphere.shardingproxy.transport.postgresql.packet.command.query.PostgreSQLColumnDescription.<init>(PostgreSQLColumnDescription.java:48)
	at org.apache.shardingsphere.shardingproxy.frontend.postgresql.command.query.binary.bind.PostgreSQLComBindExecutor.getPostgreSQLColumnDescriptions(PostgreSQLComBindExecutor.java:118)
	at org.apache.shardingsphere.shardingproxy.frontend.postgresql.command.query.binary.bind.PostgreSQLComBindExecutor.createQueryPacket(PostgreSQLComBindExecutor.java:106)
	at org.apache.shardingsphere.shardingproxy.frontend.postgresql.command.query.binary.bind.PostgreSQLComBindExecutor.execute(PostgreSQLComBindExecutor.java:89)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by SteNicholas** [comment]
@RaigorJiang Can you provide this SQL?

**Comment by tuohai666** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/6232 .
