### ISSUE TITLE
When I update my data encrypt with assisted-query-column,it happens exception

### ISSUE THREAD

**Issue by SAMARITAN2046** [apache/incubator-shardingsphere#3132]
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
	... 18 more
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter$1.execute(AbstractStatementAdapter.java:59)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter$1.execute(AbstractStatementAdapter.java:55)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.executor.ForceExecuteTemplate.execute(ForceExecuteTemplate.java:44)
	at org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractStatementAdapter.close(AbstractStatementAdapter.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:78)
	at org.apache.ibatis.executor.BaseExecutor.closeStatement(BaseExecutor.java:275)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:51)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:115)

**Comment by sunbufu** [comment]
Can you show your configuration and SQL?

**Comment by tristaZero** [comment]
@SAMARITAN2046 
Hi, is this issue same with #3131 ? If so, please #3131 . Thanks.
Moreover, can you provide more log of this exception. And what's your encrypt-rule, sql, table description?
Please provide more details to make this issue clearer.
