### ISSUE TITLE
default configuration such as [defaultDataSourceName] set default value is better？

### ISSUE THREAD

**Issue by jiang2015** [apache/incubator-shardingsphere#3362]
### Is your feature request related to a problem?
yes, 
version of ShardingSphere: **4.0.0-RC3-SNAPSHOT**
project: Sharding-Proxy
The problem:
 when I use navicat connect Sharding-Proxy, Executing a SQL：
［SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION FROM INFORMATION_SCHEMA.PROFILING GROUP BY QUERY_ID;］the sql result throw Exception:

[INFO ] 19:59:49.313 [ShardingSphere-Command-5] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION FROM INFORMATION_SCHEMA.PROFILING GROUP BY QUERY_ID;)
[ERROR] 19:59:49.898 [ShardingSphere-Command-5] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:153)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:126)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:198)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:181)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:78)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:72)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:87)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I debug the source,find the reason: the file:[config-sharding.yaml] the part :[shardingRule] not configured [defaultDataSourceName] ,because the table [PROFILING] not configured in [shardingRule],so when the table [PROFILING] sharding it used defaultDataSource.

### Describe the feature you would like.
I see the source,find that the class[ShardingRuleConfiguration] has some default configuration,like [defaultDataSourceName],[defaultDatabaseShardingStrategyConfig] and so on,I think when the Sharding-Proxy start,like default configuration such as [defaultDataSourceName] set default value is better？

**Comment by yanickxia** [comment]
sounds like #3273 ?

**Comment by jiang2015** [comment]
I think it is Different with

**Comment by RaigorJiang** [comment]
Yes, I reproduced the problem, it's diffenent with #3273 
I found the nullpoint appears when 
`ShardingTransactionManager shardingTransactionManager = shardingTransactionManagerEngine.getTransactionManager(transactionType); `

the transactionType is not match the configuration in server.yaml and it causes the shardingTransactionManager is null

**Comment by RaigorJiang** [comment]
@jiang2015 
For this issue, I think adding default values is not appropriate, but we can solve the NullPointerException.
I am going to do this.

**Comment by terrymanu** [comment]
@RaigorJiang  Thank you, assigned.

**Comment by RaigorJiang** [comment]
Update:  I am still debugging this issue, try to find the best solution.

**Comment by RaigorJiang** [comment]
Hi,  I found the root cause of NullPointerException is:
The SQL is routed to default data source but didn't check whether the default data source exists, so the dataSourceName in RoutingUnit in null.
For this scene, I submitted a PR, please take a review,  thank you.
