### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by xr2117** [apache/incubator-shardingsphere#3437]
springboot 整合 shardingJDBC 和Mybatisplus 使用Page分页出现问题 会出现异常

**Comment by xr2117** [comment]
Page<Goods1> page = new Page<>();
        IPage<Goods1> iPage = goods1Mapper.selectPage(
                page,
                Wrappers.query());

**Comment by xr2117** [comment]
![Uploading 微信图片_20191102155858.png…]()

**Comment by xr2117** [comment]
2019-11-02 15:56:01.850 DEBUG [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] c.f.p.mapper.Goods1Mapper.selectPage     : ==>  Preparing: SELECT COUNT(1) FROM goods 
2019-11-02 15:56:01.857 DEBUG [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] c.f.p.mapper.Goods1Mapper.selectPage     : ==> Parameters: 
2019-11-02 15:56:01.882  INFO [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] ShardingSphere-SQL                       : Rule Type: sharding
2019-11-02 15:56:01.882  INFO [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] ShardingSphere-SQL                       : Logic SQL: SELECT COUNT(1) FROM goods
2019-11-02 15:56:01.882  INFO [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] ShardingSphere-SQL                       : SQLStatement: ShardingSelectOptimizedStatement(tables=Tables(tables=[Table(name=goods, alias=Optional.absent())], schema=Optional.absent()), groupBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.groupby.GroupBy@672a1254, orderBy=org.apache.shardingsphere.core.optimize.sharding.segment.select.orderby.OrderBy@5b4b8128, selectItems=SelectItems(startIndex=7, stopIndex=14, distinctRow=false, items=[AggregationSelectItem(type=COUNT, innerExpression=(1), alias=Optional.absent(), derivedAggregationItems=[], index=-1)], tables=[TableSegment(startIndex=21, stopIndex=25, name=goods, quoteCharacter=NONE, owner=Optional.absent(), alias=Optional.absent())]), pagination=org.apache.shardingsphere.core.optimize.sharding.segment.select.pagination.Pagination@4ca72fcf, containsSubquery=false)
2019-11-02 15:56:01.882  INFO [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] ShardingSphere-SQL                       : Actual SQL: m1 ::: SELECT COUNT(1) FROM goods_1
2019-11-02 15:56:01.882  INFO [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] ShardingSphere-SQL                       : Actual SQL: m1 ::: SELECT COUNT(1) FROM goods_2
2019-11-02 15:56:02.077 DEBUG [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] c.f.p.mapper.Goods1Mapper.selectPage     : ==>  Preparing: SELECT id,name,price FROM goods LIMIT ?,? 
2019-11-02 15:56:02.083 DEBUG [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] c.f.p.mapper.Goods1Mapper.selectPage     : ==> Parameters: 0(Long), 2(Long)
2019-11-02 15:56:02.107 ERROR [xri-microsservice-service-provider-impl,c27792394fe5fa77,c27792394fe5fa77,false] 17568 --- [nio-9000-exec-1] o.s.c.s.i.web.ExceptionLoggingFilter     : Uncaught exception thrown

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
### The error may exist in com/frame/provider/mapper/Goods1Mapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,name,price  FROM goods LIMIT ?,?
### Cause: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013) ~[spring-webmvc-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.8.RELEASE.jar:5.1.8.RELEASE]

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by javaerHei** [comment]
辣鸡
