### ISSUE TITLE
shardingproxy Bootstrap Booting failure

### ISSUE THREAD

**Issue by 59471032** [apache/incubator-shardingsphere#3502]
## Question
`[INFO ] 18:16:45.787 [main] o.a.c.f.imps.CuratorFrameworkImpl - Starting
[INFO ] 18:16:45.879 [main] org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
[INFO ] 18:16:45.879 [main] org.apache.zookeeper.ZooKeeper - Client environment:host.name=DESKTOP-0QFTKSS
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_172
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.home=D:\coding\Java\jdk1.8.0_172\jre
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=D:\coding\Java\jdk1.8.0_172\jre\lib\charsets.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\deploy.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\access-bridge-64.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\cldrdata.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\dnsns.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\jaccess.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\jfxrt.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\localedata.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\nashorn.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\sunec.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\sunjce_provider.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\sunmscapi.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\sunpkcs11.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\ext\zipfs.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\javaws.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\jce.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\jfr.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\jfxswt.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\jsse.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\management-agent.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\plugin.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\resources.jar;D:\coding\Java\jdk1.8.0_172\jre\lib\rt.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-bootstrap\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-common\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-entry\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-api\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-common\target\classes;D:\maven\repository\org\codehaus\groovy\groovy\2.4.5\groovy-2.4.5-indy.jar;D:\maven\repository\org\yaml\snakeyaml\1.16\snakeyaml-1.16.jar;D:\maven\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-parse\sharding-core-parse-common\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-parse\sharding-core-parse-spi\target\classes;D:\maven\repository\org\apache\commons\commons-collections4\4.2\commons-collections4-4.2.jar;D:\maven\repository\org\antlr\antlr4-runtime\4.7.1\antlr4-runtime-4.7.1.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-parse\sharding-core-parse-mysql\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-parse\sharding-core-parse-postgresql\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-parse\sharding-core-parse-oracle\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-parse\sharding-core-parse-sqlserver\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-optimize\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-route\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-rewrite\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-execute\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-core\sharding-core-merge\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-orchestration\sharding-orchestration-core\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-transport\sharding-proxy-transport-core\target\classes;D:\maven\repository\io\netty\netty-all\4.1.16.Final\netty-all-4.1.16.Final.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-transport\sharding-proxy-transport-mysql\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-transaction\sharding-transaction-core\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-transport\sharding-proxy-transport-postgresql\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-frontend\sharding-proxy-frontend-core\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-frontend\sharding-proxy-frontend-spi\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-frontend\sharding-proxy-frontend-mysql\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-frontend\sharding-proxy-frontend-postgresql\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-proxy\sharding-proxy-backend\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-transaction\sharding-transaction-2pc\sharding-transaction-xa\sharding-transaction-xa-core\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-transaction\sharding-transaction-2pc\sharding-transaction-xa\sharding-transaction-xa-spi\target\classes;D:\maven\repository\javax\transaction\jta\1.1\jta-1.1.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-transaction\sharding-transaction-2pc\sharding-transaction-xa\sharding-transaction-xa-atomikos\sharding-transaction-xa-atomikos-manager\target\classes;D:\maven\repository\com\atomikos\transactions\4.0.6\transactions-4.0.6.jar;D:\maven\repository\com\atomikos\transactions-api\4.0.6\transactions-api-4.0.6.jar;D:\maven\repository\com\atomikos\atomikos-util\4.0.6\atomikos-util-4.0.6.jar;D:\maven\repository\com\atomikos\transactions-jta\4.0.6\transactions-jta-4.0.6.jar;D:\maven\repository\com\atomikos\transactions-jdbc\4.0.6\transactions-jdbc-4.0.6.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-orchestration\sharding-orchestration-reg\sharding-orchestration-reg-zookeeper-curator\target\classes;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-orchestration\sharding-orchestration-reg\sharding-orchestration-reg-api\target\classes;D:\maven\repository\org\apache\curator\curator-framework\2.10.0\curator-framework-2.10.0.jar;D:\maven\repository\org\apache\curator\curator-client\2.10.0\curator-client-2.10.0.jar;D:\maven\repository\org\apache\zookeeper\zookeeper\3.4.6\zookeeper-3.4.6.jar;D:\maven\repository\log4j\log4j\1.2.16\log4j-1.2.16.jar;D:\maven\repository\jline\jline\0.9.94\jline-0.9.94.jar;D:\maven\repository\org\apache\curator\curator-recipes\2.10.0\curator-recipes-2.10.0.jar;D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release\sharding-opentracing\target\classes;D:\maven\repository\io\opentracing\opentracing-util\0.30.0\opentracing-util-0.30.0.jar;D:\maven\repository\io\opentracing\opentracing-api\0.30.0\opentracing-api-0.30.0.jar;D:\maven\repository\io\opentracing\opentracing-noop\0.30.0\opentracing-noop-0.30.0.jar;D:\maven\repository\com\zaxxer\HikariCP-java7\2.4.11\HikariCP-java7-2.4.11.jar;D:\maven\repository\org\postgresql\postgresql\42.2.5\postgresql-42.2.5.jar;D:\maven\repository\mysql\mysql-connector-java\5.1.47\mysql-connector-java-5.1.47.jar;D:\maven\repository\ch\qos\logback\logback-classic\1.2.0\logback-classic-1.2.0.jar;D:\maven\repository\ch\qos\logback\logback-core\1.2.0\logback-core-1.2.0.jar;D:\maven\repository\com\google\guava\guava\18.0\guava-18.0.jar;D:\maven\repository\org\slf4j\slf4j-api\1.7.7\slf4j-api-1.7.7.jar;D:\maven\repository\org\slf4j\jcl-over-slf4j\1.7.7\jcl-over-slf4j-1.7.7.jar;C:\Users\baocj\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\192.6817.14\lib\idea_rt.jar
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=D:\coding\Java\jdk1.8.0_172\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;D:\Program Files (x86)\NetSarang\Xshell 6\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\coding\Java\jdk1.8.0_172\bin;d:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%m2_home%\bin;C:\Users\baocj\AppData\Local\Microsoft\WindowsApps;;.
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=C:\Users\baocj\AppData\Local\Temp\
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.name=Windows 10
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.version=10.0
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.name=baocj
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.home=C:\Users\baocj
[INFO ] 18:16:45.880 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.dir=D:\coding\IdeaProjects\apache-shardingsphere-incubating-4.0.0-RC2-src-release
[INFO ] 18:16:45.883 [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.1.196:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@954b04f
[INFO ] 18:16:46.369 [main-SendThread(192.168.1.196:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.1.196/192.168.1.196:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO ] 18:16:46.371 [main-SendThread(192.168.1.196:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.1.196/192.168.1.196:2181, initiating session
[INFO ] 18:16:46.397 [main-SendThread(192.168.1.196:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.1.196/192.168.1.196:2181, sessionid = 0x101a22413ea000a, negotiated timeout = 40000
[INFO ] 18:16:46.429 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
[INFO ] 18:16:47.479 [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
[INFO ] 18:16:47.490 [main-EventThread] org.apache.zookeeper.ClientCnxn - EventThread shut down
[INFO ] 18:16:47.490 [main] org.apache.zookeeper.ZooKeeper - Session: 0x101a22413ea000a closed
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:64)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427)
	at org.apache.shardingsphere.core.yaml.engine.YamlEngine.unmarshal(YamlEngine.java:87)
	at org.apache.shardingsphere.orchestration.internal.registry.config.service.ConfigurationService.loadAuthentication(ConfigurationService.java:244)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:110)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:80)
`

**Comment by 59471032** [comment]
[config-sharding.txt](https://github.com/apache/incubator-shardingsphere/files/3831121/config-sharding.txt)
[server.txt](https://github.com/apache/incubator-shardingsphere/files/3831122/server.txt)

**Comment by 59471032** [comment]
I have solved the problem,but new problem happend.
[config-sharding.txt](https://github.com/apache/incubator-shardingsphere/files/3834206/config-sharding.txt)
[server.txt](https://github.com/apache/incubator-shardingsphere/files/3834207/server.txt)
`
[ERROR] 11:12:22.828 [ShardingSphere-Command-4] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:198)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:181)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:78)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 11:12:22.958 [ShardingSphere-Command-9] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:198)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:181)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:78)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 11:12:22.990 [ShardingSphere-Command-10] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:198)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:181)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:78)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 11:12:23.049 [ShardingSphere-Command-11] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:198)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:181)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:93)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:78)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)



`

**Comment by 59471032** [comment]
`
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/var/folders/7l/3198rz0j16db4chqmc67dn6m0000gn/T/
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.name=Mac OS X
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.arch=x86_64
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:os.version=10.15.1
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.name=zhaolei
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.home=/Users/baocj
[INFO ] 11:14:03.796 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/Users/baocj/IdeaProjects/incubator-shardingsphere
[INFO ] 11:14:03.802 [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@78b66d36
[INFO ] 11:14:03.848 [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO ] 11:14:03.988 [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established to localhost/0:0:0:0:0:0:0:1:2181, initiating session
[INFO ] 11:14:04.022 [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 
`

**Comment by RaigorJiang** [comment]
@59471032  I'll try with your configuration file.

**Comment by RaigorJiang** [comment]
@59471032 
I used your configuration to run the proxy and the startup was successful.
What's your sharding-proxy version?

**Comment by terrymanu** [comment]
I just assign this issue to you, thank you @RaigorJiang

**Comment by RaigorJiang** [comment]
OK,   @59471032  any update?

**Comment by RaigorJiang** [comment]
@59471032    Will close soon if no response anymore.
