### ISSUE TITLE
Run sharding proxy to proxy postgresql through the official docker image startup failed

### ISSUE THREAD

**Issue by avalon566** [apache/incubator-shardingsphere#3527]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Reason analyze (If you can)

postgresql-42.2.5.jar is compile with java 8. Should we update the docker file base image to  java:8?

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/postgresql/Driver : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.validateDriverClassName(JDBCRawBackendDataSourceFactory.java:81)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCRawBackendDataSourceFactory.build(JDBCRawBackendDataSourceFactory.java:54)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createDataSources(JDBCBackendDataSource.java:75)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.<init>(JDBCBackendDataSource.java:67)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchema.<init>(LogicSchema.java:60)
	at org.apache.shardingsphere.shardingproxy.backend.schema.ShardingSchema.<init>(ShardingSchema.java:66)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.createLogicSchema(LogicSchemas.java:116)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.initSchemas(LogicSchemas.java:106)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:96)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:81)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithoutRegistryCenter(Bootstrap.java:101)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:78)
```

**Comment by terrymanu** [comment]
Did you mean `official` docker image?

**Comment by avalon566** [comment]
Sorry, spelling mistake.
Yes, [Dockerfile](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-distribution/sharding-proxy-distribution/src/main/docker/Dockerfile)

**Comment by SteNicholas** [comment]
Exception that “Unsupported major.minor version 52.0” is caused by the compile version of JDK.Please use JDK8 compile this image.

**Comment by terrymanu** [comment]
Does anybody interest with this issue?

**Comment by avalon566** [comment]
I am interesting, pls assign to me.
