### ISSUE TITLE
mvnw build error

### ISSUE THREAD

**Issue by xiaobai022sdo** [apache/incubator-shardingsphere#3554]
[root@ incubator-shardingsphere-4.0.0-RC3]# ./mvnw clean install -Prelease
--2019-11-19 09:47:45--  https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.4.2/maven-wrapper-0.4.2.jar
Resolving repo.maven.apache.org (repo.maven.apache.org)... 151.101.196.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|151.101.196.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48337 (47K) [application/java-archive]
Saving to: ‘/data/sharding/incubator-shardingsphere-4.0.0-RC3/.mvn/wrapper/maven-wrapper.jar’

100%[=================================================================================================================================================================================================>] 48,337       124KB/s   in 0.4s   

2019-11-19 09:47:46 (124 KB/s) - ‘/data/sharding/incubator-shardingsphere-4.0.0-RC3/.mvn/wrapper/maven-wrapper.jar’ saved [48337/48337]

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:161)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:78)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)

**Comment by JaredTan95** [comment]
I tested in my local dev laptop, and all runs well.  Maybe you can clean your `m2` cache and retry.

**Comment by xiaobai022sdo** [comment]
I try to delete the M2 folder and  solve the problem of clean install again . Thanks
