### ISSUE TITLE
(Proxy) Receive error response for postgres JDBC client

### ISSUE THREAD

**Issue by RaigorJiang** [apache/incubator-shardingsphere#3555]
### Which version of ShardingSphere did you use?
sharding-proxy : 4.0.0-RC3-SNAPSHOT

### Expected behavior
Insert record successful and get a correct response.

### Actual behavior
Insert record successful but the client get an error response.

### Steps to reproduce the behavior
Table structure:
----------------------------------
CREATE TABLE public.t_encrypt (
 pwd varchar(32) NULL,
 "content" varchar(32) NULL
)
----------------------------------
config-encrypt.yaml:
----------------------------------
![image](https://user-images.githubusercontent.com/5668787/69121257-d4f00400-0ad6-11ea-9704-0abb4f0badf1.png)

----------------------------------
Code:
`statement.executeUpdate(SQL_INSERT);`

Actual behavior:
The insert is successful and Proxy is OK, but the client gets an error.

**Comment by RaigorJiang** [comment]
The Error log is : 

`org.postgresql.util.PSQLException: 
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:246)`

**Comment by SteNicholas** [comment]
@RaigorJiang Can you provide the exception log?

**Comment by geomonlin** [comment]
I  also find this problem.  Incorrect response result with PostgreSQLCommandCompletePacket  in sharding-proxy.  
![image](https://user-images.githubusercontent.com/26007894/71818648-83222e00-30c4-11ea-914d-eb83aec33d7e.png)
These are affected in PostgreSQLComBindExecutor.
![image](https://user-images.githubusercontent.com/26007894/71818704-a816a100-30c4-11ea-9d9e-cc55da015fc9.png)

**Comment by tuohai666** [comment]
I'll check it later.
