### ISSUE TITLE
sharding-proxy enable zookeeper configuration start error ,version: 4.0.0-RC4

### ISSUE THREAD

**Issue by xiaobai022sdo** [apache/incubator-shardingsphere#3561]
sharding-Proxy enable zookeeper configuration in server.yaml
##########
orchestration:
  name: orchestration_ds
  overwrite: true
  registry:
    type: zookeeper
    serverLists: 172.16.251.58:2181
    namespace: orchestration
##################

[INFO ] 10:49:13.732 [main] org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/data/sharding/apache-shardingsphere-incubating-4.0.0-RC4-SNAPSHOT-sharding-proxy-bin
[INFO ] 10:49:13.733 [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=172.16.251.58:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@78dd667e
[INFO ] 10:49:13.755 [main-SendThread(172.16.251.58:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 172.16.251.58/172.16.251.58:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO ] 10:49:13.825 [main-SendThread(172.16.251.58:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established to 172.16.251.58/172.16.251.58:2181, initiating session
[INFO ] 10:49:15.255 [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
[INFO ] 10:49:17.418 [main-SendThread(172.16.251.58:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server 172.16.251.58/172.16.251.58:2181, sessionid = 0x102ad5dd41c0008, negotiated timeout = 40000
[INFO ] 10:49:17.427 [main] org.apache.zookeeper.ZooKeeper - Session: 0x102ad5dd41c0008 closed
[INFO ] 10:49:17.427 [main-EventThread] org.apache.zookeeper.ClientCnxn - EventThread shut down
Exception in thread "main" org.apache.shardingsphere.orchestration.reg.exception.RegistryCenterException: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.shardingsphere.orchestration.reg.zookeeper.curator.CuratorZookeeperExceptionHandler.handleException(CuratorZookeeperExceptionHandler.java:53)
	at org.apache.shardingsphere.orchestration.reg.zookeeper.curator.CuratorZookeeperRegistryCenter.initCuratorClient(CuratorZookeeperRegistryCenter.java:115)
	at org.apache.shardingsphere.orchestration.reg.zookeeper.curator.CuratorZookeeperRegistryCenter.init(CuratorZookeeperRegistryCenter.java:75)
	at org.apache.shardingsphere.orchestration.internal.registry.RegistryCenterServiceLoader.load(RegistryCenterServiceLoader.java:53)
	at org.apache.shardingsphere.orchestration.internal.registry.ShardingOrchestrationFacade.<init>(ShardingOrchestrationFacade.java:58)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:109)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:83)
Caused by: org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.shardingsphere.orchestration.reg.zookeeper.curator.CuratorZookeeperRegistryCenter.initCuratorClient(CuratorZookeeperRegistryCenter.java:112)

**Comment by dongzl** [comment]
Hi @xiaobai022sdo , `4.0.0-RC3` is in release process, what's your `4.0.0-RC4`?

from the error log, I think the Sharding-Proxy can't connect ZooKeeper.

**Comment by xiaobai022sdo** [comment]
sharding-ui can connect  ZooKeeper 。why？

**Comment by dongzl** [comment]
what's your deployment structure for ZK, Sharding-Proxy and Sharding-ui?

They are on same machine or on different?

Can you provide you Sharding-Proxy Configuration file?

**Comment by terrymanu** [comment]
We never release version 4.0.0-RC4, can you make sure your version and change the title?

**Comment by terrymanu** [comment]
Hi, will close soon if no response anymore

**Comment by jlhuang9** [comment]
pom.xml      
zookeeper-3.4.6.jar  success
zookeeper-3.4.5.jar  has the error
