### ISSUE TITLE
sharding-jdbc-spring-boot-starter upgraded to 4.0.0-RC3 failed

### ISSUE THREAD

**Issue by infinite-m** [apache/incubator-shardingsphere#3601]
I upgraded from 4.0.0-RC2 to 4.0.0-RC3 ,but can not start project anymore.
the info is:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is java.sql.SQLDataException: Cannot determine value type from string 'NO'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640)
	... 141 common frames omitted
Caused by: java.sql.SQLDataException: Cannot determine value type from string 'NO'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:96)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1382)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:663)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:669)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.getColumnMetaDataList(TableMetaDataLoader.java:169)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.createTableMetaData(TableMetaDataLoader.java:147)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:112)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.access$100(TableMetaDataLoader.java:56)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader$1.execute(TableMetaDataLoader.java:101)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:62)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:94)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:87)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataInitializer.loadShardingTables(TableMetaDataInitializer.java:86)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataInitializer.load(TableMetaDataInitializer.java:78)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.createMetaData(ShardingRuntimeContext.java:73)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.<init>(ShardingRuntimeContext.java:60)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:49)
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:50)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration.shardingDataSource(SpringBootConfiguration.java:99)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3f115b3b.CGLIB$shardingDataSource$1(<generated>)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3f115b3b$$FastClassBySpringCGLIB$$bb41d1d4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$3f115b3b.shardingDataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 142 common frames omitted
Caused by: com.mysql.cj.exceptions.DataConversionException: Cannot determine value type from string 'NO'
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:116)
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:47)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:132)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:196)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1270)
```

**Comment by dongzl** [comment]
Hi @infinite-m ,

Please reference this issue: #3582 .

**Comment by infinite-m** [comment]
application.yml
```
spring:
  shardingsphere:
    datasource:
      names: master,slave0 #数据源名称，多数据源以逗号分隔
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxx?useUnicode=true&useSSL=false&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
        username: 
        password: 
        # 连接池配置
        initial-size: 1
        max-active: 200
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: select 'x' FROM DUAL
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 30000
        async-init: true
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxx?useUnicode=true&useSSL=false&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
        username: 
        password: 
        # 连接池配置
        initial-size: 1
        max-active: 200
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: select 'x' FROM DUAL
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 30000
        async-init: true
    props:
      sql.show: true #是否开启SQL显示，默认值: false
    sharding:
      default-table-strategy: #默认表分片策略
        complex:
          sharding-columns: id,created_time
          algorithm-class-name: xxx.YearComplexShardingAlgorithm
      tables:
        case_object:
          actual-data-nodes: ds0.case_object_$->{2017..2022}
          table-strategy: #分表策略
            complex:
              sharding-columns: id,created_time
              algorithm-class-name: xxxYearComplexShardingAlgorithm
      master-slave-rules:
        ds0:
          master-data-source-name: master #主库数据源名称
          slave-data-source-names: slave0 #从库数据源名称列表
      broadcast-tables: 
      binding-tables:
        - case_object, case_node
        - case_node, case_node_att
```
table info
```
CREATE TABLE `case_object_2017` (
  `id` varchar(32) NOT NULL COMMENT 'id',
  `case_code` varchar(20) DEFAULT NULL COMMENT '',
  `sub_dis_id` varchar(12) NOT NULL COMMENT '',
  `created_by` varchar(32) NOT NULL COMMENT '',
  `created_time` timestamp NOT NULL COMMENT '',
  `del_flag` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
```
