### ISSUE TITLE
4.0.0-RC3  Cannot determine value type from string 'NO'

### ISSUE THREAD

**Issue by xiaolongyuan** [apache/incubator-shardingsphere#3624]
```
Exception in thread "main" org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: java.sql.SQLDataException: Cannot determine value type from string 'NO'
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: CREATE TABLE IF NOT EXISTS t_address (address_id BIGINT NOT NULL, address_name VARCHAR(100) NOT NULL, PRIMARY KEY (address_id));
### Cause: java.sql.SQLDataException: Cannot determine value type from string 'NO'
; SQL []; Cannot determine value type from string 'NO'; nested exception is java.sql.SQLDataException: Cannot determine value type from string 'NO'
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:82)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy49.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:295)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy52.createTableIfNotExists(Unknown Source)
	at org.apache.shardingsphere.example.core.mybatis.service.OrderServiceImpl.initAddressTable(OrderServiceImpl.java:64)
	at org.apache.shardingsphere.example.core.mybatis.service.OrderServiceImpl.initEnvironment(OrderServiceImpl.java:60)
	at org.apache.shardingsphere.example.core.mybatis.service.OrderServiceImpl$$FastClassBySpringCGLIB$$bc37129f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at org.apache.shardingsphere.example.core.mybatis.service.OrderServiceImpl$$EnhancerBySpringCGLIB$$bfc2e16.initEnvironment(<generated>)
	at org.apache.shardingsphere.example.core.api.ExampleExecuteTemplate.run(ExampleExecuteTemplate.java:28)
	at org.apache.shardingsphere.example.sharding.spring.boot.mybatis.ExampleMain.main(ExampleMain.java:38)
Caused by: java.sql.SQLDataException: Cannot determine value type from string 'NO'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:96)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1382)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:663)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:669)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.getColumnMetaDataList(TableMetaDataLoader.java:169)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.createTableMetaData(TableMetaDataLoader.java:147)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:112)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.access$100(TableMetaDataLoader.java:56)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader$1.execute(TableMetaDataLoader.java:101)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:62)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:94)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:87)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataInitializer.load(TableMetaDataInitializer.java:66)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.refreshTableMetaDataForCreateTable(AbstractStatementExecutor.java:182)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.refreshMetaDataIfNeeded(AbstractStatementExecutor.java:168)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:135)
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:158)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:165)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 13 more
Caused by: com.mysql.cj.exceptions.DataConversionException: Cannot determine value type from string 'NO'
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:116)
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:47)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:132)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:196)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1270)
	... 43 more
```

**Comment by dongzl** [comment]
Hi @xiaolongyuan , you can reference this issue #3582  .

**Comment by KomachiSion** [comment]
duplicate with #3582 .
