### ISSUE TITLE
使用mysql-connector-java 8.0版本的时候driver-class-name: com.mysql.cj.jdbc.Driver报错

### ISSUE THREAD

**Issue by jimmyxu1214** [apache/incubator-shardingsphere#3698]
错误信息：
Caused by: java.sql.SQLDataException: Cannot determine value type from string 'NO'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:96)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:678)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:683)

错误代码：
![image](https://user-images.githubusercontent.com/580409/70434834-4280c600-1ac0-11ea-8bbc-e0938adb771b.png)
org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader 类169行
boolean isAutoIncrement = resultSet.getBoolean(IS_AUTOINCREMENT);

**Comment by dongzl** [comment]
Hi @jimmyxu1214 ,
** For English only**, other languages will not accept.

Please reference this issue #3582 .

**Comment by terrymanu** [comment]
** For English only**, other languages will not accept.
