### ISSUE TITLE
sharding-jdbc support mysql insert select dual?

### ISSUE THREAD

**Issue by quicksandznzn** [apache/incubator-shardingsphere#3711]
version:
<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>3.0.0.M4</version>
        </dependency>

when i execute this sql 
insert into table (a,b,c) select 1,2,3 from dual WHERE not exists (select a from table  where a=1);  
error:
### Cause: java.lang.UnsupportedOperationException: Cannot INSERT SELECT
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 51 more
Caused by: java.lang.UnsupportedOperationException: Cannot INSERT SELECT
	at io.shardingsphere.core.parsing.parser.sql.dml.insert.AbstractInsertParser.parse(AbstractInsertParser.java:69)
	at io.shardingsphere.core.parsing.parser.sql.dml.insert.AbstractInsertParser.parse(AbstractInsertParser.java:41)
	at io.shardingsphere.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:60)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:91)
	at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:229)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:137)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy115.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 57 more

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by quicksandznzn** [comment]
@terrymanu what should I change

**Comment by terrymanu** [comment]
Can you try to version 4.x? the version 3.x is out of service.

**Comment by SteNicholas** [comment]
@quicksandznzn Please upgrade the version to 4.x. In 4.x version, MySQL DMLStatement supports insert select case. You can refer to `insert` of `DMLStatement.g4` file.

**Comment by terrymanu** [comment]
Cannot support for `insert into ... select ...`
