### ISSUE TITLE
Sharding-JDBC: mysql jdbc driver 6.0.6 error

### ISSUE THREAD

**Issue by Willing-Xyz** [apache/incubator-shardingsphere#3720]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

4.0.0-RC3

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

[incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example) run successfully with mysql-connector-java 6.0.6

### Actual behavior

[incubator-shardingsphere-example](https://github.com/apache/incubator-shardingsphere-example) run failed with mysql-connector-java 6.0.6

**Comment by terrymanu** [comment]
Can you provide the exception?

**Comment by Willing-Xyz** [comment]
mysql: 5.7.27

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "YES"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.mysql.cj.core.io.MysqlTextValueDecoder.decodeDouble(MysqlTextValueDecoder.java:222)
	at com.mysql.cj.core.io.StringConverter.createFromBytes(StringConverter.java:104)
	at com.mysql.cj.core.io.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:232)
	at com.mysql.cj.mysqla.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:183)
	at com.mysql.cj.mysqla.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:225)
	at com.mysql.cj.mysqla.result.ByteArrayRow.getValue(ByteArrayRow.java:84)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:630)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:721)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:725)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.getColumnMetaDataList(TableMetaDataLoader.java:169)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.createTableMetaData(TableMetaDataLoader.java:147)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:112)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.access$100(TableMetaDataLoader.java:56)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader$1.execute(TableMetaDataLoader.java:101)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
	at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:62)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:94)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:87)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataInitializer.loadShardingTables(TableMetaDataInitializer.java:86)
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataInitializer.load(TableMetaDataInitializer.java:78)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.createMetaData(ShardingRuntimeContext.java:73)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.<init>(ShardingRuntimeContext.java:60)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:49)
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:50)
	at org.apache.shardingsphere.example.sharding.raw.jdbc.config.ShardingDatabasesAndTablesConfigurationPrecise.getDataSource(ShardingDatabasesAndTablesConfigurationPrecise.java:47)
	at org.apache.shardingsphere.example.sharding.raw.jdbc.factory.DataSourceFactory.newInstance(DataSourceFactory.java:39)
	at org.apache.shardingsphere.example.sharding.raw.jdbc.JavaConfigurationExampleMain.main(JavaConfigurationExampleMain.java:41)
```

**Comment by dongzl** [comment]
Please reference this issue #3582 , Thanks!
