### ISSUE TITLE
mysql-connector-java 8 But not support Column IS_AUTOINCREMENT

### ISSUE THREAD

**Issue by jeebeys** [apache/incubator-shardingsphere#3727]
Caused by: java.sql.SQLDataException: Cannot determine value type from string 'NO'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:96) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1382) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:663) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getBoolean(ResultSetImpl.java:669) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at org.apache.commons.dbcp.DelegatingResultSet.getBoolean(DelegatingResultSet.java:266) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.getColumnMetaDataList(TableMetaDataLoader.java:169) ~[sharding-core-execute-4.0.0-RC3.jar:4.0.0-RC3]
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.createTableMetaData(TableMetaDataLoader.java:147) ~[sharding-core-execute-4.0.0-RC3.jar:4.0.0-RC3]
	at org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader.load(TableMetaDataLoader.java:112) ~[sharding-core-execute-4.0.0-RC3.jar:4.0.0-RC3]

 try (ResultSet resultSet = connection.getMetaData().getColumns(catalog, null, actualTableName, "%")) {
            while (resultSet.next()) {
                String columnName = resultSet.getString(COLUMN_NAME);
                String columnType = resultSet.getString(TYPE_NAME);
                boolean isPrimaryKey = primaryKeys.contains(columnName);
                boolean isNotNull = isPrimaryKey || !resultSet.getBoolean(IS_NULLABLE);
                boolean isAutoIncrement = resultSet.getBoolean(IS_AUTOINCREMENT);
//---------------------------------------------------------------------------------------------------
                Optional<ColumnMetaData> columnMetaData = getColumnMetaData(logicTableName, columnName, columnType, isPrimaryKey,
                        isNotNull, isAutoIncrement, generateKeyColumnName, encryptRule, derivedColumns);
                if (columnMetaData.isPresent()) {
                    result.add(columnMetaData.get());
                }
            }
        }

**Comment by dongzl** [comment]
Please reference this issue #3582 , Thanks!

**Comment by jeebeys** [comment]
#3582

**Comment by jeebeys** [comment]
use mysql-connector-java 5.x 's  com.mysql.jdbc.Driver  will be ok
