### ISSUE TITLE
Error in execute  ShardingPreparedStatement.getGeneratedKey()

### ISSUE THREAD

**Issue by ljyhust** [apache/incubator-shardingsphere#3745]
Error when I use mybatis to insert one entity and get generate id to entity. 

version:  4.0.0-RC2

My code:
```java
@Select({"insert into user_info (user_id, user_name) values (#{userId}, #{userName})"})
@Options(keyProperty = "id", useGeneratedKeys = true)
int insertUser(@Param("userId") String userId, @Param("userName") String userName);
```

The Error is:
```
Caused by: java.lang.ClassCastException: org.apache.shardingsphere.core.optimize.transparent.statement.TransparentOptimizedStatement cannot be cast to org.apache.shardingsphere.core.optimize.sharding.statement.dml.ShardingInsertOptimizedStatement
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.getGeneratedKey(ShardingPreparedStatement.java:194)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.getGeneratedKeys(ShardingPreparedStatement.java:180)
```

error maybe cause by this method in class ShardingPreparedStatement. 
```java
private Optional<GeneratedKey> getGeneratedKey() {
        return null != this.sqlRouteResult && this.sqlRouteResult.getOptimizedStatement().getSQLStatement() instanceof InsertStatement ? ((ShardingInsertOptimizedStatement)this.sqlRouteResult.getOptimizedStatement()).getGeneratedKey() : Optional.absent();
    }
```

**Comment by terrymanu** [comment]
Can you try version 4.0.0-RC3?

**Comment by ljyhust** [comment]
OK. let's try

**Comment by ljyhust** [comment]
4.0.0-RC3  is OK

**Comment by domcj** [comment]
i miss this issue too,how to handle it
