### ISSUE TITLE
4.0.0-RC3：Cannot determine value type from string 'NO'

### ISSUE THREAD

**Issue by crossdream** [apache/incubator-shardingsphere#3747]
![TableMetaDataLoader](https://user-images.githubusercontent.com/7107303/70983648-0d91f600-20f4-11ea-8391-d8d237018b4d.png)

![rc3](https://user-images.githubusercontent.com/7107303/70983736-32866900-20f4-11ea-8d2a-95fe83f129e1.png)

`Caused by: com.mysql.cj.exceptions.DataConversionException: Cannot determine value type from string 'NO'
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:116)
	at com.mysql.cj.result.BooleanValueFactory.createFromBytes(BooleanValueFactory.java:47)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeByteArray(MysqlTextValueDecoder.java:132)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:196)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241)
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1270)
	... 101 common frames omitted
`

**Comment by dongzl** [comment]
Hi @crossdream , reference this issue #3582 .
