### ISSUE TITLE
‘NullPointerException’ when getting database index

### ISSUE THREAD

**Issue by software-market** [apache/incubator-shardingsphere#3854]
the environment  is that sharding-jdbc-4.0.0-rc3,sqlserver2012. Hibernate. Dbcp2 connection pool. Triggered when getting a database index. I  think that  Using DBCP directly does not have this problem. This is a screenshot of sharding- JDBC
![exception](https://user-images.githubusercontent.com/31737411/71704604-429d8880-2e16-11ea-885a-f419e27cd567.png)

In this class, there is a NullPointerException, which can be run without an NullPointerException，So what's the problem? How does it work?

**Comment by terrymanu** [comment]
Hi, can you change the title for search friendly?

**Comment by software-market** [comment]
@terrymanu

**Comment by tristaZero** [comment]
@software-market  Hi could your give more details? Such as, who is null? resultSet or resultSet.getString(i)?

@KomachiSion Hi, i found you are the author of this class, could you provide some helps to him？ Thanks.

**Comment by KomachiSion** [comment]
@software-market , Can you provide full stack information?

**Comment by software-market** [comment]
This exception is thrown when hibernate is initialized . If I remove the ‘<property name="hibernate.hbm2ddl.auto">update</property>’ exception in the configuration, it will not appear. 
@tristaZero 
resultSet.getString(i)
@KomachiSion 
exception stack information.

{INFO } [2020-01-08 13:03:25,986] <org.hibernate.tool.hbm2ddl.SchemaUpdate> : updating schema
{ERROR} [2020-01-08 13:03:39,758] <org.hibernate.tool.hbm2ddl.SchemaUpdate> : could not complete schema update
java.lang.NullPointerException
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.DatabaseMetaDataResultSet.generateDatabaseMetaDataObject(DatabaseMetaDataResultSet.java:109)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.DatabaseMetaDataResultSet.initIterator(DatabaseMetaDataResultSet.java:90)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.DatabaseMetaDataResultSet.<init>(DatabaseMetaDataResultSet.java:73)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.metadata.ResultSetReturnedDatabaseMetaData.getIndexInfo(ResultSetReturnedDatabaseMetaData.java:212)
	at org.hibernate.tool.hbm2ddl.TableMetadata.initIndexes(TableMetadata.java:153)
	at org.hibernate.tool.hbm2ddl.TableMetadata.<init>(TableMetadata.java:58)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.getTableMetadata(DatabaseMetadata.java:113)
	at org.hibernate.cfg.Configuration.generateSchemaUpdateScript(Configuration.java:981)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:187)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:346)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1327)
	at org.hibernate.cfg.AnnotationConfiguration.buildSessionFactory(AnnotationConfiguration.java:867)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:814)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:732)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:211)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1369)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1335)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:473)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:264)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:423)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:728)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:380)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.xxx.server.service.ServiceManager.start(ServiceManager.java:60)
	at com.xxx.server.service.ServiceManager.<init>(ServiceManager.java:52)
	at com.weiguanai.server.service.ServiceManager.getInstance(ServiceManager.java:38)
	at com.xxx.server.service.ServiceLocator.getTestService(ServiceLocator.java:87)
	at com.xxx.server.test.Test.doPost(Test.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1195)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by KomachiSion** [comment]
@software-market Sorry, I don't have SQLserver environment, can you use **original datasource** to print the result of `getIndexInfo`

example code like 

```java
DatabaseMetaData metaData = connection.getMetaData();
ResultSet rs = metaData.getIndexInfo("xx", "xxxx", "xxx", false, false);
```

**Comment by software-market** [comment]
@KomachiSion Sorry, I tested it again and it returns null on rs.getString ("INDEX_NAME"). But I see that when rs.getShort ("TYPE")! = 0, "org.hibernate.tool.hbm2ddl.TableMetadata # initIndexes" will get rs.getString ("INDEX_NAME"). 
If shardingDataSource is used, when rs.getShort ("TYPE") == 0, a nullPointException will occur. I don't know if this is a problem.
![123333333](https://user-images.githubusercontent.com/31737411/72032577-ba622c00-32ca-11ea-9c04-bcfeda423106.png)

**Comment by KomachiSion** [comment]
@software-market I never used SQLserver, so I'm not sure why SQLServer return null index.

Can you have more test about `getIndexInfo` for SQLServer?
1. Is the type=0 and index_name=`null` always be returned by `getIndexInfo` for SQLServer?
2. if be not always, which situation will be returned, and  which situation will not.

Thanks.

I will also try to build a SQLServer environment to do some research.

**Comment by software-market** [comment]
@KomachiSion I use the native jdbc to find that the problem still exists. When viewing https://docs.oracle.com/javase/8/docs/api/, I see the introduction of getIndexInfo

INDEX_NAME String => index name; null when TYPE is tableIndexStatistic
TYPE short => index type:
tableIndexStatistic-this identifies table statistics that are returned in conjuction with a table's index descriptions
tableIndexClustered-this is a clustered index
tableIndexHashed-this is a hashed index
tableIndexOther-this is some other style of index

**Comment by KomachiSion** [comment]
> https://docs.oracle.com/javase/8/docs/api/

Thanks
