### ISSUE TITLE
proxy select table throw NullPointerException!

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#3905]
use:sharding-proxy-4.0.0

stdout.log :
`
[ERROR] 20:47:17.372 [ShardingSphere-Command-13] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: null
        at org.apache.shardingsphere.shardingproxy.backend.response.query.QueryHeader.<init>(QueryHeader.java:67)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.getQueryHeaders(ProxySQLExecuteCallback.java:89)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:81)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:73)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:45)
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:79)
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:61)
        at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)
        at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102)
        at org.apache.shardingsphere.core.execute.engine.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:82)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:99)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:84)
        at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

`

proxy log:
`
2020-01-08 20:55:48,644 [ShardingSphere-Command-2] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-01-08 20:55:48,645 [ShardingSphere-Command-2] INFO [ShardingSphere-SQL] Logic SQL: /* ApplicationName=DBeaver 6.1.2 - Main */ SET SQL_SELECT_LIMIT=200
2020-01-08 20:55:48,645 [ShardingSphere-Command-2] INFO [ShardingSphere-SQL] SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.SetStatement@178abd17, tablesContext=TablesContext(tables=[], schema=Optional.absent()))
2020-01-08 20:55:48,645 [ShardingSphere-Command-2] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SET SQL_SELECT_LIMIT=200
2020-01-08 20:55:48,658 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Logic SQL: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets limit 10
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] SQLStatement: SelectSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@77adb0a6, tablesContext=TablesContext(tables=[Table(name=t_role_assets, alias=Optional.absent())], schema=Optional.absent())), projectionsContext=ProjectionsContext(startIndex=50, stopIndex=50, distinctRow=false, projections=[ShorthandProjection(owner=Optional.absent())], columnLabels=[roleid, dailydiamondconsume, dailyrecharge, diamond, energy, gold, guildgold, roleexp, totaldiamond, totaldropgold, totalexp, totalrecharge, vippoint, energytime]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@5dd9ba9a, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@8965fd, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@1934d0c0, containsSubquery=false)
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets0 limit 10
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets1 limit 10
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets2 limit 10
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub1 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets0 limit 10
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub1 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets1 limit 10
2020-01-08 20:55:48,659 [ShardingSphere-Command-14] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub1 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SELECT * from t_role_assets2 limit 10
2020-01-08 20:55:48,670 [ShardingSphere-Command-4] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-01-08 20:55:48,670 [ShardingSphere-Command-4] INFO [ShardingSphere-SQL] Logic SQL: /* ApplicationName=DBeaver 6.1.2 - Main */ SET SQL_SELECT_LIMIT=DEFAULT
2020-01-08 20:55:48,670 [ShardingSphere-Command-4] INFO [ShardingSphere-SQL] SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.SetStatement@6d0df86d, tablesContext=TablesContext(tables=[], schema=Optional.absent()))
2020-01-08 20:55:48,670 [ShardingSphere-Command-4] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SET SQL_SELECT_LIMIT=DEFAULT
2020-01-08 20:55:48,675 [ShardingSphere-Command-5] INFO [ShardingSphere-SQL] Rule Type: sharding
2020-01-08 20:55:48,675 [ShardingSphere-Command-5] INFO [ShardingSphere-SQL] Logic SQL: /* ApplicationName=DBeaver 6.1.2 - Main */ SHOW WARNINGS
2020-01-08 20:55:48,675 [ShardingSphere-Command-5] INFO [ShardingSphere-SQL] SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.dialect.mysql.ShowOtherStatement@50305fb5, tablesContext=TablesContext(tables=[], schema=Optional.absent()))
2020-01-08 20:55:48,675 [ShardingSphere-Command-5] INFO [ShardingSphere-SQL] Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 6.1.2 - Main */ SHOW WARNINGS

`

**Comment by wangjing112** [comment]
but sharding-jdbc 4.0.0.rc2 work fine.

**Comment by SteNicholas** [comment]
@wangjing112 Could u please provider your configuration?

**Comment by wangjing112** [comment]
i found when alter table add columu varchar then throw exception on select the table.
but restart proxy service,is work fine!

**Comment by SteNicholas** [comment]
> i found when alter table add columu varchar then throw exception on select the table.
> but restart proxy service,is work fine!

What's your version?
