### ISSUE TITLE
insert float type vaule report "10002 - 2Unknown exception"

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#4192]
Sharding-proxy version: 4.0.0-RC1

Problems encountered：
mysqldump file import to sharding-proxy found use insert and delete “float” type vaule report `10002 - 2Unknown exception: [For input string: "5.251"],`

- sql:`insert into test VALUES (907,907,'Biomaterials ,'BIOMATER','2047',5.251);` But modify vaule '5.251' to '5' can success insert. 

- show desc backend database table structure：
CREATE TABLE `test_1` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `ran` int(255) DEFAULT NULL,
  `full_title` varchar(255) DEFAULT NULL,
  `jcr_title` varchar(255) DEFAULT NULL,
  `sn` varchar(255) DEFAULT NULL,
  `factor` float(10,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12539 DEFAULT CHARSET=latin1
`

Sharding-proxy stdout logs：`[ERROR] 21:17:45.896 [ShardingSphere-Command-7] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.NumberFormatException: For input string: "5.251"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.math.BigInteger.<init>(BigInteger.java:461)
        at org.apache.shardingsphere.core.util.NumberUtil.getExactlyNumber(NumberUtil.java:72)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.ExpressionExtractor.extractCommonExpressionSegment(ExpressionExtractor.java:101)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.ExpressionExtractor.extractExpression(ExpressionExtractor.java:64)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.ExpressionExtractor.extract(ExpressionExtractor.java:53)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.buildCompareCondition(PredicateExtractor.java:172)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.buildCondition(PredicateExtractor.java:126)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extractConditionForParen(PredicateExtractor.java:114)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extractConditionInternal(PredicateExtractor.java:79)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extractConditionInternal(PredicateExtractor.java:73)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.PredicateExtractor.extract(PredicateExtractor.java:60)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.AbstractFromWhereExtractor.buildCondition(AbstractFromWhereExtractor.java:155)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.AbstractFromWhereExtractor.extractAndFillWhere(AbstractFromWhereExtractor.java:147)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.AbstractFromWhereExtractor.extract(AbstractFromWhereExtractor.java:76)
        at org.apache.shardingsphere.core.parse.antlr.extractor.impl.dml.select.AbstractFromWhereExtractor.extract(AbstractFromWhereExtractor.java:51)
        at org.apache.shardingsphere.core.parse.antlr.extractor.SQLSegmentsExtractorEngine.extract(SQLSegmentsExtractorEngine.java:47)
        at org.apache.shardingsphere.core.parse.antlr.AntlrParsingEngine.parse(AntlrParsingEngine.java:71)
        at org.apache.shardingsphere.core.parse.SQLParsingEngine.parse(SQLParsingEngine.java:61)
        at org.apache.shardingsphere.core.route.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:78)
        at org.apache.shardingsphere.core.route.StatementRoutingEngine.route(StatementRoutingEngine.java:56)
        at org.apache.shardingsphere.core.SimpleQueryShardingEngine.route(SimpleQueryShardingEngine.java:60)
        at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:64)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:86)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:57)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:79)
        at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:71)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by SteNicholas** [comment]
@lklkxcxc Could you please use the latest version of Sharding-Proxy to try this?And the SQL you provided is wrong.
`insert into test VALUES (907,907,'Biomaterials ,'BIOMATER','2047',5.251)`
should be
`insert into test VALUES (907,907,'Biomaterials','BIOMATER','2047',5.251)`

**Comment by lklkxcxc** [comment]
> @lklkxcxc Could you please use the latest version of Sharding-Proxy to try this?And the SQL you provided is wrong.
> `insert into test VALUES (907,907,'Biomaterials ,'BIOMATER','2047',5.251)`
> should be
> `insert into test VALUES (907,907,'Biomaterials','BIOMATER','2047',5.251)`

Use the latest version of Sharding-Proxy RC3 that  mysqldump import  is sucess. But I found a problem query  tables result only return id%0 record. Query backend database ds1 can  find id%1 record.

**Comment by SteNicholas** [comment]
@lklkxcxc The different between the above SQL is Biomaterials.
