### ISSUE TITLE
SQL query big table return '[java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space]'

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#4284]
Sharding-proxy version: 4.0.0-RC3

Problems encountered：Exec SQL `select * from basic;` hung ,The `basic` table have 4 million record and  5.2GB.

Sharding-proxy Config: start.sh -Xmx8g -Xms8g -Xmn4g,server.yaml use default parm. It is now extended to 16GB `-Xmx16g -Xms16g -Xmn12g` .

stdout.log：`[DEBUG] 15:14:08.595 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=2, active=1, idle=1, waiting=0)
Exception in thread "ShardingSphere-Command-13" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:567)
        at java.nio.CharBuffer.toString(CharBuffer.java:1241)
        at com.mysql.jdbc.StringUtils.toString(StringUtils.java:2253)
        at com.mysql.jdbc.ResultSetRow.getString(ResultSetRow.java:707)
        at com.mysql.jdbc.BufferRow.getString(BufferRow.java:527)
        at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5245)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5127)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
        at org.apache.shardingsphere.core.execute.sql.execute.result.QueryResultUtil.getValueByColumnType(QueryResultUtil.java:121)
        at org.apache.shardingsphere.core.execute.sql.execute.result.QueryResultUtil.getValue(QueryResultUtil.java:51)
        at org.apache.shardingsphere.core.execute.sql.execute.result.MemoryQueryResult.getResultData(MemoryQueryResult.java:79)
        at org.apache.shardingsphere.core.execute.sql.execute.result.MemoryQueryResult.<init>(MemoryQueryResult.java:60)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.createQueryResult(ProxySQLExecuteCallback.java:111)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:93)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:85)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxySQLExecuteCallback.executeSQL(ProxySQLExecuteCallback.java:54)
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:68)
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:57)
        at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:125)
        at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.parallelExecute(ShardingExecuteEngine.java:102)
        at org.apache.shardingsphere.core.execute.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:83)
        at org.apache.shardingsphere.core.execute.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:73)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:82)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:93)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:78)
        at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[WARN ] 15:14:38.595 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m12s379ms720µs175ns).
[DEBUG] 15:14:38.595 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
[DEBUG] 15:14:38.598 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 15:14:38.598 [HikariPool-1 connection closer] com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Closing connection com.mysql.jdbc.JDBC4Connection@61c9c3fd: (connection has passed idleTimeout)
[DEBUG] 15:15:08.598 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)`

**Comment by lklkxcxc** [comment]
The problem was resolved that add jdbc parm “useCursorFetch=true”

**Comment by kimmking** [comment]
Using stream query instead of memory query?

**Comment by lklkxcxc** [comment]
@kimmking Sharding -proxy will run out of memory if you use the memory

**Comment by tuohai666** [comment]
> @kimmking Sharding -proxy will run out of memory if you use the memory

@lklkxcxc Memory resultset will out of memory if the result size larger than the jvm heap. The 5.2GB you mentioned is not equal to the size in Sharding-Proxy. To resolve this problem, you can either enlarge Xmx or using stream resultset.
