### ISSUE TITLE
Execute SQL The scope of `in` statement to report an error

### ISSUE THREAD

**Issue by lklkxcxc** [apache/incubator-shardingsphere#4336]
- Problem description: 

execute the Group by statement to report an error：`[DEBUG] 11:56:21.590 [ShardingSphere-Command-8] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=select concept_name as conceptName,domain_id as domainId,vocabulary_id as vocabularyId,concept_synonym_name as conceptSynonymName from medical_dictionary where concept_id in (select mark_id from article_mark_relation where pmid = '26820994' group by mark_id))
[ERROR] 11:56:21.671 [ShardingSphere-Command-8] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IllegalStateException: Must have sharding column with subquery.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.checkSubqueryShardingValues(ShardingRouter.java:143)
        at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.route(ShardingRouter.java:103)
        at org.apache.shardingsphere.core.route.StatementRoutingEngine.route(StatementRoutingEngine.java:54)
        at org.apache.shardingsphere.core.SimpleQueryShardingEngine.route(SimpleQueryShardingEngine.java:58)
        at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:91)
        at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:74)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:78)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:64)
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:77)
        at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:54)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:86)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`
- SQL statement:`select concept_name as conceptName,domain_id as domainId,vocabulary_id as vocabularyId,concept_synonym_name as conceptSynonymName from medical_dictionary where concept_id in (select mark_id from article_mark_relation where pmid = '26820994' group by mark_id)`

- Sharding-proxy Version：4.0.0-RC3

Sharding -proxy we are in the last step of online, please help us

**Comment by terrymanu** [comment]
Hello, ShardingSphere can not support subquery for now.
FIY: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/
