### ISSUE TITLE
Bad parsing for column name

### ISSUE THREAD

**Issue by techzhou** [apache/incubator-shardingsphere#4371]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
When update one record with 4.0.0-RC1，I can update successfully.

### Actual behavior
When upgrade 4.0.0 (same as 4.0.0-RC3), I got error.

> The error occurred while setting parameters
   SQL: UPDATE xr_menu  SET parent_id=?, category=?, name=?, path=?, component=?, icon=?, sort=?, hidden=?, always_show=?, breadcrumb=?, no_cache=?, affix=?, remark=?, created_time=?, modified_time=?, version=?  WHERE id=?   AND version=?  AND deleted=0
   Cause: java.lang.IllegalStateException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199) ~[mybatis-3.5.3.jar:3.5.3]
	at jdk.internal.reflect.GeneratedMethodAccessor409.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.3.jar:2.0.3]
	... 138 common frames omitted
Caused by: java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429) ~[guava-20.0.jar:na]
	at org.apache.shardingsphere.sql.parser.core.extractor.util.ExtractorUtils.getFirstChildNode(ExtractorUtils.java:48) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.common.column.ColumnExtractor.getColumnSegment(ColumnExtractor.java:45) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.common.column.ColumnExtractor.extract(ColumnExtractor.java:41) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.common.column.ColumnsExtractor.extract(ColumnsExtractor.java:44) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.core.extractor.SQLSegmentsExtractorEngine.extract(SQLSegmentsExtractorEngine.java:52) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.core.SQLParseKernel.parse(SQLParseKernel.java:59) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse0(SQLParseEngine.java:70) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse(SQLParseEngine.java:52) ~[shardingsphere-sql-parser-engine-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse(ShardingRouter.java:86) ~[sharding-core-route-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:61) ~[sharding-core-route-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:59) ~[sharding-core-entry-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:85) ~[sharding-core-entry-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:68) ~[sharding-core-entry-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:249) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:190) ~[sharding-jdbc-core-4.0.0.jar:4.0.0]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.5.3.jar:3.5.3]
	at jdk.internal.reflect.GeneratedMethodAccessor431.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63) ~[mybatis-3.5.3.jar:3.5.3]
	at com.sun.proxy.$Proxy191.update(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54) ~[mybatis-plus-core-3.3.0.jar:3.3.0]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83) ~[mybatis-plus-core-3.3.0.jar:3.3.0]
	at jdk.internal.reflect.GeneratedMethodAccessor430.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.extension.plugins.OptimisticLockerInterceptor.intercept(OptimisticLockerInterceptor.java:150) ~[mybatis-plus-extension-3.3.0.jar:3.3.0]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.3.jar:3.5.3]
	at com.sun.proxy.$Proxy190.update(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197) ~[mybatis-3.5.3.jar:3.5.3]
	... 142 common frames omitted

### Reason analyze (If you can)
I simplely debug in 
https://github.com/apache/incubator-shardingsphere/blob/f81f4f03b1dd4b426adf1f29ffe93f9540ce6fc9/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/ShardingPreparedStatement.java#L178
I found sqlRouteResult lost sql parameter.
I try to insert record, it still lost all parameter.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

>shardingRule:
  tables:
    cgl_monitor:
      actualDataNodes: ds0.cgl_monitor$->{0..6}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: cgl_monitor$->{id % 7}

>UPDATE xr_menu  SET parent_id=?, category=?, name=?, path=?, component=?, icon=?, sort=?, hidden=?, always_show=?, breadcrumb=?, no_cache=?, affix=?, remark=?, created_time=?, modified_time=?, version=?  WHERE id=?   AND version=?  AND deleted=0

sharding rule configuration is simplified，because the table (xr_menu) is no need sharding

**Comment by geomonlin** [comment]
I tried  didn't find this question. Maybe you can provide more code or log details.

**Comment by techzhou** [comment]
I use mybatis as ORM,when I execute INSERT/UPDATE SQL, it report no parameters.
it only happen in version > 4.0.0-RC1
I tried debug it, then I found 
in 
https://github.com/apache/incubator-shardingsphere/blob/f81f4f03b1dd4b426adf1f29ffe93f9540ce6fc9/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/core/statement/ShardingPreparedStatement.java#L174-L184

when shard finisned, this. sqlRouteResult dosent contains any parameter
after 4.0.0-RC1, some breaking change?

**Comment by tristaZero** [comment]
Hi @techzhou i appreciated your debug action. You know, help comes behind self-help. :)

Your SQL and Sharding rule is simple and has been covered by our integrated tests, so i have no idea at the first glance. Could you debug it deep to help solve this issue?

Looking at the error log below, i speculated the cause is `bad parsing of SQL`.
```
org.apache.shardingsphere.sql.parser.core.extractor.impl.common.column.ColumnExtractor.getColumnSegment(ColumnExtractor.java:45) 
```
Sharding Parser can not extract corresponding columns, so could you make a break point at line 45 of ColumnExtractor.java or `sout` the value of `columnNode`.

**Comment by techzhou** [comment]
> Hi @techzhou i appreciated your debug action. You know, help comes behind self-help. :)
> 
> Your SQL and Sharding rule is simple and has been covered by our integrated tests, so i have no idea at the first glance. Other than that, i can not debug it in your condition, so could you debug it deep to help solve this issue?
> 
> Looking at the error log below, i speculated the cause is `bad parsing of SQL`.
> 
> ```
> org.apache.shardingsphere.sql.parser.core.extractor.impl.common.column.ColumnExtractor.getColumnSegment(ColumnExtractor.java:45) 
> ```
> 
> Sharding Parser can not extract corresponding columns, so could you make a break point at line 45 of ColumnExtractor.java or `sout` the value of `columnNode`.

thx your tip. found problem. my table has a column named 'component', cause fail.
just change column name, its ok
but still dosent understand what caused. maybe mysql 8 keywords include 'component'?, but I use percona 5.7.

**Comment by tristaZero** [comment]
Hi @techzhou 
`component` is a key word but not a reserved word of MySQL. 
Sorry to say it is a bug, and we will fix it ASAP.

Thanks for your feedback, good job. 🙂

**Comment by techzhou** [comment]
@tristaZero understand. thanks for your help

**Comment by tristaZero** [comment]
@techzhou Hi Are you interested in fixing this issue?
It is a simple one, so if you want to do, please look at the solution below. Otherwise, we can post it to community.

**Comment by tristaZero** [comment]
### What caused this issue? 
[Answer](https://github.com/apache/incubator-shardingsphere/issues/4371#issuecomment-591230503)

### How to solve this issue?
- [ ] Add `component` to  [unreservedWord](https://github.com/apache/incubator-shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/BaseRule.g4)(An Antlr rule definination).
- [ ] Raize a PR

**Comment by tristaZero** [comment]
Hi @techzhou 
Very appreciated your contributions to ShardingSphere community. Your PR will benifit all of the users. 👍
