### ISSUE TITLE
Use Navicat client open database, console print ClassCastException error log.

### ISSUE THREAD

**Issue by dongzl** [apache/incubator-shardingsphere#4640]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
Lastest master code
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
Use Navicat client, open database.
### Actual behavior
Can open database, but console print error log.
### Example codes for reproduce this issue (such as a github link).

```
[INFO ] 12:23:05.330 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x1b9ce6ac, L:/0:0:0:0:0:0:0:0:3308] READ: [id: 0x2d2ad5dd, L:/127.0.0.1:3308 - R:/127.0.0.1:50754]
[INFO ] 12:23:05.331 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x1b9ce6ac, L:/0:0:0:0:0:0:0:0:3308] READ COMPLETE
[INFO ] 12:23:06.075 [ShardingSphere-Command-0] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:06.075 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: SET NAMES utf8mb4
[INFO ] 12:23:06.075 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.SetStatement@3e5a50af, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@2c15d279)
[INFO ] 12:23:06.076 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET NAMES utf8mb4
[INFO ] 12:23:06.076 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_1 ::: SET NAMES utf8mb4
[INFO ] 12:23:06.164 [ShardingSphere-Command-1] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:06.164 [ShardingSphere-Command-1] ShardingSphere-SQL - Logic SQL: SHOW VARIABLES LIKE 'lower_case_%'
[INFO ] 12:23:06.164 [ShardingSphere-Command-1] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.dialect.mysql.ShowOtherStatement@46335750, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@8b98b9b)
[INFO ] 12:23:06.164 [ShardingSphere-Command-1] ShardingSphere-SQL - Actual SQL: ds_1 ::: SHOW VARIABLES LIKE 'lower_case_%'
[INFO ] 12:23:10.510 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x1b9ce6ac, L:/0:0:0:0:0:0:0:0:3308] READ: [id: 0xca3fe6d8, L:/127.0.0.1:3308 - R:/127.0.0.1:50807]
[INFO ] 12:23:10.511 [nioEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x1b9ce6ac, L:/0:0:0:0:0:0:0:0:3308] READ COMPLETE
[INFO ] 12:23:10.521 [ShardingSphere-Command-5] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:10.521 [ShardingSphere-Command-5] ShardingSphere-SQL - Logic SQL: SET NAMES utf8mb4
[INFO ] 12:23:10.521 [ShardingSphere-Command-5] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.SetStatement@5542c1ce, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@75a4a8d3)
[INFO ] 12:23:10.521 [ShardingSphere-Command-5] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET NAMES utf8mb4
[INFO ] 12:23:10.521 [ShardingSphere-Command-5] ShardingSphere-SQL - Actual SQL: ds_1 ::: SET NAMES utf8mb4
[INFO ] 12:23:10.575 [ShardingSphere-Command-7] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:10.576 [ShardingSphere-Command-7] ShardingSphere-SQL - Logic SQL: SHOW TABLE STATUS
[INFO ] 12:23:10.576 [ShardingSphere-Command-7] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.dialect.mysql.ShowTableStatusStatement@37669c66, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@33590e52)
[INFO ] 12:23:10.576 [ShardingSphere-Command-7] ShardingSphere-SQL - Actual SQL: ds_1 ::: SHOW TABLE STATUS
[INFO ] 12:23:10.616 [ShardingSphere-Command-4] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:10.617 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'databasemanager' UNION SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'databasemanager' UNION SELECT COUNT(*) FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = 'databasemanager'
[INFO ] 12:23:10.617 [ShardingSphere-Command-4] ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@3f763a5b, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@7ae644d8), tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@7ae644d8, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=14, distinctRow=false, projections=[AggregationProjection(type=COUNT, innerExpression=(*), alias=Optional.empty, derivedAggregationProjections=[], index=-1)], columnLabels=[COUNT(*)]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@7ee6828c, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@532eca15, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@5d8496c9, containsSubquery=false)
[INFO ] 12:23:10.617 [ShardingSphere-Command-4] ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'databasemanager' UNION SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'databasemanager' UNION SELECT COUNT(*) FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = 'databasemanager'
[INFO ] 12:23:10.671 [ShardingSphere-Command-8] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:10.671 [ShardingSphere-Command-8] ShardingSphere-SQL - Logic SQL: SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'databasemanager' ORDER BY TABLE_SCHEMA, TABLE_TYPE
[INFO ] 12:23:10.671 [ShardingSphere-Command-8] ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@5139217f, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@4386d13), tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@4386d13, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=42, distinctRow=false, projections=[ColumnProjection(owner=null, name=TABLE_SCHEMA, alias=Optional.empty), ColumnProjection(owner=null, name=TABLE_NAME, alias=Optional.empty), ColumnProjection(owner=null, name=TABLE_TYPE, alias=Optional.empty)], columnLabels=[TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@3db4633e, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@7c134aa6, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@6439ae82, containsSubquery=false)
[INFO ] 12:23:10.671 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'databasemanager' ORDER BY TABLE_SCHEMA, TABLE_TYPE
[INFO ] 12:23:10.690 [ShardingSphere-Command-9] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 12:23:10.690 [ShardingSphere-Command-9] ShardingSphere-SQL - Logic SQL: SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'databasemanager' ORDER BY TABLE_SCHEMA, TABLE_NAME
[INFO ] 12:23:10.690 [ShardingSphere-Command-9] ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@4a6ca2d2, tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@f6e35fb), tablesContext=org.apache.shardingsphere.sql.parser.relation.segment.table.TablesContext@f6e35fb, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=56, distinctRow=false, projections=[ColumnProjection(owner=null, name=TABLE_SCHEMA, alias=Optional.empty), ColumnProjection(owner=null, name=TABLE_NAME, alias=Optional.empty), ColumnProjection(owner=null, name=COLUMN_NAME, alias=Optional.empty), ColumnProjection(owner=null, name=COLUMN_TYPE, alias=Optional.empty)], columnLabels=[TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@6951246d, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@3eabbbb8, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@117ef48d, containsSubquery=false)
[INFO ] 12:23:10.691 [ShardingSphere-Command-9] ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'databasemanager' ORDER BY TABLE_SCHEMA, TABLE_NAME
[ERROR] 12:23:10.916 [ShardingSphere-Command-10] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.subquery.SubquerySegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.generic.TableSegment
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitJoinedTable(MySQLDMLVisitor.java:515)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitJoinedTable(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$JoinedTableContext.accept(MySQLStatementParser.java:6736)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.getTableSegments(MySQLDMLVisitor.java:338)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitTableReference(MySQLDMLVisitor.java:490)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitTableReference(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$TableReferenceContext.accept(MySQLStatementParser.java:6265)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitEscapedTableReference(MySQLDMLVisitor.java:476)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitEscapedTableReference(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$EscapedTableReferenceContext.accept(MySQLStatementParser.java:5936)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitTableReferences(MySQLDMLVisitor.java:469)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitTableReferences(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$TableReferencesContext.accept(MySQLStatementParser.java:5880)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitFromClause(MySQLDMLVisitor.java:461)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitFromClause(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$FromClauseContext.accept(MySQLStatementParser.java:5835)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitSelectClause(MySQLDMLVisitor.java:315)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitSelectClause(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$SelectClauseContext.accept(MySQLStatementParser.java:4542)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitUnionClause(MySQLDMLVisitor.java:303)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitUnionClause(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$UnionClauseContext.accept(MySQLStatementParser.java:4437)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitSelect(MySQLDMLVisitor.java:295)
	at org.apache.shardingsphere.sql.parser.visitor.impl.MySQLDMLVisitor.visitSelect(MySQLDMLVisitor.java:119)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$SelectContext.accept(MySQLStatementParser.java:3095)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:72)
	at org.apache.shardingsphere.sql.parser.SQLParserEngine.parse(SQLParserEngine.java:53)
	at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:69)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:65)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:70)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:58)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:89)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kimmking** [comment]
> java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.subquery.SubquerySegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.generic.TableSegment

I guess the latest TableSegment/QuerySegment refactoring is related.
@tristaZero

**Comment by dongzl** [comment]
The error SQL:
```
SELECT DISTINCT ROUTINE_SCHEMA, ROUTINE_NAME, PARAMS.PARAMETER FROM information_schema.ROUTINES LEFT JOIN ( SELECT SPECIFIC_SCHEMA, SPECIFIC_NAME, GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'databasemanager' ORDER BY ROUTINE_SCHEMA
```

**Comment by tristaZero** [comment]
Thanks @dongzl
Your feedback is a great help for me. :)

**Comment by kimmking** [comment]
@dongzl @tristaZero should we add a log to show the origin SQL when parse failed?
