### ISSUE TITLE
io.seata.config.ConfigFuture - config operation timeout,cost:5002 ms

### ISSUE THREAD

**Issue by juaihua** [apache/incubator-shardingsphere#4884]
hi, brothers and sisters
i am looking for integrate seata into sharding-proxy, and i got seata spi package by compiling source code at with git tag 4.0. when i start proxy , i got this:

[ERROR] 13:58:33.244 [timeoutChecker_1] io.seata.config.ConfigFuture - config operation timeout,cost:5004 ms,op:GET,dataId:service.vgroup_mapping.raw-jdbc-group
[ERROR] 13:58:33.244 [timeoutChecker_1] i.s.c.r.n.AbstractRpcRemotingClient - no available server to connect.

so what shall i do else?  by the way i start the seate-server, but useless... 

please, thanks !!

**Comment by kimmking** [comment]
Refer:

- [Apache ShardingSphere 整合 Seata AT 分布式事务](https://www.infoq.cn/article/w6WKHscKTPa3-)QMQI4gR
- [transaction-base-seata-raw-jdbc-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-base-seata-raw-jdbc-example)

**Comment by juaihua** [comment]
> Refer:
> 
> * [Apache ShardingSphere 整合 Seata AT 分布式事务](https://www.infoq.cn/article/w6WKHscKTPa3-QMQI4gR)
> * [transaction-base-seata-raw-jdbc-example](https://github.com/apache/incubator-shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-base-seata-raw-jdbc-example)


yes , i start seata and nocas successfully,  but  **shard-proxy** response to me this:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.seata.tm.TMClient.init(TMClient.java:34)
	at org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingTransactionManager.initSeataRPCClient(SeataATShardingTransactionManager.java:118)
	at org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingTransactionManager.init(SeataATShardingTransactionManager.java:55)
	at org.apache.shardingsphere.transaction.ShardingTransactionManagerEngine.init(ShardingTransactionManagerEngine.java:69)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.<init>(JDBCBackendDataSource.java:68)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchema.<init>(LogicSchema.java:63)
	at org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema.<init>(ShardingSchema.java:70)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemaFactory.newInstance(LogicSchemaFactory.java:56)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.initSchemas(LogicSchemas.java:104)
	at org.apache.shardingsphere.shardingproxy.backend.schema.LogicSchemas.init(LogicSchemas.java:94)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:116)
	at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:83)
Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.ConfigurationProvider[Nacos] and classloader : sun.misc.Launcher$AppClassLoader@b4c966a

**Comment by cherrylzhao** [comment]
you should make sure 'transaction.service.group = my_test_tx_group' of seata.conf is same with seata-server side configuration

**Comment by cherrylzhao** [comment]
I'll close it if you don't have any other question.
