### ISSUE TITLE
proxool pool ,jdbc yaml can't run proxy.ProxoolDataSource cannot be cast to YamlDataSourceParameter

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#4901]
use proxool pool in jdbc is work fine;
the cfg

dataSources:
  db0: !!org.logicalcobwebs.proxool.ProxoolDataSource
    alias: raid-game0
    driverUrl: jdbc:mysql://host0:3306/db0?useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=true&autoReconnect=true
    driver: com.mysql.jdbc.Driver
    user: root
    password: 123456
  db1: !!org.logicalcobwebs.proxool.ProxoolDataSource
    alias: raid-game1
    driverUrl: jdbc:mysql://host1:3306/db1?useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=true&autoReconnect=true
    driver: com.mysql.jdbc.Driver
    user: root
    password: 123456

in proxy error log:

Exception in thread "main" java.lang.ClassCastException: org.logicalcobwebs.proxool.ProxoolDataSource cannot be cast to org.apache.shardingsphere.shardingproxy.config.yaml.YamlDataSourceParameter
        at org.apache.shardingsphere.shardingproxy.util.DataSourceConverter.getDataSourceConfigurationMap(DataSourceConverter.java:85)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.getDataSourceConfigurationMap(Bootstrap.java:165)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.initShardingOrchestrationFacade(Bootstrap.java:151)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCenter(Bootstrap.java:110)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java:83)

**Comment by kimmking** [comment]
just remove " !!org.logicalcobwebs.proxool.ProxoolDataSource"

**Comment by terrymanu** [comment]
Wrong configuration, please check document or example
