### ISSUE TITLE
proxy4.0.1 PREPARE SQLParsingException

### ISSUE THREAD

**Issue by wangjing112** [apache/incubator-shardingsphere#4904]
proxy v4.0.1

exec sql:
PREPARE stmt1 FROM 'SELECT * from table where id=?';
set @id  = 12;
EXECUTE stmt1 USING @id;

error log:

line 1:0 no viable alternative at input 'PREPARE'
line 1:0 mismatched input 'PREPARE' expecting {SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE, GRANT, REVOKE, SET, WITH, DESC, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, CALL, USE, DESCRIBE, SHOW, REPLACE, START, RENAME}
[ERROR] 20:50:52.733 [ShardingSphere-Command-10] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `PREPARE stmt1 FROM 'SELECT * from t_role_friend_wait where roleId=?'`
        at org.apache.shardingsphere.sql.parser.core.parser.SQLParserEngine.parse(SQLParserEngine.java:73)
        at org.apache.shardingsphere.sql.parser.core.SQLParseKernel.parse(SQLParseKernel.java:58)
        at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:72)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:65)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:91)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by tuohai666** [comment]
Thanks for your report. The parser didn't support PREPARE yet. I'll try to fix it, this is the first step.

The next step is complicated. PREPARE and EXECUTE in this case are not real preparedStatement transport in the wire. They are all TEXT protocol. We don't have the mechanism to cache the parameter like @id.

BTW, can you show me the scenarios that you use PREPARE like that?

**Comment by wangjing112** [comment]
> @wangjing112, Thanks for your report. The parser didn't support PREPARE yet. I'll try to fix it, this is the first step.
> 
> The next step is complicated. PREPARE and EXECUTE in this case are not real preparedStatement transport in the wire. They are all TEXT protocol. We don't have the mechanism to cache the parameter like @id.
> 
> BTW, can you show me the scenarios that you use PREPARE like that?

it to test issuse #4707 by dbeaver.
in normal will not use PREPARE like this.

**Comment by tuohai666** [comment]
@wangjing112, thanks. Users can't benefit from this PREPARE usage, all commands still transport via COM_QUERY, the performance won't improve. And I never heard of someone use this SQL.  I suggest we don't fix this issue. What do you think?

**Comment by tuohai666** [comment]
@wangjing112, I have tried DBeaver, unbelievable good. Thanks.

**Comment by wangjing112** [comment]
> @wangjing112, thanks. Users can't benefit from this PREPARE usage, all commands still transport via COM_QUERY, the performance won't improve. And I never heard of someone use this SQL. I suggest we don't fix this issue until someone use like that normally. What do you think?

i agree!
