### ISSUE TITLE
execute statement what is "create database testName" error in sharding-proxy module

### ISSUE THREAD

**Issue by waterMeteors** [apache/incubator-shardingsphere#4936]
execute statement what is "create database testName" error in sharding-proxy module
the error information is:
![Uploading image.png…]()

i use version is 4.0.1

**Comment by waterMeteors** [comment]
the error information is : 
Exception occur:
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `CREATE DATABASE test_db`
        at org.apache.shardingsphere.sql.parser.core.parser.SQLParserEngine.parse(SQLParserEngine.java:73)
        at org.apache.shardingsphere.sql.parser.core.SQLParseKernel.parse(SQLParseKernel.java:58)
        at org.apache.shardingsphere.shardingproxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:72)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:65)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:72)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:91)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by ssxlulu** [comment]
For now, shardng-proxy can not support create database syntax.

**Comment by terrymanu** [comment]
The picture is invalid

**Comment by terrymanu** [comment]
Can not support `CREATE DATABASE test_db` because ShardingSphere using logic schema to process sharded data sources
