### ISSUE TITLE
if field name of table  is "call",encrypt not work.

### ISSUE THREAD

**Issue by lennonn** [apache/incubator-shardingsphere#4986]
### version 4.0.1
SQL: jdbcTemplate.update("INSERT INTO `test` (id,name,call) VALUES (1, '1', '1')");

### ERROR LOG:

line 1:28 no viable alternative at input '(id,name,call'
line 1:28 no viable alternative at input '(id,name,call'

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at shardingtest.Application.main(Application.java:31) [classes/:na]
Caused by: java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158) ~[guava-18.0.jar:na]
	at org.apache.shardingsphere.encrypt.rewrite.token.generator.impl.EncryptForUseDefaultInsertColumnsTokenGenerator.generateNewSQLToken(EncryptForUseDefaultInsertColumnsTokenGenerator.java:84) ~[encrypt-core-rewrite-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.encrypt.rewrite.token.generator.impl.EncryptForUseDefaultInsertColumnsTokenGenerator.generateSQLToken(EncryptForUseDefaultInsertColumnsTokenGenerator.java:62) ~[encrypt-core-rewrite-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.encrypt.rewrite.token.generator.impl.EncryptForUseDefaultInsertColumnsTokenGenerator.generateSQLToken(EncryptForUseDefaultInsertColumnsTokenGenerator.java:44) ~[encrypt-core-rewrite-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.underlying.rewrite.sql.token.generator.SQLTokenGenerators.generateSQLTokens(SQLTokenGenerators.java:78) ~[shardingsphere-rewrite-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.underlying.rewrite.context.SQLRewriteContext.generateSQLTokens(SQLRewriteContext.java:83) ~[shardingsphere-rewrite-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptStatement.getRewriteSQL(EncryptStatement.java:100) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptStatement.executeUpdate(EncryptStatement.java:124) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:531) ~[spring-jdbc-4.3.26.RELEASE.jar:4.3.26.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:528) ~[spring-jdbc-4.3.26.RELEASE.jar:4.3.26.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407) ~[spring-jdbc-4.3.26.RELEASE.jar:4.3.26.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:543) ~[spring-jdbc-4.3.26.RELEASE.jar:4.3.26.RELEASE]
	at shardingtest.Application.run(Application.java:59) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	... 5 common frames omitted

**Comment by yu199195** [comment]
can you show Encryptor rule config？

**Comment by lennonn** [comment]
> can you show Encryptor rule config？

```
encryptors:
  aes:
    props:
      aes.key.value: '123456'
    type: AES
tables:
  test:
    columns:
      call:
        assistedQueryColumn: ''
        cipherColumn: cipher_call
        encryptor: aes
        plainColumn: ''
```

![image](https://user-images.githubusercontent.com/8982513/77820562-185e1d00-711e-11ea-8b8d-ab2dbb32eba9.png)

**Comment by kimmking** [comment]
`call` is in MySQL `Keywords and Reserved Words`.
You can try:
```
`call` 
```

**Comment by lennonn** [comment]
It is not a keywords in oracle,
