### ISSUE TITLE
org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext

### ISSUE THREAD

**Issue by fyuan1030** [apache/incubator-shardingsphere#5123]
Caused by: java.lang.ClassCastException: org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.dml.PredicateExtractor.extractPredicate(PredicateExtractor.java:140) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.dml.PredicateExtractor.extractRecursiveWithParen(PredicateExtractor.java:124) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.dml.PredicateExtractor.extractPredicateSegment(PredicateExtractor.java:98) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.dml.PredicateExtractor.extractRecursiveWithLogicalOperation(PredicateExtractor.java:79) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.dml.PredicateExtractor.extract(PredicateExtractor.java:71) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.extractor.impl.dml.WhereExtractor.extract(WhereExtractor.java:48) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.extractor.SQLSegmentsExtractorEngine.extract(SQLSegmentsExtractorEngine.java:47) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.core.SQLParseKernel.parse(SQLParseKernel.java:59) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse0(SQLParseEngine.java:70) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.sql.parser.SQLParseEngine.parse(SQLParseEngine.java:52) ~[shardingsphere-sql-parser-engine-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.core.route.router.sharding.ShardingRouter.parse(ShardingRouter.java:86) ~[sharding-core-route-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.core.route.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:61) ~[sharding-core-route-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.core.PreparedQueryShardingEngine.route(PreparedQueryShardingEngine.java:59) ~[sharding-core-entry-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.core.BaseShardingEngine.executeRoute(BaseShardingEngine.java:85) ~[sharding-core-entry-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.core.BaseShardingEngine.shard(BaseShardingEngine.java:68) ~[sharding-core-entry-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.shard(ShardingPreparedStatement.java:249) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:190) ~[sharding-jdbc-core-4.0.1.jar:4.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy220.execute(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.4.5.jar:3.4.5]
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108) ~[pagehelper-5.1.7.jar:na]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy218.query(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.5.jar:3.4.5]
	... 83 common frames omitted
when I use this SQL querying, it told me this message. I want to know whether it is a bug? because when I use version 3.1 it is ok. but now, I use version 4.0.1, it wrong....
SQL :
select
    <include refid="No_Price_Column_List"/>
    from table_name
    where CURRENT_TIMESTAMP BETWEEN startTime AND endTime AND type=1
    AND a in
    <foreach collection="list" item="item" open="(" close=")" separator=",">
      #{item}
    </foreach>
    and status = 0 order by mtime asc

**Comment by fyuan1030** [comment]
when I change the SQL like this; it is ok
select
from table_name
where type=1 and CURRENT_TIMESTAMP BETWEEN startTime AND endTime 
AND a in

#{item}

and status = 0 order by mtime asc

**Comment by tristaZero** [comment]
@fyuan1030 Thanks for your feedback, I will give it a look.

**Comment by fyuan1030** [comment]
> @fyuan1030 Thanks for your feedback, I will give it a look.

it's my pleasure。

**Comment by tristaZero** [comment]
@fyuan1030 Hi AFAIK, `CURRENT_TIMESTAMP` is a function name for a query in MySQL, so the correct format in SELECT SQL is `select CURRENT_TIMESTAMP()`.
What's the meaning of `CURRENT_TIMESTAMP` in your SQL?

**Comment by fyuan1030** [comment]
> @fyuan1030 Hi AFAIK, `CURRENT_TIMESTAMP` is a function name for a query in MySQL, so the correct format in SELECT SQL is `select CURRENT_TIMESTAMP()`.
> What's the meaning of `CURRENT_TIMESTAMP` in your SQL?

@tristaZero hi dear young sister, thanks for your reply, I am sorry that I didn't reply you on time as I have so many things to do;  my mysql's version is 5.7.25, I can use **current_time** query time；
and when I change the position of current_time like this **select ? from tbl_name where ? and current_time between ? and ?** is correct. but this **select ? from tbl_name where current_time between ? and ?** is wrong;
![image](https://user-images.githubusercontent.com/38123832/79072246-91f72d00-7d12-11ea-9060-25cb25a08d17.png)

**Comment by tristaZero** [comment]
@fyuan1030 Hi I want to make sure `current_time` means the column in your table or the keyword of MySQL?

**Comment by fyuan1030** [comment]
@tristaZero keyword;

**Comment by tristaZero** [comment]
> CURRENT_TIMESTAMP

Hi but you use `CURRENT_TIMESTAMP `, not `current_time ` in this SQL.

**Comment by fyuan1030** [comment]
@tristaZero sorry, I spelt it wrong, but current_timestamp is right too;
![image](https://user-images.githubusercontent.com/38123832/79226304-ba0c9a80-7e90-11ea-9f18-8cbb78b82e58.png)

**Comment by tristaZero** [comment]
Hi Thanks for your feedback.
The doc[1] and [2] can help give us direction, so I raized a PR #5214 to fix this bug. :)
[1] https://dev.mysql.com/doc/refman/8.0/en/keywords.html
[2] https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html

**Comment by xuyong12** [comment]
i hava @fyuan1030 have you solved this problem？
